import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { startPlugins, type PluginsServer } from "./harness.js";

// Tier 3 — runtime introspection. The example's own (enable_typegen=true) binary
// generates a typed client from the data dir it just provisioned — no Zig source
// needed by the consumer, no network. The README shows the published
// `npx @zigbase/typegen` form users run against a remote URL.

let server: PluginsServer;
let outDir: string;
beforeAll(async () => { server = await startPlugins(); outDir = mkdtempSync(join(tmpdir(), "plug-gen-")); });
afterAll(() => { server?.stop(); try { rmSync(outDir, { recursive: true, force: true }); } catch { /* ignore */ } });

describe("plugins — runtime typegen (SDK Tier 3)", () => {
  it("generates a typed client from the running data dir (offline --data-dir)", () => {
    const out = join(outDir, "zbase.gen.ts");
    const r = spawnSync(server.bin, ["typegen", "--data-dir", server.dataDir, "--out", out], { stdio: "inherit" });
    expect(r.status).toBe(0);
    const gen = readFileSync(out, "utf8");
    // the generated client should carry the plugins collections + the typed factory.
    expect(gen).toContain("// generated by zigbase");
    expect(gen).toMatch(/createClient/);
    for (const col of ["authors", "posts", "comments", "commenters"]) expect(gen).toContain(col);
  });
});
