const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const zap = b.dependency("zap", .{ .target = target, .optimize = optimize });

    // The public library module. Consumers `zig fetch` this and import "zigbase".
    const zigbase_mod = b.addModule("zigbase", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    zigbase_mod.addIncludePath(b.path("vendor/sqlite"));
    zigbase_mod.addCSourceFile(.{
        .file = b.path("vendor/sqlite/sqlite3.c"),
        .flags = &.{
            "-DSQLITE_THREADSAFE=1",
            "-DSQLITE_DQS=0",
            "-DSQLITE_ENABLE_FTS5",
            "-DSQLITE_DEFAULT_FOREIGN_KEYS=1",
            "-DSQLITE_OMIT_LOAD_EXTENSION=1",
        },
    });
    zigbase_mod.addImport("zap", zap.module("zap"));

    // The shipped binary: a thin consumer of the library module.
    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    exe_mod.addImport("zigbase", zigbase_mod);

    const exe = b.addExecutable(.{ .name = "zigbase", .root_module = exe_mod });
    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    if (b.args) |args| run_cmd.addArgs(args);
    const run_step = b.step("run", "Run zigbase");
    run_step.dependOn(&run_cmd.step);

    // Unit tests run against the library module (where all internal test{} live).
    const tests = b.addTest(.{ .root_module = zigbase_mod });
    const run_tests = b.addRunArtifact(tests);
    const test_step = b.step("test", "Run all tests");
    test_step.dependOn(&run_tests.step);
}

/// Embed every file under `dir_rel` (relative to the consumer's build root) into
/// the binary as a static-asset manifest module. Wire it up like:
///
///     const zigbase_build = @import("zigbase");                  // dep's build.zig
///     const assets = zigbase_build.embedStaticDir(b, "frontend/dist");
///     exe_mod.addImport("static_assets", assets);
///
/// and in main.zig:
///
///     .static_files = .{ .embedded = &@import("static_assets").files }
///
/// The generated module declares `pub const files = [_]StaticFile{...}` with one
/// `@embedFile` per asset and a precomputed CRC32 content ETag.
pub fn embedStaticDir(b: *std.Build, dir_rel: []const u8) *std.Build.Module {
    const alloc = b.allocator;
    const io = b.graph.io;
    var dir = b.build_root.handle.openDir(io, dir_rel, .{ .iterate = true }) catch
        std.debug.panic("embedStaticDir: cannot open '{s}' — build the frontend first (e.g. `cd {s}/.. && npm run build`)", .{ dir_rel, dir_rel });
    defer dir.close(io);

    var names: std.ArrayList([]const u8) = .empty;
    var walker = dir.walk(alloc) catch @panic("OOM");
    defer walker.deinit();
    while (walker.next(io) catch |e| std.debug.panic("embedStaticDir: walk failed: {s}", .{@errorName(e)})) |entry| {
        if (entry.kind != .file) continue;
        names.append(alloc, alloc.dupe(u8, entry.path) catch @panic("OOM")) catch @panic("OOM");
    }
    std.mem.sort([]const u8, names.items, {}, struct {
        fn lt(_: void, x: []const u8, y: []const u8) bool {
            return std.mem.lessThan(u8, x, y);
        }
    }.lt);

    const wf = b.addWriteFiles();
    var src: std.ArrayList(u8) = .empty;
    src.appendSlice(alloc,
        \\//! Generated by zigbase's embedStaticDir — do not edit.
        \\pub const StaticFile = struct { path: []const u8, bytes: []const u8, etag: []const u8 };
        \\pub const files = [_]StaticFile{
        \\
    ) catch @panic("OOM");
    for (names.items) |rel| {
        _ = wf.addCopyFile(b.path(b.fmt("{s}/{s}", .{ dir_rel, rel })), rel);
        // no size limit: runs at build time on the developer's machine, not in the server
        const data = dir.readFileAlloc(io, rel, alloc, .unlimited) catch |e|
            std.debug.panic("embedStaticDir: cannot read '{s}/{s}': {s}", .{ dir_rel, rel, @errorName(e) });
        defer alloc.free(data);
        const crc = std.hash.Crc32.hash(data);
        // Assumes asset filenames are ASCII without '"' or '\' — true for Vite/Astro hashed output.
        src.appendSlice(alloc, b.fmt(
            "    .{{ .path = \"{s}\", .bytes = @embedFile(\"{s}\"), .etag = \"\\\"{x:0>8}\\\"\" }},\n",
            .{ rel, rel, crc },
        )) catch @panic("OOM");
    }
    src.appendSlice(alloc, "};\n") catch @panic("OOM");
    const manifest = wf.add("static_assets.zig", src.items);
    return b.createModule(.{ .root_source_file = manifest });
}
