// A repo-agnostic Markdown -> SuperMD transformer: no repo-specific paths,
// URLs or constants live here. It exists because publishing a canonical
// Markdown file as a SuperMD site page requires five transformations, in one
// line each below — the full why of each is in docs/generated-content.md,
// which is itself generated by an example consumer of this module
// (site/scripts/gen-docs-mirror.ts).
//
//   1. Frontmatter must be Ziggy, not YAML (see `frontmatter`/`ziggyRaw`).
//   2. Relative link targets become `$link.page(...)`/`.ref(...)` when they
//      resolve to a published page and an absolute URL when they do not —
//      decided by resolved path, never by file extension (see
//      `TransformOptions.published`/`githubBlobBase`).
//   3. Every heading gets an explicit `$heading.id(...)` via a leading empty
//      link (see `slugifyHeading`).
//   4. Fence languages can be remapped, mirror-only (see `fenceLangRemap`).
//   5. A leading `# Title` can be stripped, mirror-only (see
//      `stripLeadingTitle`).

export interface ZiggyRaw {
  readonly raw: string;
}

/** An unquoted Ziggy expression, e.g. `ziggyRaw('@date("2026-07-27T00:00:00")')`. */
export function ziggyRaw(src: string): ZiggyRaw {
  return { raw: src };
}

export type ZiggyValue =
  | string
  | number
  | boolean
  | ZiggyRaw
  | { readonly [k: string]: ZiggyValue };

/** A `ZiggyRaw` is structurally just `{ raw: string }`, so a nested object
 * whose only field is genuinely named `.raw` would be misread as an unquoted
 * expression. No frontmatter in this repo has such a field; a project that
 * grows one should brand `ZiggyRaw` with a symbol rather than widen this. */
function isZiggyRaw(v: ZiggyValue): v is ZiggyRaw {
  return typeof v === "object" && v !== null && "raw" in v && Object.keys(v).length === 1;
}

/** Render a single Ziggy value: string -> quoted+escaped, number/boolean ->
 * literal, ZiggyRaw -> verbatim, nested object -> inline `{ .k = v, .k = v }`
 * (empty object -> `{}`). No array support — no caller of this module needs
 * one; a project that does extends this function. */
function renderZiggyValue(v: ZiggyValue): string {
  if (isZiggyRaw(v)) return v.raw;
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  const keys = Object.keys(v);
  if (keys.length === 0) return "{}";
  const fields = keys.map((k) => `.${k} = ${renderZiggyValue(v[k])}`).join(", ");
  return `{ ${fields} }`;
}

/** Ziggy frontmatter block: `---`, one `.field = value,` per line, `---`,
 * and a trailing blank line. `JSON.stringify` gives a correctly escaped
 * Ziggy string, since Ziggy strings share JSON's escaping rules. */
export function frontmatter(fields: Readonly<Record<string, ZiggyValue>>): string {
  const lines = ["---"];
  for (const [k, v] of Object.entries(fields)) {
    lines.push(`.${k} = ${renderZiggyValue(v)},`);
  }
  lines.push("---", "");
  return lines.join("\n");
}

/** Resolve a relative link target against the canonical file's directory. */
function resolveRepoPath(path: string, canonicalDir: string): string {
  const stack = canonicalDir ? canonicalDir.split("/") : [];
  for (const part of path.split("/")) {
    if (part === "" || part === ".") continue;
    else if (part === "..") stack.pop();
    else stack.push(part);
  }
  return stack.join("/");
}

/** One piece of a line, split at inline-code-span boundaries. */
interface LineSegment {
  /** The piece exactly as authored, a code span's own backtick delimiters
   * included — so joining every `text` reconstructs the line byte for byte. */
  text: string;
  /** True for a code span, false for the prose between spans. */
  code: boolean;
  /** What a reader sees: a code span's content with its delimiters removed and
   * CommonMark's flanking-space rule applied; `text` verbatim outside a span. */
  content: string;
}

/**
 * A code span's rendered content: delimiters dropped, and — per CommonMark —
 * one leading and one trailing space removed when the remainder begins and
 * ends with a space without being all spaces. That last rule is what makes
 * ``` `` `b` `` ``` a span whose content is a backtick-flanked `b` rather than
 * one padded with two spaces; those spaces are invisible to a reader and must
 * be invisible to `slugifyHeading` too, since whitespace there becomes a
 * hyphen apiece.
 */
function codeSpanContent(span: string, delim: number): string {
  const inner = span.slice(delim, span.length - delim);
  if (inner.startsWith(" ") && inner.endsWith(" ") && inner.trim() !== "") {
    return inner.slice(1, -1);
  }
  return inner;
}

/**
 * Split a line into alternating prose / inline-code-span pieces, per
 * CommonMark's backtick-string rule: a run of N backticks opens a span that is
 * closed by the next run of EXACTLY N, and a run with no such partner is
 * literal text — scanning then resumes at the run after it, not at the end of
 * the line.
 *
 * Both halves of that rule are load-bearing, and getting either wrong fails
 * silently rather than loudly:
 *
 *   - Closing on the first run of length >= N ends a ``-delimited span at an
 *     embedded lone backtick, so the tail of the author's code sample is read
 *     as prose and gets rewritten.
 *   - Treating an unmatched run as an opener switches every later
 *     transformation on the line off — the fence tracker's inversion bug (see
 *     `fenceDelimiter`) in miniature, one line wide.
 *
 * This knows nothing about fences and must not be asked to: only a line the
 * fence tracker in `transformBody` has already classified as non-fenced ever
 * reaches it.
 */
function splitCodeSpans(line: string): LineSegment[] {
  const runs: Array<{ start: number; len: number }> = [];
  for (let i = 0; i < line.length;) {
    if (line[i] !== "`") {
      i++;
      continue;
    }
    let j = i;
    while (j < line.length && line[j] === "`") j++;
    runs.push({ start: i, len: j - i }); // maximal run: a backtick string
    i = j;
  }

  const segments: LineSegment[] = [];
  let cursor = 0; // first byte of `line` not yet emitted
  for (let r = 0; r < runs.length; r++) {
    const open = runs[r];
    let close = -1;
    for (let c = r + 1; c < runs.length; c++) {
      if (runs[c].len === open.len) {
        close = c;
        break;
      }
    }
    if (close < 0) continue; // unmatched: literal text, keep scanning
    const end = runs[close].start + runs[close].len;
    if (open.start > cursor) {
      const text = line.slice(cursor, open.start);
      segments.push({ text, code: false, content: text });
    }
    const text = line.slice(open.start, end);
    segments.push({ text, code: true, content: codeSpanContent(text, open.len) });
    cursor = end;
    r = close; // the loop's r++ resumes at the run after the closer
  }
  if (cursor < line.length || segments.length === 0) {
    const text = line.slice(cursor);
    segments.push({ text, code: false, content: text });
  }
  return segments;
}

/**
 * GitHub-compatible heading slug. GitHub (and docs written against GitHub's
 * rendering) lowercases, strips inline emphasis markers, drops any character
 * that isn't a letter/number/space/hyphen/underscore, and turns each
 * remaining whitespace character into a `-` INDIVIDUALLY — not collapsed.
 * That last part matters: a heading like "Calling the backend — `apiFetch`"
 * has an em dash flanked by two spaces; removing just the dash leaves two
 * spaces, which become two hyphens ("calling-the-backend--apifetch"),
 * matching the double-hyphen anchor GitHub itself produces.
 *
 * Code spans are unwrapped through `splitCodeSpans` rather than a
 * `/`([^`]*)`/g` sweep, because that pattern reads a ``-run as an empty span
 * and so mis-parses every multi-backtick span: "`` `b` ``" came apart into two
 * empty spans plus a bare `` `b` ``, leaving the padding spaces behind and
 * slugging an extra hyphen into the anchor (issue #66).
 */
export function slugifyHeading(raw: string): string {
  const plain = splitCodeSpans(raw)
    .map((seg) => seg.content)
    .join("")
    .replace(/\*\*([^*]*)\*\*/g, "$1")
    .replace(/\*([^*]*)\*/g, "$1")
    .replace(/_([^_]*)_/g, "$1");
  return plain
    .toLowerCase()
    .trim()
    .replace(/[^\p{L}\p{N}\s_-]+/gu, "")
    .replace(/\s/g, "-");
}

/**
 * Rewrite one non-fenced, non-code-span STRETCH of a line's link TARGETS,
 * never link text — `rewriteLinksOutsideCodeSpans` is what feeds it. Every
 * relative target is resolved against `canonicalPath`'s directory and looked
 * up in `published`: a hit becomes a `$link.page(...)` Scripty directive
 * (optionally `.ref(...)` for a `#anchor`), and anything else — whatever its
 * file extension, since nothing here inspects one — becomes an absolute URL
 * under `githubBlobBase` (or `githubTreeBase` for a trailing-slash directory
 * target), with `onOffsiteLink` invoked so an unpublished-but-linked target
 * can be surfaced rather than quietly degrading.
 * A bare `#anchor` (same-page) target is left untouched — SuperMD's own
 * `[text](#anchor)` shorthand already handles it, once the target heading
 * carries a matching id.
 */
function rewriteLinksInLine(line: string, opts: TransformOptions): string {
  const canonicalPath = opts.canonicalPath;
  const dir = canonicalPath.includes("/")
    ? canonicalPath.slice(0, canonicalPath.lastIndexOf("/"))
    : "";
  return line.replace(/\]\(([^)\s]+)\)/g, (match, target: string) => {
    const hash = target.indexOf("#");
    const path = hash >= 0 ? target.slice(0, hash) : target;
    const anchor = hash >= 0 ? target.slice(hash + 1) : "";
    if (path === "") return match; // in-page anchor — SuperMD's `#id` shorthand
    if (path.startsWith("$")) return match; // already a Scripty directive
    if (/^(https?:|mailto:)/i.test(path)) return match; // absolute
    if (path.startsWith("/")) return match; // root-absolute, leave as authored

    const repoPath = resolveRepoPath(path, dir);
    const page = opts.published.get(repoPath);
    if (page) {
      const refPart = anchor ? `.ref(${JSON.stringify(anchor)})` : "";
      return `]($link.page(${JSON.stringify(page)})${refPart})`;
    }

    opts.onOffsiteLink?.(canonicalPath, path, repoPath);
    const base = path.endsWith("/") ? opts.githubTreeBase : opts.githubBlobBase;
    return `](${base}${repoPath}${anchor ? `#${anchor}` : ""})`;
  });
}

/**
 * `rewriteLinksInLine` applied to the parts of a line that are NOT inside an
 * inline code span.
 *
 * The fence tracker already keeps the link rewrite out of fenced blocks, on
 * the grounds that a link-shaped string in a code sample is sample text rather
 * than a link. An inline code span makes exactly the same claim in one line,
 * and before this split both ways of getting it wrong were silent (issue #66):
 * a published target inside a span became a `$link.page(...)` directive the
 * author never wrote — so a reader copying the sample copied something wrong —
 * and an unpublished one became a bare GitHub URL with no marker at all, plus
 * a spurious `onOffsiteLink` report for a link that does not exist.
 *
 * Nothing downstream catches either: `site/test/docs-mirror.sh`'s
 * rendered-HTML check strips `<pre>` and `<code>` before matching, precisely
 * so that a page documenting these directives may legitimately show them.
 */
function rewriteLinksOutsideCodeSpans(line: string, opts: TransformOptions): string {
  return splitCodeSpans(line)
    .map((seg) => (seg.code ? seg.text : rewriteLinksInLine(seg.text, opts)))
    .join("");
}

/**
 * Given a non-fenced ATX heading line, return it with a leading empty
 * `$heading.id(...)` link inserted. IDs are deduped per file the same way
 * GitHub dedupes duplicate heading text: repeats get `-1`, `-2`, … The id is
 * carried by a leading EMPTY link rather than wrapping the heading's own
 * text, because a heading like `## [Unreleased]` would then nest a link
 * inside a link, which CommonMark refuses to parse — the directive leaks
 * into the page as literal text and the heading gets no id at all.
 */
function addHeadingId(line: string, seen: Map<string, number>): string {
  const m = /^(#{1,6})\s+(.+)$/.exec(line);
  if (!m) return line;
  const [, hashes, text] = m;

  let slug = slugifyHeading(text);
  const count = seen.get(slug) ?? 0;
  seen.set(slug, count + 1);
  if (count > 0) slug = `${slug}-${count}`;

  return `${hashes} []($heading.id(${JSON.stringify(slug)})) ${text}`;
}

interface FenceDelimiter {
  /** Leading whitespace before the delimiter run. With `len` it gives the
   * offset of the info string within the original line, which is how
   * `remapFenceLang` substitutes a language without disturbing a byte around
   * it. */
  indent: string;
  /** The delimiter character: a backtick or a tilde. */
  char: string;
  /** How many of it — CommonMark's "at least three", and a closing fence must
   * be at least as long as the opening one. */
  len: number;
  /** Everything after the delimiter run, trimmed. Non-empty means this line
   * can only be an OPENING fence. */
  info: string;
}

/**
 * Recognise a fenced-code-block delimiter line, per CommonMark rather than the
 * common-case subset.
 *
 * Both relaxations here are load-bearing, and getting either wrong desyncs the
 * fence tracker for the whole rest of the file — silently, since an inverted
 * tracker produces valid-looking output with heading ids and link rewrites
 * simply missing (issue #76: `docs/islands.md`'s nested-fence example turned
 * off heading ids for the file's last two thirds, which then failed the site
 * build with `unknown ref` on two links whose targets had quietly lost their
 * `$heading.id`).
 *
 *   - The run is `{3,}`, not exactly three. A doc that shows fenced Markdown
 *     nests a ``` block inside a ```` one, and the inner closer must not be
 *     mistaken for an opener.
 *   - The info string is arbitrary text, not `[A-Za-z0-9_-]*`. SuperMD's own
 *     raw-HTML escape hatch is the fence info `=html`, and fences elsewhere
 *     carry attributes after the language.
 *
 * CommonMark's one restriction on a backtick fence's info string — it may not
 * contain a backtick — is what keeps a line of inline code from being read as
 * a fence, so it is enforced too.
 */
function fenceDelimiter(line: string): FenceDelimiter | null {
  const m = /^(\s*)(`{3,}|~{3,})(.*)$/.exec(line);
  if (!m) return null;
  const [, indent, run, rest] = m;
  const char = run[0];
  if (char === "`" && rest.includes("`")) return null;
  return { indent, char, len: run.length, info: rest.trim() };
}

/**
 * An opening fence line with its language substituted, or the line verbatim
 * when nothing maps. Only the FIRST token of the info string is a language;
 * anything after it is attributes and is preserved as authored.
 *
 * "As authored" is why this splices into the ORIGINAL line rather than
 * reassembling one from the parsed parts: a fence info string is arbitrary
 * text, so its whitespace can be significant (`title="a  b"` names a file with
 * two spaces in it) and the transform has no business normalising it.
 * Rebuilding the line from `info.split(/\s+/)` collapsed every run of
 * whitespace to one space, dropped any spacing between the delimiter and the
 * language, and dropped trailing whitespace — turning a remap of ONE token
 * into a rewrite of the whole line, and only on the lines that happened to map.
 */
function remapFenceLang(
  line: string,
  fence: FenceDelimiter,
  remap: Readonly<Record<string, string>>,
): string {
  if (fence.info === "") return line;
  const lang = fence.info.split(/\s/)[0];
  // `Object.hasOwn`, not a raw `remap[lang]`: `fenceLangRemap` is an ordinary
  // object literal, so its prototype is `Object.prototype` and a fence tagged
  // `constructor`, `toString`, `valueOf`, `hasOwnProperty` or `__proto__`
  // resolves to an inherited member instead of missing. Every one of those is
  // truthy, so the miss check below passed and the member was stringified into
  // the fence's language slot — ```` ```constructor ```` came out as the source
  // text of the `Object` constructor, spread over three lines (issue #67).
  //
  // The guard rather than a null-prototype copy of the table, because this
  // module exists to be copied (see docs/generated-content.md) and the caller
  // supplying that table is exactly the person who will not read this file: the
  // option stays a plain `Record`, which is what they will naturally pass.
  const mapped = Object.hasOwn(remap, lang) ? remap[lang] : undefined;
  if (!mapped) return line;
  // `info` is the line past the delimiter run, trimmed, so the language token
  // starts at that run's end plus whatever leading whitespace the trim ate.
  const restStart = fence.indent.length + fence.len;
  const rest = line.slice(restStart);
  const langStart = restStart + (rest.length - rest.trimStart().length);
  return line.slice(0, langStart) + mapped + line.slice(langStart + lang.length);
}

export interface TransformOptions {
  /** Repo-relative path of the canonical file; relative link targets resolve
   * against its directory. */
  canonicalPath: string;
  /** Repo path -> site page path, e.g. "docs/spa.md" -> "docs/spa". A hit
   * becomes `$link.page(...)`. */
  published: ReadonlyMap<string, string>;
  /** Absolute prefix a non-published FILE target falls back to, e.g.
   * "https://github.com/o/r/blob/main/". */
  githubBlobBase: string;
  /** Same, for a target ending in "/" (a directory). */
  githubTreeBase: string;
  /** Mirror-only fence-language substitutions, e.g. { jsonc: "json" }. */
  fenceLangRemap: Readonly<Record<string, string>>;
  /** Drop the body's own leading `# Title` (for a layout that renders its own
   * h1 from frontmatter). */
  stripLeadingTitle: boolean;
  /** Called when a link target is not published and degrades to an off-site
   * URL. `target` is as authored with any `#anchor` removed, `repoPath` is it
   * resolved against `canonicalPath`'s directory. Omitted = silent, which
   * makes an unpublished-but-linked page invisible; pass something. */
  onOffsiteLink?: (canonicalPath: string, target: string, repoPath: string) => void;
}

/**
 * Single line-by-line pass applying the link, heading-id, fence-remap and
 * title-strip transformations, sharing one fence tracker so link-rewriting,
 * heading-id assignment and the title strip never touch fenced code (a
 * link-shaped or heading-shaped string inside a code sample is sample text),
 * and so the fence-language remap only ever touches a fence's own opening
 * delimiter. The fence delimiter match tolerates leading whitespace — an
 * indented fence under a list item is still recognised.
 *
 * The tracker holds the OPEN fence's delimiter rather than a boolean, because
 * only a run of the same character that is at least as long and carries no
 * info string closes it (see `fenceDelimiter`). A boolean cannot express that,
 * and toggling on every delimiter-shaped line inverts the tracker for the rest
 * of the file at the first nested fence.
 *
 * `sawContent` tracks whether anything other than a blank line has been
 * emitted yet; it gates the title strip to the body's FIRST top-level
 * heading and nothing after it, and is set unconditionally by a fence
 * delimiter so a body that opens with a code block never has a later `#`
 * line mistaken for the title.
 */
export function transformBody(body: string, opts: TransformOptions): string {
  const headingIds = new Map<string, number>();
  let openFence: FenceDelimiter | null = null;
  // Starting "already stripped" is how the option is honoured: the strip
  // branch below only runs while this is false.
  let strippedTitle = !opts.stripLeadingTitle;
  let sawContent = false;
  const out: string[] = [];

  for (const line of body.split("\n")) {
    const fence = fenceDelimiter(line);
    if (openFence) {
      const closes = fence !== null &&
        fence.char === openFence.char &&
        fence.len >= openFence.len &&
        fence.info === "";
      if (closes) openFence = null;
      out.push(line); // fence body and closing delimiter alike: verbatim
      continue;
    }
    if (fence) {
      openFence = fence;
      sawContent = true;
      out.push(remapFenceLang(line, fence, opts.fenceLangRemap));
      continue;
    }

    if (!strippedTitle && !sawContent) {
      if (/^#\s+.+$/.test(line)) {
        strippedTitle = true; // drop it: no heading id, no toc entry, no body h1
        continue;
      }
      if (line.trim() === "") {
        out.push(line); // blank line before the title: keep scanning
        continue;
      }
      sawContent = true; // real content and no leading title — nothing to strip
    }

    out.push(addHeadingId(rewriteLinksOutsideCodeSpans(line, opts), headingIds));
  }

  return out.join("\n");
}
