// generated by zigbase — do not edit
// schema-hash: blog-fixture-v1
//
// In a consumer repo this file imports from "@zigbase/client" and
// "@zigbase/client/typed". In this in-repo fixture we import from the package
// source so it typechecks against the working tree without a built dist.
import { createClient as baseCreateClient, type Client } from "../../src/index.js";
import { withRealtime, type RealtimeEnabledClient } from "../../src/realtime-entry.js";
import type { ListResult } from "../../src/records.js";
import type { CursorPage } from "../../src/cursor.js";
import type { FileUrlOptions } from "../../src/files.js";
import {
  makeRecordService,
  makeTypedRealtime,
  makeTypedFiles,
  type CollectionMeta,
  type WithExpand,
  type StringOps,
  type NumberOps,
  type EnumOps,
  type RelOps,
  type Expr,
  type FieldExpr,
  type TypedFieldExpr,
  type RelationResolver,
  type RawTypedRealtime,
} from "../../src/typed/index.js";

// ---- Records --------------------------------------------------------------

export interface User {
  id: string;
  email: string;
  verified: boolean;
  name: string;
  created: string;
  updated: string;
}

export interface Tag {
  id: string;
  label: string;
}

export type PostStatus = "draft" | "published";

export interface Post {
  id: string;
  title: string;
  status: PostStatus;
  price: number;
  author: string; // related user id (maxSelect 1)
  tags: string[]; // related tag ids (maxSelect > 1)
  cover: string; // filename (maxSelect 1)
  created: string;
  updated: string;
}

// ---- Create / Update payloads ---------------------------------------------

export interface PostCreate {
  title: string; // required
  status?: PostStatus;
  price?: number;
  author?: string;
  tags?: string[];
  cover?: File | Blob;
}
export type PostUpdate = Partial<PostCreate>;

export interface UserCreate {
  email: string;
  password: string;
  passwordConfirm: string;
  name?: string;
}
export type UserUpdate = Partial<Omit<UserCreate, "password" | "passwordConfirm">>;

export interface TagCreate {
  label: string;
}
export type TagUpdate = Partial<TagCreate>;

// ---- Where types ----------------------------------------------------------

export interface UserWhere {
  name?: StringOps | string;
  email?: StringOps | string;
  verified?: boolean;
  AND?: UserWhere[];
  OR?: UserWhere[];
}

export interface TagWhere {
  label?: StringOps | string;
  AND?: TagWhere[];
  OR?: TagWhere[];
}

export interface PostWhere {
  title?: StringOps | string;
  status?: EnumOps<PostStatus> | PostStatus;
  price?: NumberOps | number;
  author?: string | RelOps | UserWhere; // nested relation, 1 level
  tags?: string | RelOps; // multi relation: id-level only
  created?: StringOps | string;
  AND?: PostWhere[];
  OR?: PostWhere[];
}

// ---- Relations + expand keys ----------------------------------------------

export type PostRelations = { author: User; tags: Tag[] };
export type PostExpand = "author" | "tags";

// ---- Fluent accessor types ------------------------------------------------
// Each field is typed to its value domain so invalid operands error at the call
// site: `f.status.eq('archived')` is a compile error, `f.price.eq('lots')` too.
// At runtime the Proxy returns a plain FieldExpr for every field, which
// structurally satisfies TypedFieldExpr<V> — the cast in createClient is sound.

export interface PostFields {
  title: TypedFieldExpr<string>;
  status: TypedFieldExpr<PostStatus>;
  price: TypedFieldExpr<number>;
  author: TypedFieldExpr<string>;
  tags: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
}
export interface UserFields {
  name: TypedFieldExpr<string>;
  email: TypedFieldExpr<string>;
  verified: TypedFieldExpr<boolean>;
}
export interface TagFields {
  label: TypedFieldExpr<string>;
}

// ---- Concrete service interfaces ------------------------------------------

export interface PostsService {
  getOne<K extends PostExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal },
  ): Promise<WithExpand<Post, PostRelations, K>>;
  getList<K extends PostExpand = never>(opts?: {
    where?: PostWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
  }): Promise<ListResult<WithExpand<Post, PostRelations, K>>>;
  getFirstListItem<K extends PostExpand = never>(opts?: {
    where?: PostWhere;
    sort?: string;
    expand?: K[];
  }): Promise<WithExpand<Post, PostRelations, K>>;
  getPage(opts?: {
    where?: PostWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
  }): Promise<CursorPage<Post>>;
  iterate(opts?: { where?: PostWhere; sort?: string }): AsyncIterableIterator<Post>;
  getFullList(opts?: { where?: PostWhere; sort?: string }): Promise<Post[]>;
  create<K extends PostExpand = never>(
    data: PostCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Post, PostRelations, K>>;
  update<K extends PostExpand = never>(
    id: string,
    data: PostUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Post, PostRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: PostFields) => Expr): string;
}

export interface UsersService {
  getOne(id: string, opts?: { fields?: string }): Promise<User>;
  getList(opts?: {
    where?: UserWhere;
    sort?: string;
    page?: number;
    limit?: number;
  }): Promise<ListResult<User>>;
  getFirstListItem(opts?: { where?: UserWhere }): Promise<User>;
  getPage(opts?: {
    where?: UserWhere;
    limit?: number;
    cursor?: string;
  }): Promise<CursorPage<User>>;
  create(
    data: UserCreate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<User>;
  update(
    id: string,
    data: UserUpdate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<User>;
  delete(id: string): Promise<void>;
  filter(fn: (f: UserFields) => Expr): string;
  authWithPassword(
    identity: string,
    password: string,
  ): Promise<{ token: string; record: User }>;
}

export interface TagsService {
  getOne(id: string): Promise<Tag>;
  getList(opts?: { where?: TagWhere; sort?: string; page?: number; limit?: number }): Promise<ListResult<Tag>>;
  getPage(opts?: { where?: TagWhere; limit?: number; cursor?: string }): Promise<CursorPage<Tag>>;
  create(
    data: TagCreate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<Tag>;
  update(
    id: string,
    data: TagUpdate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<Tag>;
  delete(id: string): Promise<void>;
  filter(fn: (f: TagFields) => Expr): string;
}

// ---- Per-collection metadata ----------------------------------------------

export const usersMeta: CollectionMeta = {
  name: "users",
  fields: {
    name: { type: "text" },
    email: { type: "email" },
    verified: { type: "bool" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: [],
  expandable: [],
  isAuth: true,
};

export const postsMeta: CollectionMeta = {
  name: "posts",
  fields: {
    title: { type: "text" },
    status: { type: "select" },
    price: { type: "number" },
    author: { type: "relation" },
    tags: { type: "relation", multi: true },
    cover: { type: "file" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: ["cover"],
  expandable: ["author", "tags"],
  isAuth: false,
};

export const tagsMeta: CollectionMeta = {
  name: "tags",
  fields: { label: { type: "text" } },
  fileFields: [],
  expandable: [],
  isAuth: false,
};

// Nested-relation registry: posts.author -> users (one level deep).
const relationResolver: RelationResolver = (collection, field) => {
  if (collection === "posts" && field === "author") return usersMeta;
  return undefined;
};

// ---- Typed files surface (filename lookup baked in) -----------------------

/** File fields per collection (typed at the call site). */
export type PostFileField = "cover";

export interface TypedFiles {
  /** Build a file URL: `field` is typed to the record's file fields; the stored
   * filename is read off `record[field]`. */
  url(record: Post, field: PostFileField, opts?: FileUrlOptions): string;
}

// ---- Typed realtime surface -----------------------------------------------

// The realtime surface varies only by record type + where type, so the typed
// core's generic covers it directly — no bespoke per-collection interface.
export type PostsRealtime = RawTypedRealtime<Post, PostWhere>;

// ---- createClient ---------------------------------------------------------

export interface BlogClient {
  db: {
    posts: PostsService;
    users: UsersService;
    tags: TagsService;
  };
  realtime: {
    posts: PostsRealtime;
  };
  files: TypedFiles;
  authStore: Client["authStore"];
  send: Client["send"];
  fetch: Client["fetch"];
}

export interface BlogClientOptions {
  fetch?: typeof fetch;
  WebSocket?: typeof WebSocket;
  authCollection?: string;
}

export function createClient(url: string, opts: BlogClientOptions = {}): BlogClient {
  const base: RealtimeEnabledClient = withRealtime(
    baseCreateClient(url, {
      fetch: opts.fetch,
      WebSocket: opts.WebSocket,
      authCollection: opts.authCollection ?? "users",
    }),
  );

  const typedFiles = makeTypedFiles(base.files);

  const usersCollection = base.collection("users");

  return {
    db: {
      posts: makeRecordService(base, postsMeta, relationResolver) as unknown as PostsService,
      users: Object.assign(
        makeRecordService(base, usersMeta) as unknown as UsersService,
        {
          // Wire the auth method declared on UsersService to the SP1 collection.
          authWithPassword: (identity: string, password: string) =>
            usersCollection.authWithPassword(identity, password),
        },
      ) as unknown as UsersService,
      tags: makeRecordService(base, tagsMeta) as unknown as TagsService,
    },
    realtime: {
      posts: makeTypedRealtime<Post, PostWhere>(base.realtime, postsMeta, relationResolver),
    },
    files: {
      url(record, field, opts2) {
        // Generated wrapper: read the stored filename off the record's file field.
        const filename = (record as unknown as Record<string, string>)[field] ?? "";
        return typedFiles.fileUrl(
          { id: record.id, collectionName: "posts" },
          filename,
          opts2,
        );
      },
    },
    authStore: base.authStore,
    send: base.send.bind(base),
    fetch: base.fetch.bind(base),
  };
}
