// generated by zigbase — do not edit
// schema-hash: 9612c4ff43179782
//
// In a consumer repo this file imports from "@zigbase/client" and
// "@zigbase/client/typed". In this in-repo snapshot we import from the
// package source so it typechecks against the working tree without a built dist.
import { createClient as baseCreateClient, type Client } from "@zigbase/client";
import { withRealtime, type RealtimeEnabledClient } from "@zigbase/client/realtime";
import type { ListResult, CursorPage, FilesService, FileUrlOptions } from "@zigbase/client";
import {
  makeRecordService,
  makeTypedRealtime,
  type CollectionMeta,
  type WithExpand,
  type StringOps,
  type NumberOps,
  type EnumOps,
  type RelOps,
  type Expr,
  type FieldExpr,
  type TypedFieldExpr,
  type RelationResolver,
  type RawTypedRealtime,
} from "@zigbase/client/typed";

// ---- Records ----

export type ListingStatus = "draft" | "published" | "archived";
export type BookingStatus = "pending" | "confirmed" | "cancelled";
export interface User {
  id: string;
  email: string;
  username: string;
  verified: boolean;
  name: string;
  created: string;
  updated: string;
}

export interface Simulator {
  id: string;
  label: string;
  owner: string;
  created: string;
  updated: string;
}

export interface Listing {
  id: string;
  title: string;
  price_per_hour: number;
  status: ListingStatus;
  simulator: string;
  photos: string[];
  created: string;
  updated: string;
}

export interface Booking {
  id: string;
  listing: string;
  guest: string;
  starts_at: string;
  ends_at: string;
  price_total: number;
  status: BookingStatus;
  created: string;
  updated: string;
}

export interface Review {
  id: string;
  booking: string;
  author: string;
  rating: number;
  body: string;
  created: string;
  updated: string;
}


// ---- Create / Update payloads ----

export interface UserCreate {
  email: string;
  password: string;
  passwordConfirm: string;
  name?: string;
}
export type UserUpdate = Partial<Omit<UserCreate, "password" | "passwordConfirm">>;
export interface SimulatorCreate {
  label: string;
  owner: string;
}
export type SimulatorUpdate = Partial<SimulatorCreate>;
export interface ListingCreate {
  title: string;
  price_per_hour: number;
  status: ListingStatus;
  simulator: string;
  photos?: (File | Blob)[];
}
export type ListingUpdate = Partial<ListingCreate>;
export interface BookingCreate {
  listing: string;
  guest: string;
  starts_at: string;
  ends_at: string;
  price_total?: number;
  status?: BookingStatus;
}
export type BookingUpdate = Partial<BookingCreate>;
export interface ReviewCreate {
  booking: string;
  author: string;
  rating?: number;
  body?: string;
}
export type ReviewUpdate = Partial<ReviewCreate>;

// ---- Where types ----

export interface UserWhere {
  email?: StringOps | string;
  username?: StringOps | string;
  verified?: boolean;
  name?: StringOps | string;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: UserWhere[];
  OR?: UserWhere[];
}
export interface SimulatorWhere {
  label?: StringOps | string;
  owner?: string | RelOps | UserWhere;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: SimulatorWhere[];
  OR?: SimulatorWhere[];
}
export interface ListingWhere {
  title?: StringOps | string;
  price_per_hour?: NumberOps | number;
  status?: EnumOps<ListingStatus> | ListingStatus;
  simulator?: string | RelOps | SimulatorWhere;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: ListingWhere[];
  OR?: ListingWhere[];
}
export interface BookingWhere {
  listing?: string | RelOps | ListingWhere;
  guest?: string | RelOps | UserWhere;
  starts_at?: StringOps | string;
  ends_at?: StringOps | string;
  price_total?: NumberOps | number;
  status?: EnumOps<BookingStatus> | BookingStatus;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: BookingWhere[];
  OR?: BookingWhere[];
}
export interface ReviewWhere {
  booking?: string | RelOps | BookingWhere;
  author?: string | RelOps | UserWhere;
  rating?: NumberOps | number;
  body?: StringOps | string;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: ReviewWhere[];
  OR?: ReviewWhere[];
}

// ---- Relations + expand keys ----

export type SimulatorRelations = { owner: User };
export type SimulatorExpand = "owner";
export type ListingRelations = { simulator: Simulator };
export type ListingExpand = "simulator";
export type BookingRelations = { listing: Listing; guest: User };
export type BookingExpand = "listing" | "guest";
export type ReviewRelations = { booking: Booking; author: User };
export type ReviewExpand = "booking" | "author";

// ---- Fluent accessor types ----

export interface UserFields {
  email: TypedFieldExpr<string>;
  username: TypedFieldExpr<string>;
  verified: TypedFieldExpr<boolean>;
  name: TypedFieldExpr<string>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface SimulatorFields {
  label: TypedFieldExpr<string>;
  owner: TypedFieldExpr<string>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface ListingFields {
  title: TypedFieldExpr<string>;
  price_per_hour: TypedFieldExpr<number>;
  status: TypedFieldExpr<ListingStatus>;
  simulator: TypedFieldExpr<string>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface BookingFields {
  listing: TypedFieldExpr<string>;
  guest: TypedFieldExpr<string>;
  starts_at: TypedFieldExpr<string>;
  ends_at: TypedFieldExpr<string>;
  price_total: TypedFieldExpr<number>;
  status: TypedFieldExpr<BookingStatus>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface ReviewFields {
  booking: TypedFieldExpr<string>;
  author: TypedFieldExpr<string>;
  rating: TypedFieldExpr<number>;
  body: TypedFieldExpr<string>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}

// ---- Concrete service interfaces ----

export interface UsersService {
  getOne(id: string, opts?: { fields?: string; signal?: AbortSignal }): Promise<User>;
  getList(opts?: {
    where?: UserWhere;
    sort?: string;
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
  }): Promise<ListResult<User>>;
  getFirstListItem(opts?: { where?: UserWhere; sort?: string }): Promise<User>;
  getPage(opts?: {
    where?: UserWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
  }): Promise<CursorPage<User>>;
  iterate(opts?: { where?: UserWhere; sort?: string }): AsyncIterableIterator<User>;
  getFullList(opts?: { where?: UserWhere; sort?: string }): Promise<User[]>;
  create(
    data: UserCreate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<User>;
  update(
    id: string,
    data: UserUpdate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<User>;
  delete(id: string): Promise<void>;
  filter(fn: (f: UserFields) => Expr): string;
  authWithPassword(
    identity: string,
    password: string,
  ): Promise<{ token: string; record: User }>;
}
export interface SimulatorsService {
  getOne<K extends SimulatorExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal },
  ): Promise<WithExpand<Simulator, SimulatorRelations, K>>;
  getList<K extends SimulatorExpand = never>(opts?: {
    where?: SimulatorWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
  }): Promise<ListResult<WithExpand<Simulator, SimulatorRelations, K>>>;
  getFirstListItem<K extends SimulatorExpand = never>(opts?: {
    where?: SimulatorWhere;
    sort?: string;
    expand?: K[];
  }): Promise<WithExpand<Simulator, SimulatorRelations, K>>;
  getPage(opts?: {
    where?: SimulatorWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
  }): Promise<CursorPage<Simulator>>;
  iterate(opts?: { where?: SimulatorWhere; sort?: string }): AsyncIterableIterator<Simulator>;
  getFullList(opts?: { where?: SimulatorWhere; sort?: string }): Promise<Simulator[]>;
  create<K extends SimulatorExpand = never>(
    data: SimulatorCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Simulator, SimulatorRelations, K>>;
  update<K extends SimulatorExpand = never>(
    id: string,
    data: SimulatorUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Simulator, SimulatorRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: SimulatorFields) => Expr): string;
}
export interface ListingsService {
  getOne<K extends ListingExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal },
  ): Promise<WithExpand<Listing, ListingRelations, K>>;
  getList<K extends ListingExpand = never>(opts?: {
    where?: ListingWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
  }): Promise<ListResult<WithExpand<Listing, ListingRelations, K>>>;
  getFirstListItem<K extends ListingExpand = never>(opts?: {
    where?: ListingWhere;
    sort?: string;
    expand?: K[];
  }): Promise<WithExpand<Listing, ListingRelations, K>>;
  getPage(opts?: {
    where?: ListingWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
  }): Promise<CursorPage<Listing>>;
  iterate(opts?: { where?: ListingWhere; sort?: string }): AsyncIterableIterator<Listing>;
  getFullList(opts?: { where?: ListingWhere; sort?: string }): Promise<Listing[]>;
  create<K extends ListingExpand = never>(
    data: ListingCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Listing, ListingRelations, K>>;
  update<K extends ListingExpand = never>(
    id: string,
    data: ListingUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Listing, ListingRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: ListingFields) => Expr): string;
}
export interface BookingsService {
  getOne<K extends BookingExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal },
  ): Promise<WithExpand<Booking, BookingRelations, K>>;
  getList<K extends BookingExpand = never>(opts?: {
    where?: BookingWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
  }): Promise<ListResult<WithExpand<Booking, BookingRelations, K>>>;
  getFirstListItem<K extends BookingExpand = never>(opts?: {
    where?: BookingWhere;
    sort?: string;
    expand?: K[];
  }): Promise<WithExpand<Booking, BookingRelations, K>>;
  getPage(opts?: {
    where?: BookingWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
  }): Promise<CursorPage<Booking>>;
  iterate(opts?: { where?: BookingWhere; sort?: string }): AsyncIterableIterator<Booking>;
  getFullList(opts?: { where?: BookingWhere; sort?: string }): Promise<Booking[]>;
  create<K extends BookingExpand = never>(
    data: BookingCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Booking, BookingRelations, K>>;
  update<K extends BookingExpand = never>(
    id: string,
    data: BookingUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Booking, BookingRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: BookingFields) => Expr): string;
}
export interface ReviewsService {
  getOne<K extends ReviewExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal },
  ): Promise<WithExpand<Review, ReviewRelations, K>>;
  getList<K extends ReviewExpand = never>(opts?: {
    where?: ReviewWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
  }): Promise<ListResult<WithExpand<Review, ReviewRelations, K>>>;
  getFirstListItem<K extends ReviewExpand = never>(opts?: {
    where?: ReviewWhere;
    sort?: string;
    expand?: K[];
  }): Promise<WithExpand<Review, ReviewRelations, K>>;
  getPage(opts?: {
    where?: ReviewWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
  }): Promise<CursorPage<Review>>;
  iterate(opts?: { where?: ReviewWhere; sort?: string }): AsyncIterableIterator<Review>;
  getFullList(opts?: { where?: ReviewWhere; sort?: string }): Promise<Review[]>;
  create<K extends ReviewExpand = never>(
    data: ReviewCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Review, ReviewRelations, K>>;
  update<K extends ReviewExpand = never>(
    id: string,
    data: ReviewUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Review, ReviewRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: ReviewFields) => Expr): string;
}

// ---- Per-collection metadata ----

export const usersMeta: CollectionMeta = {
  name: "users",
  fields: {
    id: { type: "text" },
    email: { type: "email" },
    username: { type: "text" },
    verified: { type: "bool" },
    name: { type: "text" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: [],
  expandable: [],
  isAuth: true,
};
export const simulatorsMeta: CollectionMeta = {
  name: "simulators",
  fields: {
    id: { type: "text" },
    label: { type: "text" },
    owner: { type: "relation" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: [],
  expandable: ["owner"],
  isAuth: false,
};
export const listingsMeta: CollectionMeta = {
  name: "listings",
  fields: {
    id: { type: "text" },
    title: { type: "text" },
    price_per_hour: { type: "number" },
    status: { type: "select" },
    simulator: { type: "relation" },
    photos: { type: "file", multi: true },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: ["photos"],
  expandable: ["simulator"],
  isAuth: false,
};
export const bookingsMeta: CollectionMeta = {
  name: "bookings",
  fields: {
    id: { type: "text" },
    listing: { type: "relation" },
    guest: { type: "relation" },
    starts_at: { type: "date" },
    ends_at: { type: "date" },
    price_total: { type: "number" },
    status: { type: "select" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: [],
  expandable: ["listing", "guest"],
  isAuth: false,
};
export const reviewsMeta: CollectionMeta = {
  name: "reviews",
  fields: {
    id: { type: "text" },
    booking: { type: "relation" },
    author: { type: "relation" },
    rating: { type: "number", mode: "int" },
    body: { type: "text" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: [],
  expandable: ["booking", "author"],
  isAuth: false,
};
const relationResolver: RelationResolver = (collection, field) => {
  if (collection === "simulators" && field === "owner") return usersMeta;
  if (collection === "listings" && field === "simulator") return simulatorsMeta;
  if (collection === "bookings" && field === "listing") return listingsMeta;
  if (collection === "bookings" && field === "guest") return usersMeta;
  if (collection === "reviews" && field === "booking") return bookingsMeta;
  if (collection === "reviews" && field === "author") return usersMeta;
  return undefined;
};

// ---- Typed files surface ----


// ---- Typed realtime surface ----

export type UsersRealtime = RawTypedRealtime<User, UserWhere>;
export type SimulatorsRealtime = RawTypedRealtime<Simulator, SimulatorWhere>;
export type ListingsRealtime = RawTypedRealtime<Listing, ListingWhere>;
export type BookingsRealtime = RawTypedRealtime<Booking, BookingWhere>;
export type ReviewsRealtime = RawTypedRealtime<Review, ReviewWhere>;

// ---- createClient ----

export interface ZbClient {
  db: {
    users: UsersService;
    simulators: SimulatorsService;
    listings: ListingsService;
    bookings: BookingsService;
    reviews: ReviewsService;
  };
  realtime: {
    users: UsersRealtime;
    simulators: SimulatorsRealtime;
    listings: ListingsRealtime;
    bookings: BookingsRealtime;
    reviews: ReviewsRealtime;
  };
  files: FilesService;
  authStore: Client["authStore"];
  send: Client["send"];
  fetch: Client["fetch"];
}
export interface ZbClientOptions {
  fetch?: typeof fetch;
  WebSocket?: typeof WebSocket;
  authCollection?: string;
}
export function createClient(url: string, opts: ZbClientOptions = {}): ZbClient {
  const base: RealtimeEnabledClient = withRealtime(
    baseCreateClient(url, {
      fetch: opts.fetch,
      WebSocket: opts.WebSocket,
      authCollection: opts.authCollection ?? "users",
    }),
  );

  return {
    db: {
      users: Object.assign(
        makeRecordService(base, usersMeta) as unknown as UsersService,
        {
          authWithPassword: (identity: string, password: string) =>
            base.collection("users").authWithPassword(identity, password),
        },
      ) as unknown as UsersService,
      simulators: makeRecordService(base, simulatorsMeta, relationResolver) as unknown as SimulatorsService,
      listings: makeRecordService(base, listingsMeta, relationResolver) as unknown as ListingsService,
      bookings: makeRecordService(base, bookingsMeta, relationResolver) as unknown as BookingsService,
      reviews: makeRecordService(base, reviewsMeta, relationResolver) as unknown as ReviewsService,
    },
    realtime: {
      users: makeTypedRealtime<User, UserWhere>(base.realtime, usersMeta),
      simulators: makeTypedRealtime<Simulator, SimulatorWhere>(base.realtime, simulatorsMeta, relationResolver),
      listings: makeTypedRealtime<Listing, ListingWhere>(base.realtime, listingsMeta, relationResolver),
      bookings: makeTypedRealtime<Booking, BookingWhere>(base.realtime, bookingsMeta, relationResolver),
      reviews: makeTypedRealtime<Review, ReviewWhere>(base.realtime, reviewsMeta, relationResolver),
    },
    files: base.files,
    authStore: base.authStore,
    send: base.send.bind(base),
    fetch: base.fetch.bind(base),
  };
}
