//! Pure-Zig TypeScript client generator executable.
//! Reads @import("app").App.collections and emits a zbase.gen.ts.
//! Pure functions (generate, schemaHash) use relative imports so they can be
//! reached by the library test suite without a circular zigbase reference.
//! main() is the only function that touches @import("zigbase")/@import("app") and IO.
const std = @import("std");
const schema = @import("../schema.zig");
const emit = @import("emit.zig");
const guards = @import("guards.zig");
const ident = @import("identifiers.zig");

const W = std.ArrayList(u8);

/// FNV-1a over a canonical serialization of the collections (declared order).
pub fn schemaHash(cols: []const schema.Collection) u64 {
    var h = std.hash.Fnv1a_64.init();
    for (cols) |c| {
        h.update(c.name);
        h.update("|");
        h.update(@tagName(c.type));
        for (c.fields) |f| {
            h.update("\x00");
            h.update(f.name);
            h.update(":");
            h.update(@tagName(std.meta.activeTag(f.options)));
            if (f.required) h.update("!");
            if (f.isMultiValue()) h.update("*");
            switch (f.options) {
                .select => |o| for (o.values) |v| {
                    h.update(",");
                    h.update(v);
                },
                .relation => |o| {
                    h.update("->");
                    h.update(o.targetCollectionId);
                },
                else => {},
            }
        }
    }
    return h.final();
}

fn section(alloc: std.mem.Allocator, w: *W, title: []const u8) !void {
    const line = try std.fmt.allocPrint(alloc, "\n// ---- {s} " ++ ("-" ** 4) ++ "\n\n", .{title});
    try w.appendSlice(alloc, line);
}

/// The pure generator core: collections -> full file text. Runs guards first.
pub fn generate(
    alloc: std.mem.Allocator,
    cols: []const schema.Collection,
    in_repo: bool,
    auth_collection: []const u8,
    client_name: []const u8,
) ![]const u8 {
    var report = guards.GuardReport{ .message = "" };
    try guards.checkOperatorNames(alloc, cols, &report);
    try guards.checkIdentifiers(alloc, cols, &report);

    var w: W = .empty;
    // header
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        "// generated by zigbase — do not edit\n// schema-hash: {x:0>16}\n//\n", .{schemaHash(cols)}));
    try w.appendSlice(alloc,
        \\// In a consumer repo this file imports from "@zigbase/client" and
        \\// "@zigbase/client/typed". In this in-repo snapshot we import from the
        \\// package source so it typechecks against the working tree without a built dist.
        \\
    );
    try emit.emitImports(alloc, &w, in_repo);

    try section(alloc, &w, "Records");
    for (cols) |c| try emit.emitSelectUnions(alloc, &w, c);
    for (cols) |c| {
        try emit.emitRecord(alloc, &w, c);
        try w.appendSlice(alloc, "\n");
    }
    try section(alloc, &w, "Create / Update payloads");
    for (cols) |c| {
        try emit.emitCreate(alloc, &w, c);
        try emit.emitUpdate(alloc, &w, c);
    }
    try section(alloc, &w, "Where types");
    for (cols) |c| try emit.emitWhere(alloc, &w, cols, c);
    try section(alloc, &w, "Relations + expand keys");
    for (cols) |c| {
        try emit.emitRelations(alloc, &w, cols, c);
        try emit.emitExpandKeys(alloc, &w, c);
    }
    try section(alloc, &w, "Fluent accessor types");
    for (cols) |c| try emit.emitFields(alloc, &w, c);
    try section(alloc, &w, "Concrete service interfaces");
    for (cols) |c| try emit.emitService(alloc, &w, c);
    try section(alloc, &w, "Per-collection metadata");
    for (cols) |c| try emit.emitMeta(alloc, &w, c);
    try emit.emitRelationResolver(alloc, &w, cols);
    try section(alloc, &w, "Typed files surface");
    try emit.emitTypedFiles(alloc, &w, cols);
    try section(alloc, &w, "Typed realtime surface");
    for (cols) |c| try emit.emitRealtimeAlias(alloc, &w, c);
    try section(alloc, &w, "createClient");
    try emitClientFactory(alloc, &w, cols, client_name, auth_collection);

    return w.toOwnedSlice(alloc);
}

/// The createClient + client-interface block (mirrors blog.gen.ts createClient).
fn emitClientFactory(alloc: std.mem.Allocator, w: *W, cols: []const schema.Collection, client_name: []const u8, auth_collection: []const u8) !void {
    // BlogClient-style interface
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "export interface {s} {{\n  db: {{\n", .{client_name}));
    for (cols) |c| try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: {s};\n", .{ c.name, try ident.serviceName(alloc, c.name) }));
    try w.appendSlice(alloc, "  };\n  realtime: {\n");
    for (cols) |c| try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: {s};\n", .{ c.name, try ident.realtimeAliasName(alloc, c.name) }));
    try w.appendSlice(alloc,
        \\  };
        \\  files: FilesService;
        \\  authStore: Client["authStore"];
        \\  send: Client["send"];
        \\  fetch: Client["fetch"];
        \\}
        \\
    );
    // options interface
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        \\export interface {s}Options {{
        \\  fetch?: typeof fetch;
        \\  WebSocket?: typeof WebSocket;
        \\  authCollection?: string;
        \\}}
        \\
    , .{client_name}));
    // createClient
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        \\export function createClient(url: string, opts: {0s}Options = {{}}): {0s} {{
        \\  const base: RealtimeEnabledClient = withRealtime(
        \\    baseCreateClient(url, {{
        \\      fetch: opts.fetch,
        \\      WebSocket: opts.WebSocket,
        \\      authCollection: opts.authCollection ?? "{1s}",
        \\    }}),
        \\  );
        \\
        \\  return {{
        \\    db: {{
        \\
    , .{ client_name, auth_collection }));
    for (cols) |c| {
        const mc = try ident.metaConst(alloc, c.name);
        const svc = try ident.serviceName(alloc, c.name);
        const resolver = if (emit_hasRelations(c)) ", relationResolver" else "";
        const file_fields = emit_hasFileFields(c);
        if (c.type == .auth and file_fields) {
            // Auth collection WITH file fields: Object.assign with both authWithPassword + fileUrl.
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                \\      {0s}: Object.assign(
                \\        makeRecordService(base, {1s}{2s}) as unknown as {3s},
                \\        {{
                \\          authWithPassword: (identity: string, password: string) =>
                \\            base.collection("{0s}").authWithPassword(identity, password),
                \\          fileUrl: (record: any, field: any, opts: any) =>
                \\            base.files.getUrl({{ id: record.id, collectionName: "{0s}" }}, (record as Record<string, string>)[field] ?? "", opts),
                \\        }},
                \\      ) as unknown as {3s},
                \\
            , .{ c.name, mc, resolver, svc }));
        } else if (c.type == .auth) {
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                \\      {0s}: Object.assign(
                \\        makeRecordService(base, {1s}{2s}) as unknown as {3s},
                \\        {{
                \\          authWithPassword: (identity: string, password: string) =>
                \\            base.collection("{0s}").authWithPassword(identity, password),
                \\        }},
                \\      ) as unknown as {3s},
                \\
            , .{ c.name, mc, resolver, svc }));
        } else if (file_fields) {
            // Non-auth collection WITH file fields: Object.assign to graft fileUrl.
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                \\      {0s}: Object.assign(
                \\        makeRecordService(base, {1s}{2s}) as unknown as {3s},
                \\        {{
                \\          fileUrl: (record: any, field: any, opts: any) =>
                \\            base.files.getUrl({{ id: record.id, collectionName: "{0s}" }}, (record as Record<string, string>)[field] ?? "", opts),
                \\        }},
                \\      ) as unknown as {3s},
                \\
            , .{ c.name, mc, resolver, svc }));
        } else {
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                "      {0s}: makeRecordService(base, {1s}{2s}) as unknown as {3s},\n",
                .{ c.name, mc, resolver, svc }));
        }
    }
    try w.appendSlice(alloc, "    },\n    realtime: {\n");
    for (cols) |c| {
        const rec = try ident.recordName(alloc, c.name);
        const wn = try ident.whereName(alloc, c.name);
        const mc = try ident.metaConst(alloc, c.name);
        const resolver = if (emit_hasRelations(c)) ", relationResolver" else "";
        try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
            "      {0s}: makeTypedRealtime<{1s}, {2s}>(base.realtime, {3s}{4s}),\n",
            .{ c.name, rec, wn, mc, resolver }));
    }
    try w.appendSlice(alloc, "    },\n    files: base.files,\n");
    try w.appendSlice(alloc,
        \\    authStore: base.authStore,
        \\    send: base.send.bind(base),
        \\    fetch: base.fetch.bind(base),
        \\  };
        \\}
        \\
    );
}

fn emit_hasRelations(c: schema.Collection) bool {
    for (c.fields) |f| if (f.options == .relation) return true;
    return false;
}

fn emit_hasFileFields(c: schema.Collection) bool {
    const tt = @import("ts_type.zig");
    for (c.fields) |f| if (tt.kindOf(f) == .file_name) return true;
    return false;
}

const Args = struct {
    out: ?[]const u8 = null,
    api_prefix: []const u8 = "/api",
    check: bool = false,
};

/// Parse CLI args from the Zig 0.16 argv slice ([]const [:0]const u8).
fn parseArgsSlice(alloc: std.mem.Allocator, argv: []const [:0]const u8) !Args {
    var args = Args{};
    var i: usize = 1; // skip exe name
    while (i < argv.len) : (i += 1) {
        const a = argv[i];
        if (std.mem.eql(u8, a, "--out")) {
            i += 1;
            if (i >= argv.len) return error.MissingOutValue;
            args.out = try alloc.dupe(u8, argv[i]);
        } else if (std.mem.eql(u8, a, "--api-prefix")) {
            i += 1;
            if (i >= argv.len) return error.MissingApiPrefixValue;
            args.api_prefix = try alloc.dupe(u8, argv[i]);
        } else if (std.mem.eql(u8, a, "--check")) {
            args.check = true;
        } else {
            std.log.warn("gen_client: ignoring unknown arg '{s}'", .{a});
        }
    }
    return args;
}

/// Pick the auth collection name (first auth collection).
fn authCollectionName(cols: []const schema.Collection) []const u8 {
    for (cols) |c| if (c.type == .auth) return c.name;
    return "";
}

/// Entry point: Zig 0.16 `pub fn main(init: std.process.Init) !void`.
/// Threads `init.io` (for file operations) and uses `init.gpa` for a local arena,
/// reads argv from `init.minimal.args.toSlice(arena)` (yields `[]const [:0]const u8`).
/// Uses `std.c.getenv` for the ZBASE_INREPO env flag — requires link_libc = true
/// in the exe module (see Task 7 build wiring).
///
/// NOTE (Task 7): In Zig 0.16, a file can only belong to one module. gen_client.zig
/// uses relative imports (@import("../schema.zig") etc.) which claim those files for
/// THIS module. If gen_client.zig is used as the exe module root AND zigbase is in
/// the dependency graph (via the `app` module), those files would be double-claimed.
/// The solution: use gen_main.zig as the exe root (which imports "zigbase" and "app"
/// as named modules) and call mainWithCollections() here. This keeps gen_client.zig
/// as a self-contained library file usable by the zigbase test suite WITHOUT being
/// a module root.
pub fn mainWithCollections(init: std.process.Init, cols: []const schema.Collection) !void {
    const io = init.io;
    // Use an arena for all temporary allocations during the generator run.
    var arena_state = std.heap.ArenaAllocator.init(init.gpa);
    defer arena_state.deinit();
    const a = arena_state.allocator();

    // argv: []const [:0]const u8 (Zig 0.16 — init.minimal.args.toSlice returns this).
    const argv = try init.minimal.args.toSlice(a);
    const args = try parseArgsSlice(a, argv);
    const out_path = args.out orelse {
        std.log.err("gen_client: --out <path> is required", .{});
        return error.MissingOut;
    };

    // ZBASE_INREPO: use std.c.getenv (libc-backed; exe must link_libc = true in Task 7).
    // Non-null return value means the var is set (value may be empty string — that's fine).
    const in_repo = std.c.getenv("ZBASE_INREPO") != null;
    const client_name = "ZbClient";

    const text = generate(a, cols, in_repo, authCollectionName(cols), client_name) catch |e| {
        // guard messages are printed via the report; re-run path for the message:
        var report = guards.GuardReport{ .message = "" };
        guards.checkOperatorNames(a, cols, &report) catch {};
        guards.checkIdentifiers(a, cols, &report) catch {};
        if (report.message.len > 0) std.log.err("{s}", .{report.message});
        return e;
    };

    if (args.check) {
        // Zig 0.16 file-read: std.Io.Dir.cwd().readFileAlloc(io, path, alloc, .limited(N))
        const existing = std.Io.Dir.cwd().readFileAlloc(io, out_path, a, .limited(64 * 1024 * 1024)) catch |e| {
            std.log.err("gen_client --check: cannot read '{s}': {s}", .{ out_path, @errorName(e) });
            return error.CheckReadFailed;
        };
        if (!std.mem.eql(u8, existing, text)) {
            std.log.err("gen_client --check: '{s}' is STALE — re-run gen-client to regenerate.", .{out_path});
            return error.Stale;
        }
        return;
    }

    // Ensure the output directory exists.
    // Zig 0.16: std.Io.Dir.cwd().createDirPath(io, dir) — NOT makePath.
    if (std.fs.path.dirname(out_path)) |dir| {
        std.Io.Dir.cwd().createDirPath(io, dir) catch {};
    }
    // Zig 0.16 file-write: std.Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = bytes })
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = text });
    std.log.info("gen_client: wrote {s} ({d} bytes)", .{ out_path, text.len });
}

/// Legacy entry point kept for back-compat; reads @import("app").App.collections.
/// Prefer mainWithCollections when building as a separate module to avoid
/// the Zig 0.16 "file exists in multiple modules" error (see note above).
pub fn main(init: std.process.Init) !void {
    const app = @import("app");
    return mainWithCollections(init, app.App.collections);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

fn miniBlog(alloc: std.mem.Allocator) ![]const schema.Collection {
    const tags_f = try alloc.dupe(schema.Field, &.{.{ .id = "a", .name = "label", .required = true, .options = .{ .text = .{} } }});
    const users_f = try alloc.dupe(schema.Field, &.{.{ .id = "b", .name = "name", .options = .{ .text = .{} } }});
    const posts_f = try alloc.dupe(schema.Field, &.{
        .{ .id = "c", .name = "title", .required = true, .options = .{ .text = .{} } },
        .{ .id = "d", .name = "status", .options = .{ .select = .{ .values = &.{ "draft", "published" }, .maxSelect = 1 } } },
        .{ .id = "e", .name = "author", .options = .{ .relation = .{ .targetCollectionId = "users", .maxSelect = 1 } } },
        .{ .id = "f", .name = "tags", .options = .{ .relation = .{ .targetCollectionId = "tags", .maxSelect = 99 } } },
        .{ .id = "g", .name = "cover", .options = .{ .file = .{ .maxSelect = 1 } } },
    });
    return try alloc.dupe(schema.Collection, &.{
        .{ .id = "", .name = "posts", .fields = posts_f },
        .{ .id = "", .name = "users", .type = .auth, .fields = users_f },
        .{ .id = "", .name = "tags", .fields = tags_f },
    });
}

test "generate emits a parseable file with the expected top-level constructs" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const out = try generate(a, cols, true, "users", "BlogClient");
    try std.testing.expect(std.mem.startsWith(u8, out, "// generated by zigbase — do not edit\n// schema-hash: "));
    inline for (.{
        "export interface Post {",        "export type PostStatus =",
        "export interface PostCreate {",  "export type PostUpdate =",
        "export interface PostWhere {",   "export type PostRelations =",
        "export type PostExpand =",       "export interface PostFields {",
        "export interface PostsService {","export const postsMeta: CollectionMeta = {",
        "const relationResolver: RelationResolver =",
        "export type PostsRealtime = RawTypedRealtime<Post, PostWhere>;",
        "export interface BlogClient {",  "export function createClient(",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, out, needle) != null);
}

test "schemaHash is deterministic + order-sensitive" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    try std.testing.expectEqual(schemaHash(cols), schemaHash(cols));
    // mutating a field name changes the hash
    var cols2 = try a.dupe(schema.Collection, cols);
    var f2 = try a.dupe(schema.Field, cols2[0].fields);
    f2[0].name = "headline";
    cols2[0].fields = f2;
    try std.testing.expect(schemaHash(cols) != schemaHash(cols2));
}

test "--check diff: stale buffer differs from fresh output" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const fresh = try generate(a, cols, true, "users", "BlogClient");
    const stale = try std.fmt.allocPrint(a, "{s}\n// drift\n", .{fresh});
    try std.testing.expect(!std.mem.eql(u8, fresh, stale)); // --check would exit non-zero
    try std.testing.expect(std.mem.eql(u8, fresh, fresh));   // --check would exit zero
}

test "guards run inside generate: operator-named relation target errors" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const tag_f = try a.dupe(schema.Field, &.{.{ .id = "x", .name = "in", .options = .{ .text = .{} } }});
    const post_f = try a.dupe(schema.Field, &.{.{ .id = "y", .name = "labels", .options = .{ .relation = .{ .targetCollectionId = "tags" } } }});
    const cols = try a.dupe(schema.Collection, &.{
        .{ .id = "", .name = "tags", .fields = tag_f },
        .{ .id = "", .name = "posts", .fields = post_f },
    });
    try std.testing.expectError(guards.GuardError.OperatorNameClash, generate(a, cols, true, "", "ZbClient"));
}
