//! Pure-Zig TypeScript client generator executable.
//! Reads @import("app").App.collections and emits a zbase.gen.ts.
//! Pure functions (generate, schemaHash) use relative imports so they can be
//! reached by the library test suite without a circular zigbase reference.
//! main() is the only function that touches @import("zigbase")/@import("app") and IO.
const std = @import("std");
const schema = @import("../schema.zig");
const events = @import("../events.zig");
const emit = @import("emit.zig");
const guards = @import("guards.zig");
const ident = @import("identifiers.zig");

const W = std.ArrayList(u8);

/// FNV-1a over a canonical serialization of the collections (declared order).
pub fn schemaHash(cols: []const schema.Collection) u64 {
    var h = std.hash.Fnv1a_64.init();
    for (cols) |c| {
        h.update(c.name);
        h.update("|");
        h.update(@tagName(c.type));
        for (c.fields) |f| {
            h.update("\x00");
            h.update(f.name);
            h.update(":");
            h.update(@tagName(std.meta.activeTag(f.options)));
            if (f.required) h.update("!");
            if (f.isMultiValue()) h.update("*");
            switch (f.options) {
                .select => |o| for (o.values) |v| {
                    h.update(",");
                    h.update(v);
                },
                .relation => |o| {
                    h.update("->");
                    h.update(o.targetCollectionId);
                },
                else => {},
            }
        }
    }
    return h.final();
}

fn section(alloc: std.mem.Allocator, w: *W, title: []const u8) !void {
    const line = try std.fmt.allocPrint(alloc, "\n// ---- {s} " ++ ("-" ** 4) ++ "\n\n", .{title});
    try w.appendSlice(alloc, line);
}

/// The pure generator core: collections -> full file text. Runs guards first.
pub fn generate(
    alloc: std.mem.Allocator,
    cols: []const schema.Collection,
    comptime routes: []const events.RouteMeta,
    in_repo: bool,
    auth_collection: []const u8,
    client_name: []const u8,
    api_prefix: []const u8,
) ![]const u8 {
    // Validate that every route path starts with the given api_prefix.
    // Must use `inline for` because RouteMeta contains `Input: type` (comptime-only field).
    inline for (routes) |r| {
        if (!std.mem.startsWith(u8, r.path, api_prefix)) {
            std.log.err("gen_client: route '{s}' does not start with --api-prefix '{s}'; the framework route prefix and the generator prefix disagree.", .{ r.path, api_prefix });
            return error.RoutePrefixMismatch;
        }
    }

    var report = guards.GuardReport{ .message = "" };
    try guards.checkOperatorNames(alloc, cols, &report);
    try guards.checkIdentifiers(alloc, cols, &report);

    var w: W = .empty;
    // header
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        "// generated by zigbase — do not edit\n// schema-hash: {x:0>16}\n//\n", .{schemaHash(cols)}));
    if (in_repo) {
        try w.appendSlice(alloc,
            \\// In a consumer repo this file imports from "@zigbase/client" and
            \\// "@zigbase/client/typed". In this in-repo snapshot we import from the
            \\// package source so it typechecks against the working tree without a built dist.
            \\
        );
    } else {
        try w.appendSlice(alloc,
            \\// This client imports its runtime and types from the "@zigbase/client"
            \\// and "@zigbase/client/typed" packages.
            \\
        );
    }
    try emit.emitImports(alloc, &w, in_repo, routes.len > 0);

    try section(alloc, &w, "Records");
    for (cols) |c| try emit.emitSelectUnions(alloc, &w, c);
    for (cols) |c| {
        try emit.emitRecord(alloc, &w, c);
        try w.appendSlice(alloc, "\n");
    }
    try section(alloc, &w, "Create / Update payloads");
    for (cols) |c| {
        try emit.emitCreate(alloc, &w, c);
        try emit.emitUpdate(alloc, &w, c);
    }
    try section(alloc, &w, "Where types");
    for (cols) |c| try emit.emitWhere(alloc, &w, cols, c);
    try section(alloc, &w, "Relations + expand keys");
    for (cols) |c| {
        try emit.emitRelations(alloc, &w, cols, c);
        try emit.emitExpandKeys(alloc, &w, c);
    }
    try section(alloc, &w, "Fluent accessor types");
    for (cols) |c| try emit.emitFields(alloc, &w, c);
    try section(alloc, &w, "Concrete service interfaces");
    for (cols) |c| try emit.emitService(alloc, &w, c);
    try section(alloc, &w, "Per-collection metadata");
    for (cols) |c| try emit.emitMeta(alloc, &w, c);
    try emit.emitRelationResolver(alloc, &w, cols);
    try section(alloc, &w, "Typed files surface");
    try emit.emitTypedFiles(alloc, &w, cols);
    try section(alloc, &w, "Typed realtime surface");
    for (cols) |c| try emit.emitRealtimeAlias(alloc, &w, c);
    try section(alloc, &w, "createClient");
    const rpc_section = try @import("rpc.zig").render(routes, alloc);
    // rpc_section slices are owned by the arena (alloc), freed on arena deinit.
    try emitClientFactory(alloc, &w, cols, client_name, auth_collection, rpc_section, routes.len, api_prefix);

    return w.toOwnedSlice(alloc);
}

/// The createClient + client-interface block (mirrors blog.gen.ts createClient).
fn emitClientFactory(
    alloc: std.mem.Allocator,
    w: *W,
    cols: []const schema.Collection,
    client_name: []const u8,
    auth_collection: []const u8,
    rpc_section: @import("rpc.zig").Section,
    routes_len: usize,
    api_prefix: []const u8,
) !void {
    // Pre-build the auth iface + factory sections (empty if no non-password methods).
    var auth_iface: W = .empty;
    var auth_factory: W = .empty;
    try emitAuthMethodEndpoints(alloc, &auth_iface, &auth_factory, cols, api_prefix);
    const auth_iface_s = try auth_iface.toOwnedSlice(alloc);
    const auth_factory_s = try auth_factory.toOwnedSlice(alloc);
    const has_auth_methods = auth_iface_s.len > 0;

    // Emit named RPC Input/Output decls before the client interface (only when routes exist).
    if (routes_len > 0) {
        try w.appendSlice(alloc, rpc_section.decls);
    }
    // BlogClient-style interface
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "export interface {s} {{\n  db: {{\n", .{client_name}));
    for (cols) |c| try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: {s};\n", .{ c.name, try ident.serviceName(alloc, c.name) }));
    try w.appendSlice(alloc, "  };\n  realtime: {\n");
    for (cols) |c| try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: {s};\n", .{ c.name, try ident.realtimeAliasName(alloc, c.name) }));
    // auth method stubs (non-password methods only; password stays on db.<col>.authWithPassword)
    try w.appendSlice(alloc, "  };\n");
    if (has_auth_methods) try w.appendSlice(alloc, auth_iface_s);
    if (routes_len > 0) {
        try w.appendSlice(alloc,
            \\  files: FilesService;
        );
        try w.appendSlice(alloc, "\n  rpc: {\n");
        try w.appendSlice(alloc, rpc_section.iface_member);
        try w.appendSlice(alloc,
            \\  };
            \\  authStore: Client["authStore"];
            \\  send: Client["send"];
            \\  fetch: Client["fetch"];
            \\}
            \\
        );
    } else {
        try w.appendSlice(alloc,
            \\  files: FilesService;
            \\  authStore: Client["authStore"];
            \\  send: Client["send"];
            \\  fetch: Client["fetch"];
            \\}
            \\
        );
    }
    // options interface
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        \\export interface {s}Options {{
        \\  fetch?: typeof fetch;
        \\  WebSocket?: typeof WebSocket;
        \\  authCollection?: string;
        \\}}
        \\
    , .{client_name}));
    // createClient
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        \\export function createClient(url: string, opts: {0s}Options = {{}}): {0s} {{
        \\  const base: RealtimeEnabledClient = withRealtime(
        \\    baseCreateClient(url, {{
        \\      fetch: opts.fetch,
        \\      WebSocket: opts.WebSocket,
        \\      authCollection: opts.authCollection ?? "{1s}",
        \\    }}),
        \\  );
        \\
        \\  return {{
        \\    db: {{
        \\
    , .{ client_name, auth_collection }));
    for (cols) |c| {
        const mc = try ident.metaConst(alloc, c.name);
        const svc = try ident.serviceName(alloc, c.name);
        const resolver = if (emit_hasRelations(c)) ", relationResolver" else "";
        const file_fields = emit_hasSingleFileFields(c);
        if (c.type == .auth and file_fields) {
            // Auth collection WITH file fields: Object.assign with both authWithPassword + fileUrl.
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                \\      {0s}: Object.assign(
                \\        makeRecordService(base, {1s}{2s}) as unknown as {3s},
                \\        {{
                \\          authWithPassword: (identity: string, password: string) =>
                \\            base.collection("{0s}").authWithPassword(identity, password),
                \\          fileUrl: (record: any, field: any, opts: any) =>
                \\            base.files.getUrl({{ id: record.id, collectionName: "{0s}" }}, (record as Record<string, string>)[field] ?? "", opts),
                \\        }},
                \\      ) as unknown as {3s},
                \\
            , .{ c.name, mc, resolver, svc }));
        } else if (c.type == .auth) {
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                \\      {0s}: Object.assign(
                \\        makeRecordService(base, {1s}{2s}) as unknown as {3s},
                \\        {{
                \\          authWithPassword: (identity: string, password: string) =>
                \\            base.collection("{0s}").authWithPassword(identity, password),
                \\        }},
                \\      ) as unknown as {3s},
                \\
            , .{ c.name, mc, resolver, svc }));
        } else if (file_fields) {
            // Non-auth collection WITH file fields: Object.assign to graft fileUrl.
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                \\      {0s}: Object.assign(
                \\        makeRecordService(base, {1s}{2s}) as unknown as {3s},
                \\        {{
                \\          fileUrl: (record: any, field: any, opts: any) =>
                \\            base.files.getUrl({{ id: record.id, collectionName: "{0s}" }}, (record as Record<string, string>)[field] ?? "", opts),
                \\        }},
                \\      ) as unknown as {3s},
                \\
            , .{ c.name, mc, resolver, svc }));
        } else {
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                "      {0s}: makeRecordService(base, {1s}{2s}) as unknown as {3s},\n",
                .{ c.name, mc, resolver, svc }));
        }
    }
    try w.appendSlice(alloc, "    },\n    realtime: {\n");
    for (cols) |c| {
        const rec = try ident.recordName(alloc, c.name);
        const wn = try ident.whereName(alloc, c.name);
        const mc = try ident.metaConst(alloc, c.name);
        const resolver = if (emit_hasRelations(c)) ", relationResolver" else "";
        try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
            "      {0s}: makeTypedRealtime<{1s}, {2s}>(base.realtime, {3s}{4s}),\n",
            .{ c.name, rec, wn, mc, resolver }));
    }
    // auth method stubs in the factory (non-password methods only)
    if (has_auth_methods) {
        try w.appendSlice(alloc, "    },\n");
        try w.appendSlice(alloc, auth_factory_s);
        try w.appendSlice(alloc, "    files: base.files,\n");
    } else {
        try w.appendSlice(alloc, "    },\n    files: base.files,\n");
    }
    if (routes_len > 0) {
        try w.appendSlice(alloc, "    rpc: {\n");
        try w.appendSlice(alloc, rpc_section.factory_member);
        try w.appendSlice(alloc, "    },\n");
    }
    try w.appendSlice(alloc,
        \\    authStore: base.authStore,
        \\    send: base.send.bind(base),
        \\    fetch: base.fetch.bind(base),
        \\  };
        \\}
        \\
    );
}

fn emit_hasRelations(c: schema.Collection) bool {
    for (c.fields) |f| if (f.options == .relation) return true;
    return false;
}

/// Convert a snake_case slug (e.g. "magic_link") to camelCase (e.g. "magicLink").
/// First character is lowercased; underscores become word boundaries.
fn camelFromSlug(alloc: std.mem.Allocator, slug: []const u8) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    var upper_next = false;
    var first = true;
    for (slug) |ch| {
        if (ch == '_' or ch == '-') {
            upper_next = true;
            continue;
        }
        if (upper_next) {
            try out.append(alloc, std.ascii.toUpper(ch));
            upper_next = false;
        } else if (first) {
            try out.append(alloc, std.ascii.toLower(ch));
        } else {
            try out.append(alloc, ch);
        }
        first = false;
    }
    return out.toOwnedSlice(alloc);
}

/// Returns true if the collection has any non-password auth methods enabled.
fn hasNonPasswordAuthMethods(c: schema.Collection) bool {
    if (c.type != .auth) return false;
    const m = c.options.auth.methods;
    return m.magic_link != null or m.otp != null or m.webauthn != null or m.custom.len > 0;
}

/// Returns true if any collection in the slice has non-password auth methods.
fn anyNonPasswordAuthMethods(cols: []const schema.Collection) bool {
    for (cols) |c| if (hasNonPasswordAuthMethods(c)) return true;
    return false;
}

/// Emit the `auth` surface for non-password auth methods into both the interface
/// and factory sections.
/// Naming: client.auth.<colName>.<methodCamelCase>.initiate / .complete
/// Posts to /api/collections/<col>/auth/<slug>/initiate|complete (untyped stubs).
// TODO(typed): emit typed Initiate/Complete I/O once methods declare comptime types
fn emitAuthMethodEndpoints(
    alloc: std.mem.Allocator,
    w_iface: *W, // receives the auth: { ... } interface body
    w_factory: *W, // receives the auth: { ... } factory body
    cols: []const schema.Collection,
    api_prefix: []const u8,
) !void {
    // Build the list of (colName, []slug) pairs for non-password methods.
    // We need a helper to iterate slugs for a given MethodsOptions.
    //
    // Only emit if there is at least one collection with non-password methods.
    if (!anyNonPasswordAuthMethods(cols)) return;

    // Interface: auth: {
    try w_iface.appendSlice(alloc,
        \\  auth: {
        \\
    );
    // Factory: auth: {
    try w_factory.appendSlice(alloc,
        \\    auth: {
        \\
    );

    for (cols) |c| {
        if (!hasNonPasswordAuthMethods(c)) continue;

        // Interface: <colName>: {
        try w_iface.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: {{\n", .{c.name}));
        // Factory: <colName>: {
        try w_factory.appendSlice(alloc, try std.fmt.allocPrint(alloc, "      {s}: {{\n", .{c.name}));

        // Collect slugs of enabled non-password methods.
        const m = c.options.auth.methods;

        // Helper: emit interface + factory lines for one slug.
        const emit_slug = struct {
            fn emit(
                a: std.mem.Allocator,
                wi: *W,
                wf: *W,
                col_name: []const u8,
                slug: []const u8,
                prefix: []const u8,
            ) !void {
                const camel_name = try camelFromSlug(a, slug);
                // Interface member
                try wi.appendSlice(a, try std.fmt.allocPrint(a,
                    \\      {0s}: {{
                    \\        // TODO(typed): emit typed Initiate/Complete I/O once methods declare comptime types
                    \\        initiate(input: Record<string, unknown>, opts?: SendOptions): Promise<unknown>;
                    \\        complete(input: Record<string, unknown>, opts?: SendOptions): Promise<unknown>;
                    \\      }};
                    \\
                , .{camel_name}));
                // Factory member
                try wf.appendSlice(a, try std.fmt.allocPrint(a,
                    \\        {0s}: {{
                    \\          initiate: (input: Record<string, unknown>, opts?: SendOptions) =>
                    \\            base.send("POST", `{1s}/collections/{2s}/auth/{3s}/initiate`, {{ body: input, ...opts }}),
                    \\          complete: (input: Record<string, unknown>, opts?: SendOptions) =>
                    \\            base.send("POST", `{1s}/collections/{2s}/auth/{3s}/complete`, {{ body: input, ...opts }}),
                    \\        }},
                    \\
                , .{ camel_name, prefix, col_name, slug }));
            }
        }.emit;

        if (m.magic_link != null) try emit_slug(alloc, w_iface, w_factory, c.name, "magic_link", api_prefix);
        if (m.otp != null) try emit_slug(alloc, w_iface, w_factory, c.name, "otp", api_prefix);
        if (m.webauthn != null) try emit_slug(alloc, w_iface, w_factory, c.name, "webauthn", api_prefix);
        for (m.custom) |slug| try emit_slug(alloc, w_iface, w_factory, c.name, slug, api_prefix);

        // Interface: close colName
        try w_iface.appendSlice(alloc, "    };\n");
        // Factory: close colName
        try w_factory.appendSlice(alloc, "      },\n");
    }

    // Interface: close auth
    try w_iface.appendSlice(alloc, "  };\n");
    // Factory: close auth
    try w_factory.appendSlice(alloc, "    },\n");
}

/// Mirror of emit.zig's hasSingleFileFields: the per-collection fileUrl graft is
/// only valid for single-value file fields (a multi-value file field is string[]
/// on the record and can't be passed as a single filename). Collections whose only
/// file fields are multi-value fall through to the plain makeRecordService path.
fn emit_hasSingleFileFields(c: schema.Collection) bool {
    const tt = @import("ts_type.zig");
    for (c.fields) |f| if (tt.kindOf(f) == .file_name and !f.isMultiValue()) return true;
    return false;
}

const Args = struct {
    out: ?[]const u8 = null,
    api_prefix: []const u8 = "/api",
    check: bool = false,
};

/// Parse CLI args from the Zig 0.16 argv slice ([]const [:0]const u8).
fn parseArgsSlice(alloc: std.mem.Allocator, argv: []const [:0]const u8) !Args {
    var args = Args{};
    var i: usize = 1; // skip exe name
    while (i < argv.len) : (i += 1) {
        const a = argv[i];
        if (std.mem.eql(u8, a, "--out")) {
            i += 1;
            if (i >= argv.len) return error.MissingOutValue;
            args.out = try alloc.dupe(u8, argv[i]);
        } else if (std.mem.eql(u8, a, "--api-prefix")) {
            i += 1;
            if (i >= argv.len) return error.MissingApiPrefixValue;
            args.api_prefix = try alloc.dupe(u8, argv[i]);
        } else if (std.mem.eql(u8, a, "--check")) {
            args.check = true;
        } else {
            std.log.warn("gen_client: ignoring unknown arg '{s}'", .{a});
        }
    }
    return args;
}

/// Pick the auth collection name (first auth collection).
fn authCollectionName(cols: []const schema.Collection) []const u8 {
    for (cols) |c| if (c.type == .auth) return c.name;
    return "";
}

/// Entry point: Zig 0.16 `pub fn main(init: std.process.Init) !void`.
/// Threads `init.io` (for file operations) and uses `init.gpa` for a local arena,
/// reads argv from `init.minimal.args.toSlice(arena)` (yields `[]const [:0]const u8`).
/// Reads the ZBASE_INREPO env flag via `init.environ_map` (Zig 0.16's pure-Zig env
/// access through `std.process.Environ.Map` — no `std.c.getenv`, so this code adds no
/// libc dependency of its own).
///
/// NOTE (Task 7): In Zig 0.16, a file can only belong to one module. gen_client.zig
/// uses relative imports (@import("../schema.zig") etc.) which claim those files for
/// THIS module. If gen_client.zig is used as the exe module root AND zigbase is in
/// the dependency graph (via the `app` module), those files would be double-claimed.
/// The solution: use gen_main.zig as the exe root (which imports "zigbase" and "app"
/// as named modules) and call mainWithCollections() here. This keeps gen_client.zig
/// as a self-contained library file usable by the zigbase test suite WITHOUT being
/// a module root.
pub fn mainWithCollections(init: std.process.Init, cols: []const schema.Collection, comptime routes: []const events.RouteMeta) !void {
    const io = init.io;
    // Use an arena for all temporary allocations during the generator run.
    var arena_state = std.heap.ArenaAllocator.init(init.gpa);
    defer arena_state.deinit();
    const a = arena_state.allocator();

    // argv: []const [:0]const u8 (Zig 0.16 — init.minimal.args.toSlice returns this).
    const argv = try init.minimal.args.toSlice(a);
    const args = try parseArgsSlice(a, argv);
    const out_path = args.out orelse {
        std.log.err("gen_client: --out <path> is required", .{});
        return error.MissingOut;
    };

    // ZBASE_INREPO: read via init.environ_map (Zig 0.16 pure-Zig env access; no libc).
    // contains() means the var is set (value may be empty string — that's fine).
    const in_repo = init.environ_map.contains("ZBASE_INREPO");
    const client_name = "ZbClient";

    const text = generate(a, cols, routes, in_repo, authCollectionName(cols), client_name, args.api_prefix) catch |e| {
        // guard messages are printed via the report; re-run path for the message:
        var report = guards.GuardReport{ .message = "" };
        guards.checkOperatorNames(a, cols, &report) catch {};
        guards.checkIdentifiers(a, cols, &report) catch {};
        if (report.message.len > 0) std.log.err("{s}", .{report.message});
        return e;
    };

    if (args.check) {
        // Zig 0.16 file-read: std.Io.Dir.cwd().readFileAlloc(io, path, alloc, .limited(N))
        const existing = std.Io.Dir.cwd().readFileAlloc(io, out_path, a, .limited(64 * 1024 * 1024)) catch |e| {
            std.log.err("gen_client --check: cannot read '{s}': {s}", .{ out_path, @errorName(e) });
            return error.CheckReadFailed;
        };
        if (!std.mem.eql(u8, existing, text)) {
            std.log.err("gen_client --check: '{s}' is STALE — re-run gen-client to regenerate.", .{out_path});
            return error.Stale;
        }
        return;
    }

    // Ensure the output directory exists.
    // Zig 0.16: std.Io.Dir.cwd().createDirPath(io, dir) — NOT makePath.
    if (std.fs.path.dirname(out_path)) |dir| {
        std.Io.Dir.cwd().createDirPath(io, dir) catch {};
    }
    // Zig 0.16 file-write: std.Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = bytes })
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = text });
    std.log.info("gen_client: wrote {s} ({d} bytes)", .{ out_path, text.len });
}

/// Legacy entry point kept for back-compat; reads @import("app").App.collections.
/// Prefer mainWithCollections when building as a separate module to avoid
/// the Zig 0.16 "file exists in multiple modules" error (see note above).
pub fn main(init: std.process.Init) !void {
    const app = @import("app");
    return mainWithCollections(init, app.App.collections, app.App.routes);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

fn miniBlog(alloc: std.mem.Allocator) ![]const schema.Collection {
    const tags_f = try alloc.dupe(schema.Field, &.{.{ .id = "a", .name = "label", .required = true, .options = .{ .text = .{} } }});
    const users_f = try alloc.dupe(schema.Field, &.{.{ .id = "b", .name = "name", .options = .{ .text = .{} } }});
    const posts_f = try alloc.dupe(schema.Field, &.{
        .{ .id = "c", .name = "title", .required = true, .options = .{ .text = .{} } },
        .{ .id = "d", .name = "status", .options = .{ .select = .{ .values = &.{ "draft", "published" }, .maxSelect = 1 } } },
        .{ .id = "e", .name = "author", .options = .{ .relation = .{ .targetCollectionId = "users", .maxSelect = 1 } } },
        .{ .id = "f", .name = "tags", .options = .{ .relation = .{ .targetCollectionId = "tags", .maxSelect = 99 } } },
        .{ .id = "g", .name = "cover", .options = .{ .file = .{ .maxSelect = 1 } } },
    });
    return try alloc.dupe(schema.Collection, &.{
        .{ .id = "", .name = "posts", .fields = posts_f },
        .{ .id = "", .name = "users", .type = .auth, .fields = users_f },
        .{ .id = "", .name = "tags", .fields = tags_f },
    });
}

test "generate emits a parseable file with the expected top-level constructs" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const out = try generate(a, cols, &.{}, true, "users", "BlogClient", "/api");
    try std.testing.expect(std.mem.startsWith(u8, out, "// generated by zigbase — do not edit\n// schema-hash: "));
    inline for (.{
        "export interface Post {",        "export type PostStatus =",
        "export interface PostCreate {",  "export type PostUpdate =",
        "export interface PostWhere {",   "export type PostRelations =",
        "export type PostExpand =",       "export interface PostFields {",
        "export interface PostsService {","export const postsMeta: CollectionMeta = {",
        "const relationResolver: RelationResolver =",
        "export type PostsRealtime = RawTypedRealtime<Post, PostWhere>;",
        "export interface BlogClient {",  "export function createClient(",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, out, needle) != null);
}

test "schemaHash is deterministic + order-sensitive" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    try std.testing.expectEqual(schemaHash(cols), schemaHash(cols));
    // mutating a field name changes the hash
    var cols2 = try a.dupe(schema.Collection, cols);
    var f2 = try a.dupe(schema.Field, cols2[0].fields);
    f2[0].name = "headline";
    cols2[0].fields = f2;
    try std.testing.expect(schemaHash(cols) != schemaHash(cols2));
}

test "--check diff: stale buffer differs from fresh output" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const fresh = try generate(a, cols, &.{}, true, "users", "BlogClient", "/api");
    const stale = try std.fmt.allocPrint(a, "{s}\n// drift\n", .{fresh});
    try std.testing.expect(!std.mem.eql(u8, fresh, stale)); // --check would exit non-zero
    try std.testing.expect(std.mem.eql(u8, fresh, fresh));   // --check would exit zero
}

test "guards run inside generate: operator-named relation target errors" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const tag_f = try a.dupe(schema.Field, &.{.{ .id = "x", .name = "in", .options = .{ .text = .{} } }});
    const post_f = try a.dupe(schema.Field, &.{.{ .id = "y", .name = "labels", .options = .{ .relation = .{ .targetCollectionId = "tags" } } }});
    const cols = try a.dupe(schema.Collection, &.{
        .{ .id = "", .name = "tags", .fields = tag_f },
        .{ .id = "", .name = "posts", .fields = post_f },
    });
    try std.testing.expectError(guards.GuardError.OperatorNameClash, generate(a, cols, &.{}, true, "", "ZbClient", "/api"));
}

test "auth-method endpoints: magic_link emits initiate/complete stubs; password emits nothing" {
    // Verifies that emitAuthMethodEndpoints generates initiate/complete stubs for non-password methods.
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    // An auth collection with magic_link enabled.
    const members_cols = try a.dupe(schema.Collection, &.{
        .{
            .id = "",
            .name = "members",
            .type = .auth,
            .fields = &.{},
            .options = .{ .auth = .{ .methods = .{ .magic_link = .{} } } },
        },
    });
    const out_ml = try generate(a, members_cols, &.{}, true, "members", "MembersClient", "/api");
    // Should contain magic_link initiate + complete paths
    try std.testing.expect(std.mem.indexOf(u8, out_ml, "/auth/magic_link/initiate") != null);
    try std.testing.expect(std.mem.indexOf(u8, out_ml, "/auth/magic_link/complete") != null);
    // Should contain the camelCase method name
    try std.testing.expect(std.mem.indexOf(u8, out_ml, "magicLink") != null);

    // An auth collection with ONLY password — no non-password stubs.
    const pw_cols = try a.dupe(schema.Collection, &.{
        .{
            .id = "",
            .name = "users",
            .type = .auth,
            .fields = &.{},
            .options = .{ .auth = .{ .methods = .{ .password = .{} } } },
        },
    });
    const out_pw = try generate(a, pw_cols, &.{}, true, "users", "UsersClient", "/api");
    // Should NOT contain any /auth/password/ URL stubs
    try std.testing.expect(std.mem.indexOf(u8, out_pw, "/auth/password/") == null);
    // Should NOT contain an auth namespace on the client interface
    try std.testing.expect(std.mem.indexOf(u8, out_pw, "auth: {") == null);
}
