//! Pure-Zig TypeScript client generator executable.
//! Reads @import("app").App.collections and emits a zbase.gen.ts.
//! Pure functions (generate, schemaHash) use relative imports so they can be
//! reached by the library test suite without a circular zigbase reference.
//! main() is the only function that touches @import("zigbase")/@import("app") and IO.
const std = @import("std");
const schema = @import("../schema.zig");
const events = @import("../events.zig");
const features = @import("../features.zig");
const emit = @import("emit.zig");
const guards = @import("guards.zig");
const ident = @import("identifiers.zig");
const rpc_ts = @import("rpc_ts.zig");
const rpc = @import("rpc.zig");
const gen_dart = @import("gen_dart.zig");
const gen_python = @import("gen_python.zig");
const gen_kotlin = @import("gen_kotlin.zig");

const W = std.ArrayList(u8);

/// FNV-1a over a canonical serialization of the collections (declared order).
pub fn schemaHash(cols: []const schema.Collection) u64 {
    var h = std.hash.Fnv1a_64.init();
    for (cols) |c| {
        h.update(c.name);
        h.update("|");
        h.update(@tagName(c.type));
        for (c.fields) |f| {
            h.update("\x00");
            h.update(f.name);
            h.update(":");
            h.update(@tagName(std.meta.activeTag(f.options)));
            if (f.required) h.update("!");
            if (f.isMultiValue()) h.update("*");
            if (f.searchable) h.update("?");
            switch (f.options) {
                .select => |o| for (o.values) |v| {
                    h.update(",");
                    h.update(v);
                },
                .relation => |o| {
                    h.update("->");
                    h.update(o.targetCollectionId);
                },
                else => {},
            }
        }
        if (c.options.tenant_field) |tf| {
            h.update("\x01tenant:");
            h.update(tf);
        }
    }
    return h.final();
}

fn section(alloc: std.mem.Allocator, w: *W, title: []const u8) !void {
    const line = try std.fmt.allocPrint(alloc, "\n// ---- {s} " ++ ("-" ** 4) ++ "\n\n", .{title});
    try w.appendSlice(alloc, line);
}

/// The pure generator core: collections -> full file text. Runs guards first.
pub fn generate(
    alloc: std.mem.Allocator,
    cols: []const schema.Collection,
    comptime routes: []const events.RouteMeta,
    comptime custom_auth: []const events.CustomAuthMeta,
    // Declared feature-flag + experiment metadata (#130). Plain data (no `type`
    // fields), so these are runtime params; the runtime-introspection path passes
    // empty (`&.{}`), exactly the asymmetry of routes/custom_auth.
    flags: []const features.FlagDef,
    experiments: []const features.ExperimentDef,
    in_repo: bool,
    auth_collection: []const u8,
    client_name: []const u8,
    api_prefix: []const u8,
) ![]const u8 {
    // Validate that every route path starts with the given api_prefix.
    // Must use `inline for` because RouteMeta contains `Input: type` (comptime-only field).
    inline for (routes) |r| {
        if (!std.mem.startsWith(u8, r.path, api_prefix)) {
            std.log.err("gen_client: route '{s}' does not start with --api-prefix '{s}'; the framework route prefix and the generator prefix disagree.", .{ r.path, api_prefix });
            return error.RoutePrefixMismatch;
        }
    }

    var report = guards.GuardReport{ .message = "" };
    try guards.checkOperatorNames(alloc, cols, &report);
    try guards.checkIdentifiers(alloc, cols, &report);

    var w: W = .empty;
    // header
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "// generated by zigbase — do not edit\n// schema-hash: {x:0>16}\n//\n", .{schemaHash(cols)}));
    if (in_repo) {
        try w.appendSlice(alloc,
            \\// In a consumer repo this file imports from "@zigbase/client" and
            \\// "@zigbase/client/typed". In this in-repo snapshot we import from the
            \\// package source so it typechecks against the working tree without a built dist.
            \\
        );
    } else {
        try w.appendSlice(alloc,
            \\// This client imports its runtime and types from the "@zigbase/client"
            \\// and "@zigbase/client/typed" packages.
            \\
        );
    }
    // SendOptions is referenced by typed RPC routes AND by auth-method stubs
    // (built-in or custom), so import it whenever either is present.
    try emit.emitImports(alloc, &w, in_repo, routes.len > 0 or anyNonPasswordAuthMethods(cols));

    try section(alloc, &w, "Records");
    for (cols) |c| try emit.emitSelectUnions(alloc, &w, c);
    for (cols) |c| {
        try emit.emitRecord(alloc, &w, c);
        try w.appendSlice(alloc, "\n");
    }
    try section(alloc, &w, "Create / Update payloads");
    for (cols) |c| {
        try emit.emitCreate(alloc, &w, c);
        try emit.emitUpdate(alloc, &w, c);
    }
    try section(alloc, &w, "Where types");
    for (cols) |c| try emit.emitWhere(alloc, &w, cols, c);
    try section(alloc, &w, "Relations + expand keys");
    for (cols) |c| {
        try emit.emitRelations(alloc, &w, cols, c);
        try emit.emitExpandKeys(alloc, &w, cols, c);
    }
    try section(alloc, &w, "Fluent accessor types");
    for (cols) |c| {
        try emit.emitFields(alloc, &w, c);
        try emit.emitSortUnion(alloc, &w, c);
    }
    try section(alloc, &w, "Concrete service interfaces");
    for (cols) |c| try emit.emitService(alloc, &w, c);
    try section(alloc, &w, "Per-collection metadata");
    for (cols) |c| try emit.emitMeta(alloc, &w, c);
    try emit.emitRelationResolver(alloc, &w, cols);
    try section(alloc, &w, "Typed files surface");
    try emit.emitTypedFiles(alloc, &w, cols);
    try section(alloc, &w, "Typed realtime surface");
    for (cols) |c| try emit.emitRealtimeAlias(alloc, &w, c);
    try section(alloc, &w, "createClient");
    // One SeenMap shared across the typed RPC route surface AND the typed custom-auth
    // surface, so two DISTINCT Zig types that map to the same TS name across those
    // surfaces are caught (error.RpcTypeNameCollision) instead of emitting an
    // ambiguous client (Decision E).
    var seen = rpc_ts.SeenMap.init(alloc);
    defer seen.deinit();
    const rpc_section = try rpc.renderShared(routes, alloc, &seen);
    // rpc_section slices are owned by the arena (alloc), freed on arena deinit.
    try emitClientFactory(alloc, &w, cols, client_name, auth_collection, rpc_section, routes.len, api_prefix, custom_auth, &seen, flags, experiments);

    return w.toOwnedSlice(alloc);
}

/// The createClient + client-interface block (mirrors blog.gen.ts createClient).
fn emitClientFactory(
    alloc: std.mem.Allocator,
    w: *W,
    cols: []const schema.Collection,
    client_name: []const u8,
    auth_collection: []const u8,
    rpc_section: rpc.Section,
    routes_len: usize,
    api_prefix: []const u8,
    comptime custom_auth: []const events.CustomAuthMeta,
    seen: *rpc_ts.SeenMap,
    flags: []const features.FlagDef,
    experiments: []const features.ExperimentDef,
) !void {
    // The typed feature-state surface (`zb.flags.resolveAll`) is emitted only when the
    // app declares at least one flag or experiment (otherwise the snapshot is unchanged).
    const has_features = flags.len > 0 or experiments.len > 0;
    // Pre-build the auth iface + factory sections (empty if no non-password methods).
    // `auth_decls` receives the named `export interface`/`export type` declarations for
    // any TYPED custom auth methods (deduped through the shared `seen` map).
    var auth_iface: W = .empty;
    var auth_factory: W = .empty;
    var auth_decls: W = .empty;
    try emitAuthMethodEndpoints(alloc, &auth_iface, &auth_factory, &auth_decls, cols, api_prefix, custom_auth, seen);
    const auth_iface_s = try auth_iface.toOwnedSlice(alloc);
    const auth_factory_s = try auth_factory.toOwnedSlice(alloc);
    const auth_decls_s = try auth_decls.toOwnedSlice(alloc);
    const has_auth_methods = auth_iface_s.len > 0;

    // Emit named RPC Input/Output decls before the client interface (only when routes exist).
    if (routes_len > 0) {
        try w.appendSlice(alloc, rpc_section.decls);
    }
    // Emit the shared built-in auth-method I/O interfaces before the client interface
    // (only for built-ins actually enabled across the collections).
    if (has_auth_methods) try emitAuthMethodIODecls(alloc, w, cols);
    // Emit named decls for any TYPED custom auth methods (after built-ins, still before
    // the client interface that references them).
    if (auth_decls_s.len > 0) {
        try section(alloc, w, "Custom auth method I/O");
        try w.appendSlice(alloc, auth_decls_s);
    }
    // Named FeatureState type for the public `zb.flags.resolveAll` surface (#130):
    // flags as named booleans, experiments as string-literal unions of their variants.
    if (has_features) {
        try section(alloc, w, "Feature state");
        try emitFeatureState(alloc, w, flags, experiments);
    }
    // BlogClient-style interface
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "export interface {s} {{\n  db: {{\n", .{client_name}));
    for (cols) |c| try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: {s};\n", .{ c.name, try ident.serviceName(alloc, c.name) }));
    try w.appendSlice(alloc, "  };\n  realtime: {\n");
    for (cols) |c| try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: {s};\n", .{ c.name, try ident.realtimeAliasName(alloc, c.name) }));
    // auth method stubs (non-password methods only; password stays on db.<col>.authWithPassword)
    try w.appendSlice(alloc, "  };\n");
    if (has_auth_methods) try w.appendSlice(alloc, auth_iface_s);
    if (has_features) try w.appendSlice(alloc,
        \\  flags: {
        \\    resolveAll(subject: string): Promise<FeatureState>;
        \\  };
        \\
    );
    if (routes_len > 0) {
        try w.appendSlice(alloc,
            \\  files: FilesService;
        );
        try w.appendSlice(alloc, "\n  rpc: {\n");
        try w.appendSlice(alloc, rpc_section.iface_member);
        try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
            \\  }};
            \\  accounts: Client["accounts"];
            \\  analytics: Client["analytics"];
            \\  senders: Client["senders"];
            \\  withAccount(accountId: string): {0s};
            \\  authStore: Client["authStore"];
            \\  send: Client["send"];
            \\  fetch: Client["fetch"];
            \\}}
            \\
        , .{client_name}));
    } else {
        try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
            \\  files: FilesService;
            \\  accounts: Client["accounts"];
            \\  analytics: Client["analytics"];
            \\  senders: Client["senders"];
            \\  withAccount(accountId: string): {0s};
            \\  authStore: Client["authStore"];
            \\  send: Client["send"];
            \\  fetch: Client["fetch"];
            \\}}
            \\
        , .{client_name}));
    }
    // options interface
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        \\export interface {s}Options {{
        \\  fetch?: typeof fetch;
        \\  WebSocket?: typeof WebSocket;
        \\  authCollection?: string;
        \\}}
        \\
    , .{client_name}));
    // createClient
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        \\export function createClient(url: string, opts: {0s}Options = {{}}): {0s} {{
        \\  const base: RealtimeEnabledClient = withRealtime(
        \\    baseCreateClient(url, {{
        \\      fetch: opts.fetch,
        \\      WebSocket: opts.WebSocket,
        \\      authCollection: opts.authCollection ?? "{1s}",
        \\    }}),
        \\  );
        \\  return makeClient(base);
        \\}}
        \\
        \\/** Build the typed facade over a realtime-enabled base client. All facades are
        \\ *  stateless wrappers, so `withAccount` can rebuild them cheaply per scope. */
        \\function makeClient(base: RealtimeEnabledClient): {0s} {{
        \\  return {{
        \\    db: {{
        \\
    , .{ client_name, auth_collection }));
    for (cols) |c| {
        const mc = try ident.metaConst(alloc, c.name);
        const svc = try ident.serviceName(alloc, c.name);
        const resolver = if (emit_hasRelations(c)) ", relationResolver" else "";
        const file_fields = emit_hasSingleFileFields(c);
        if (c.type == .auth and file_fields) {
            // Auth collection WITH file fields: Object.assign with both authWithPassword + fileUrl.
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                \\      {0s}: Object.assign(
                \\        makeRecordService(base, {1s}{2s}) as unknown as {3s},
                \\        {{
                \\          authWithPassword: (identity: string, password: string) =>
                \\            base.collection("{0s}").authWithPassword(identity, password),
                \\          fileUrl: (record: any, field: any, opts: any) =>
                \\            base.files.getUrl({{ id: record.id, collectionName: "{0s}" }}, (record as Record<string, string>)[field] ?? "", opts),
                \\        }},
                \\      ) as unknown as {3s},
                \\
            , .{ c.name, mc, resolver, svc }));
        } else if (c.type == .auth) {
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                \\      {0s}: Object.assign(
                \\        makeRecordService(base, {1s}{2s}) as unknown as {3s},
                \\        {{
                \\          authWithPassword: (identity: string, password: string) =>
                \\            base.collection("{0s}").authWithPassword(identity, password),
                \\        }},
                \\      ) as unknown as {3s},
                \\
            , .{ c.name, mc, resolver, svc }));
        } else if (file_fields) {
            // Non-auth collection WITH file fields: Object.assign to graft fileUrl.
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
                \\      {0s}: Object.assign(
                \\        makeRecordService(base, {1s}{2s}) as unknown as {3s},
                \\        {{
                \\          fileUrl: (record: any, field: any, opts: any) =>
                \\            base.files.getUrl({{ id: record.id, collectionName: "{0s}" }}, (record as Record<string, string>)[field] ?? "", opts),
                \\        }},
                \\      ) as unknown as {3s},
                \\
            , .{ c.name, mc, resolver, svc }));
        } else {
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "      {0s}: makeRecordService(base, {1s}{2s}) as unknown as {3s},\n", .{ c.name, mc, resolver, svc }));
        }
    }
    try w.appendSlice(alloc, "    },\n    realtime: {\n");
    for (cols) |c| {
        const rec = try ident.recordName(alloc, c.name);
        const wn = try ident.whereName(alloc, c.name);
        const mc = try ident.metaConst(alloc, c.name);
        const resolver = if (emit_hasRelations(c)) ", relationResolver" else "";
        try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "      {0s}: makeTypedRealtime<{1s}, {2s}>(base.realtime, {3s}{4s}),\n", .{ c.name, rec, wn, mc, resolver }));
    }
    // auth method stubs in the factory (non-password methods only)
    if (has_auth_methods) {
        try w.appendSlice(alloc, "    },\n");
        try w.appendSlice(alloc, auth_factory_s);
    } else {
        try w.appendSlice(alloc, "    },\n");
    }
    // Typed feature-state surface (#130): GET <prefix>/state?subject=<id>.
    if (has_features) {
        try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
            \\    flags: {{
            \\      resolveAll: (subject: string): Promise<FeatureState> =>
            \\        base.send<FeatureState>("GET", `{s}/state?subject=${{encodeURIComponent(subject)}}`),
            \\    }},
            \\
        , .{api_prefix}));
    }
    try w.appendSlice(alloc, "    files: base.files,\n");
    if (routes_len > 0) {
        try w.appendSlice(alloc, "    rpc: {\n");
        try w.appendSlice(alloc, rpc_section.factory_member);
        try w.appendSlice(alloc, "    },\n");
    }
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        \\    accounts: base.accounts,
        \\    analytics: base.analytics,
        \\    senders: base.senders,
        \\    withAccount: (accountId: string): {0s} => makeClient(withRealtime(base.withAccount(accountId))),
        \\    authStore: base.authStore,
        \\    send: base.send.bind(base),
        \\    fetch: base.fetch.bind(base),
        \\  }};
        \\}}
        \\
    , .{client_name}));
}

/// Emit `export interface FeatureState { … }` for the public `zb.flags.resolveAll`
/// surface (#130): each declared flag is a named `boolean`; each experiment is a
/// string-literal union of its declared variants. Empty groups map to
/// `Record<string, never>` (the precise empty-object type the server returns).
/// Flag/experiment names are Zig identifiers, so they need no quoting.
fn emitFeatureState(
    alloc: std.mem.Allocator,
    w: *W,
    flags: []const features.FlagDef,
    experiments: []const features.ExperimentDef,
) !void {
    try w.appendSlice(alloc, "export interface FeatureState {\n");
    if (flags.len == 0) {
        try w.appendSlice(alloc, "  flags: Record<string, never>;\n");
    } else {
        try w.appendSlice(alloc, "  flags: {\n");
        for (flags) |f| try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: boolean;\n", .{f.name}));
        try w.appendSlice(alloc, "  };\n");
    }
    if (experiments.len == 0) {
        try w.appendSlice(alloc, "  experiments: Record<string, never>;\n");
    } else {
        try w.appendSlice(alloc, "  experiments: {\n");
        for (experiments) |e| {
            try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: ", .{e.name}));
            for (e.variants, 0..) |v, i| {
                if (i > 0) try w.appendSlice(alloc, " | ");
                try w.appendSlice(alloc, try std.fmt.allocPrint(alloc, "\"{s}\"", .{v}));
            }
            try w.appendSlice(alloc, ";\n");
        }
        try w.appendSlice(alloc, "  };\n");
    }
    try w.appendSlice(alloc, "}\n");
}

fn emit_hasRelations(c: schema.Collection) bool {
    for (c.fields) |f| if (f.options == .relation) return true;
    return false;
}

/// Convert a snake_case slug (e.g. "magic_link") to camelCase (e.g. "magicLink").
/// First character is lowercased; underscores become word boundaries.
fn camelFromSlug(alloc: std.mem.Allocator, slug: []const u8) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    var upper_next = false;
    var first = true;
    for (slug) |ch| {
        if (ch == '_' or ch == '-') {
            upper_next = true;
            continue;
        }
        if (upper_next) {
            try out.append(alloc, std.ascii.toUpper(ch));
            upper_next = false;
        } else if (first) {
            try out.append(alloc, std.ascii.toLower(ch));
        } else {
            try out.append(alloc, ch);
        }
        first = false;
    }
    return out.toOwnedSlice(alloc);
}

/// Returns true if the collection has any non-password auth methods enabled.
fn hasNonPasswordAuthMethods(c: schema.Collection) bool {
    if (c.type != .auth) return false;
    const m = c.options.auth.methods;
    return m.magic_link != null or m.otp != null or m.webauthn != null or m.custom.len > 0;
}

/// Returns true if any collection in the slice has non-password auth methods.
fn anyNonPasswordAuthMethods(cols: []const schema.Collection) bool {
    for (cols) |c| if (hasNonPasswordAuthMethods(c)) return true;
    return false;
}

/// Typed I/O descriptor for a built-in auth method. The three built-ins
/// (magic_link, otp, webauthn) have FIXED server-side request/response contracts
/// (see src/auth/methods/*.zig + src/api/auth_methods.zig), so the generator can
/// emit precise TS types. Custom methods (m.custom slugs) carry no type info and
/// stay on the untyped `Record<string, unknown>`/`unknown` stubs (see below).
const BuiltinIO = struct {
    /// camelCase accessor name on `client.auth.<col>.<camel>`.
    camel: []const u8,
    /// TS type of the `initiate` input body.
    init_input: []const u8,
    /// TS type the `initiate` promise resolves to.
    init_result: []const u8,
    /// TS type of the `complete` input body.
    complete_input: []const u8,
    /// TS type the `complete` promise resolves to.
    complete_result: []const u8,
};

/// Map a built-in slug to its typed I/O contract. Returns null for custom slugs.
///
/// Contracts derived directly from the handlers:
///   - magic_link: initiate reads {identity} → 204 (void); complete reads {token}
///     → 200 {token} (src/auth/methods/magic_link.zig).
///   - otp: initiate reads {identity} → 204 (void); complete reads {identity, code}
///     → 200 {token} (src/auth/methods/otp.zig).
///   - webauthn: initiate reads optional {identity} → 200
///     {challenge, rpId, ceremonyId, timeout}; complete reads
///     {ceremonyId, credentialId, authenticatorData, clientDataJSON, signature}
///     → 200 {token} (src/auth/methods/webauthn.zig).
/// All three `complete` paths return `{token}` (AuthMethodResult) — the session is
/// also set via cookies by src/api/auth_methods.zig's dispatch().
fn builtinIO(slug: []const u8) ?BuiltinIO {
    if (std.mem.eql(u8, slug, "magic_link")) return .{
        .camel = "magicLink",
        .init_input = "MagicLinkInitiateInput",
        .init_result = "void",
        .complete_input = "MagicLinkCompleteInput",
        .complete_result = "AuthMethodResult",
    };
    if (std.mem.eql(u8, slug, "otp")) return .{
        .camel = "otp",
        .init_input = "OtpInitiateInput",
        .init_result = "void",
        .complete_input = "OtpCompleteInput",
        .complete_result = "AuthMethodResult",
    };
    if (std.mem.eql(u8, slug, "webauthn")) return .{
        .camel = "webauthn",
        .init_input = "WebAuthnInitiateInput",
        .init_result = "WebAuthnInitiateResult",
        .complete_input = "WebAuthnCompleteInput",
        .complete_result = "AuthMethodResult",
    };
    return null;
}

/// Emit the shared TS interfaces for the built-in auth-method I/O contracts that
/// are actually enabled across `cols`. These are global (the contract is the same
/// regardless of which collection enables the method), so they are emitted once,
/// just before the client interface. `AuthMethodResult` is shared by every
/// built-in `complete`.
fn emitAuthMethodIODecls(alloc: std.mem.Allocator, w: *W, cols: []const schema.Collection) !void {
    var any_ml = false;
    var any_otp = false;
    var any_wa = false;
    for (cols) |c| {
        if (c.type != .auth) continue;
        const m = c.options.auth.methods;
        if (m.magic_link != null) any_ml = true;
        if (m.otp != null) any_otp = true;
        if (m.webauthn != null) any_wa = true;
    }
    if (!any_ml and !any_otp and !any_wa) return;

    try section(alloc, w, "Built-in auth method I/O");
    // Shared success result for every built-in `complete` (the session is also set
    // via zb_auth/zb_csrf cookies on the response).
    try w.appendSlice(alloc,
        \\export interface AuthMethodResult {
        \\  /** Session JWT. Session cookies (zb_auth/zb_csrf) are also set on the response. */
        \\  token: string;
        \\}
        \\
    );
    if (any_ml) try w.appendSlice(alloc,
        \\export interface MagicLinkInitiateInput {
        \\  /** Email/identity to send the single-use sign-in link to. */
        \\  identity: string;
        \\}
        \\export interface MagicLinkCompleteInput {
        \\  /** The single-use link token delivered by email. */
        \\  token: string;
        \\}
        \\
    );
    if (any_otp) try w.appendSlice(alloc,
        \\export interface OtpInitiateInput {
        \\  /** Email/identity to send the one-time code to. */
        \\  identity: string;
        \\}
        \\export interface OtpCompleteInput {
        \\  identity: string;
        \\  /** The one-time numeric code delivered by email. */
        \\  code: string;
        \\}
        \\
    );
    if (any_wa) try w.appendSlice(alloc,
        \\export interface WebAuthnInitiateInput {
        \\  /** Optional identity; omit for a usernameless (discoverable) login. */
        \\  identity?: string;
        \\}
        \\export interface WebAuthnInitiateResult {
        \\  /** base64url-encoded random challenge to sign. */
        \\  challenge: string;
        \\  rpId: string;
        \\  /** Opaque id correlating this initiate with the matching complete. */
        \\  ceremonyId: string;
        \\  /** Ceremony timeout in milliseconds. */
        \\  timeout: number;
        \\}
        \\export interface WebAuthnCompleteInput {
        \\  ceremonyId: string;
        \\  /** base64url credential id of the passkey used. */
        \\  credentialId: string;
        \\  /** base64url authenticatorData from the assertion. */
        \\  authenticatorData: string;
        \\  /** base64url clientDataJSON from the assertion. */
        \\  clientDataJSON: string;
        \\  /** base64url signature from the assertion. */
        \\  signature: string;
        \\}
        \\
    );
}

/// Emit the `auth` surface for non-password auth methods into both the interface
/// and factory sections.
/// Naming: client.auth.<colName>.<methodCamelCase>.initiate / .complete
/// Posts to /api/collections/<col>/auth/<slug>/initiate|complete.
/// Built-in methods (magic_link/otp/webauthn) get precise typed I/O (see
/// builtinIO + emitAuthMethodIODecls); custom slugs keep the untyped stubs.
fn emitAuthMethodEndpoints(
    alloc: std.mem.Allocator,
    w_iface: *W, // receives the auth: { ... } interface body
    w_factory: *W, // receives the auth: { ... } factory body
    w_decls: *W, // receives named decls for TYPED custom methods
    cols: []const schema.Collection,
    api_prefix: []const u8,
    comptime custom_auth: []const events.CustomAuthMeta,
    seen: *rpc_ts.SeenMap,
) !void {
    // Build the list of (colName, []slug) pairs for non-password methods.
    // We need a helper to iterate slugs for a given MethodsOptions.
    //
    // Only emit if there is at least one collection with non-password methods.
    if (!anyNonPasswordAuthMethods(cols)) return;

    // Interface: auth: {
    try w_iface.appendSlice(alloc,
        \\  auth: {
        \\
    );
    // Factory: auth: {
    try w_factory.appendSlice(alloc,
        \\    auth: {
        \\
    );

    for (cols) |c| {
        if (!hasNonPasswordAuthMethods(c)) continue;

        // Interface: <colName>: {
        try w_iface.appendSlice(alloc, try std.fmt.allocPrint(alloc, "    {s}: {{\n", .{c.name}));
        // Factory: <colName>: {
        try w_factory.appendSlice(alloc, try std.fmt.allocPrint(alloc, "      {s}: {{\n", .{c.name}));

        // Collect slugs of enabled non-password methods.
        const m = c.options.auth.methods;

        // Helper: emit TYPED interface + factory lines for one built-in slug.
        const emit_builtin = struct {
            fn emit(
                a: std.mem.Allocator,
                wi: *W,
                wf: *W,
                col_name: []const u8,
                slug: []const u8,
                prefix: []const u8,
                io: BuiltinIO,
            ) !void {
                // Interface member
                try wi.appendSlice(a, try std.fmt.allocPrint(a,
                    \\      {0s}: {{
                    \\        initiate(input: {1s}, opts?: SendOptions): Promise<{2s}>;
                    \\        complete(input: {3s}, opts?: SendOptions): Promise<{4s}>;
                    \\      }};
                    \\
                , .{ io.camel, io.init_input, io.init_result, io.complete_input, io.complete_result }));
                // Factory member — explicit send<T> type args so the object literal
                // is assignable to the typed interface above.
                try wf.appendSlice(a, try std.fmt.allocPrint(a,
                    \\        {0s}: {{
                    \\          initiate: (input: {4s}, opts?: SendOptions): Promise<{5s}> =>
                    \\            base.send<{5s}>("POST", `{1s}/collections/{2s}/auth/{3s}/initiate`, {{ body: input, ...opts }}),
                    \\          complete: (input: {6s}, opts?: SendOptions): Promise<{7s}> =>
                    \\            base.send<{7s}>("POST", `{1s}/collections/{2s}/auth/{3s}/complete`, {{ body: input, ...opts }}),
                    \\        }},
                    \\
                , .{ io.camel, prefix, col_name, slug, io.init_input, io.init_result, io.complete_input, io.complete_result }));
            }
        }.emit;

        // Helper: emit UNTYPED interface + factory lines for one custom slug.
        const emit_custom = struct {
            fn emit(
                a: std.mem.Allocator,
                wi: *W,
                wf: *W,
                col_name: []const u8,
                slug: []const u8,
                prefix: []const u8,
            ) !void {
                const camel_name = try camelFromSlug(a, slug);
                // Interface member
                try wi.appendSlice(a, try std.fmt.allocPrint(a,
                    \\      {0s}: {{
                    \\        // TODO(typed): custom auth methods carry no type info (m.custom is bare
                    \\        // slug strings). Typing these needs a comptime typed-I/O declaration API
                    \\        // — m.custom entries carrying comptime Input/Output Zig types the generator
                    \\        // can reflect. Until then these stay untyped.
                    \\        initiate(input: Record<string, unknown>, opts?: SendOptions): Promise<unknown>;
                    \\        complete(input: Record<string, unknown>, opts?: SendOptions): Promise<unknown>;
                    \\      }};
                    \\
                , .{camel_name}));
                // Factory member
                try wf.appendSlice(a, try std.fmt.allocPrint(a,
                    \\        {0s}: {{
                    \\          initiate: (input: Record<string, unknown>, opts?: SendOptions) =>
                    \\            base.send("POST", `{1s}/collections/{2s}/auth/{3s}/initiate`, {{ body: input, ...opts }}),
                    \\          complete: (input: Record<string, unknown>, opts?: SendOptions) =>
                    \\            base.send("POST", `{1s}/collections/{2s}/auth/{3s}/complete`, {{ body: input, ...opts }}),
                    \\        }},
                    \\
                , .{ camel_name, prefix, col_name, slug }));
            }
        }.emit;

        if (m.magic_link != null) try emit_builtin(alloc, w_iface, w_factory, c.name, "magic_link", api_prefix, builtinIO("magic_link").?);
        if (m.otp != null) try emit_builtin(alloc, w_iface, w_factory, c.name, "otp", api_prefix, builtinIO("otp").?);
        if (m.webauthn != null) try emit_builtin(alloc, w_iface, w_factory, c.name, "webauthn", api_prefix, builtinIO("webauthn").?);
        for (m.custom) |slug| {
            // A custom slug declared with comptime I/O types (a struct entry in the
            // `.custom` tuple) gets a TYPED surface; a bare-string slug stays untyped.
            var matched = false;
            inline for (custom_auth) |cm| {
                if (!matched and std.mem.eql(u8, cm.col_name, c.name) and std.mem.eql(u8, cm.slug, slug)) {
                    try emitCustomTyped(alloc, w_iface, w_factory, w_decls, seen, c.name, slug, cm, api_prefix);
                    matched = true;
                }
            }
            if (!matched) try emit_custom(alloc, w_iface, w_factory, c.name, slug, api_prefix);
        }

        // Interface: close colName
        try w_iface.appendSlice(alloc, "    };\n");
        // Factory: close colName
        try w_factory.appendSlice(alloc, "      },\n");
    }

    // Interface: close auth
    try w_iface.appendSlice(alloc, "  };\n");
    // Factory: close auth
    try w_factory.appendSlice(alloc, "    },\n");
}

/// Emit the TYPED interface + factory + named-decls for one custom auth method whose
/// comptime I/O types were declared via the `.custom` struct form. Mirrors the
/// built-in path (`emit_builtin` + `emitAuthMethodIODecls`) but reflects the declared
/// Zig types through `rpc_ts` (interfaces named by the Zig type's own short name).
/// A `void` Input omits the `input` argument; a `void` Output maps to `Promise<void>`
/// (Decision C). Named decls are deduped through the shared `seen` map (Decision E).
fn emitCustomTyped(
    a: std.mem.Allocator,
    wi: *W,
    wf: *W,
    wd: *W,
    seen: *rpc_ts.SeenMap,
    col_name: []const u8,
    slug: []const u8,
    comptime cm: events.CustomAuthMeta,
    prefix: []const u8,
) !void {
    const camel = try camelFromSlug(a, slug);

    // Named `export interface`/`export type` decls for each non-scalar I/O type,
    // dependencies first, deduped (and collision-checked) via the shared seen map.
    try rpc_ts.renderNamedDeclsShared(cm.InitiateInput, wd, a, seen);
    try rpc_ts.renderNamedDeclsShared(cm.InitiateOutput, wd, a, seen);
    try rpc_ts.renderNamedDeclsShared(cm.CompleteInput, wd, a, seen);
    try rpc_ts.renderNamedDeclsShared(cm.CompleteOutput, wd, a, seen);

    const init_in = comptime rpc_ts.tsForType(cm.InitiateInput);
    const init_out = comptime rpc_ts.tsForType(cm.InitiateOutput);
    const comp_in = comptime rpc_ts.tsForType(cm.CompleteInput);
    const comp_out = comptime rpc_ts.tsForType(cm.CompleteOutput);
    const init_has_input = cm.InitiateInput != void;
    const comp_has_input = cm.CompleteInput != void;

    // Interface member: <camel>: { initiate(...): Promise<...>; complete(...): Promise<...>; };
    try wi.appendSlice(a, try std.fmt.allocPrint(a, "      {s}: {{\n", .{camel}));
    if (init_has_input) {
        try wi.appendSlice(a, try std.fmt.allocPrint(a, "        initiate(input: {s}, opts?: SendOptions): Promise<{s}>;\n", .{ init_in, init_out }));
    } else {
        try wi.appendSlice(a, try std.fmt.allocPrint(a, "        initiate(opts?: SendOptions): Promise<{s}>;\n", .{init_out}));
    }
    if (comp_has_input) {
        try wi.appendSlice(a, try std.fmt.allocPrint(a, "        complete(input: {s}, opts?: SendOptions): Promise<{s}>;\n", .{ comp_in, comp_out }));
    } else {
        try wi.appendSlice(a, try std.fmt.allocPrint(a, "        complete(opts?: SendOptions): Promise<{s}>;\n", .{comp_out}));
    }
    try wi.appendSlice(a, "      };\n");

    // Factory member — explicit send<T> type arg so the literal is assignable to the iface.
    try wf.appendSlice(a, try std.fmt.allocPrint(a, "        {s}: {{\n", .{camel}));
    if (init_has_input) {
        try wf.appendSlice(a, try std.fmt.allocPrint(a,
            \\          initiate: (input: {0s}, opts?: SendOptions): Promise<{1s}> =>
            \\            base.send<{1s}>("POST", `{2s}/collections/{3s}/auth/{4s}/initiate`, {{ body: input, ...opts }}),
            \\
        , .{ init_in, init_out, prefix, col_name, slug }));
    } else {
        try wf.appendSlice(a, try std.fmt.allocPrint(a,
            \\          initiate: (opts?: SendOptions): Promise<{0s}> =>
            \\            base.send<{0s}>("POST", `{1s}/collections/{2s}/auth/{3s}/initiate`, {{ ...opts }}),
            \\
        , .{ init_out, prefix, col_name, slug }));
    }
    if (comp_has_input) {
        try wf.appendSlice(a, try std.fmt.allocPrint(a,
            \\          complete: (input: {0s}, opts?: SendOptions): Promise<{1s}> =>
            \\            base.send<{1s}>("POST", `{2s}/collections/{3s}/auth/{4s}/complete`, {{ body: input, ...opts }}),
            \\
        , .{ comp_in, comp_out, prefix, col_name, slug }));
    } else {
        try wf.appendSlice(a, try std.fmt.allocPrint(a,
            \\          complete: (opts?: SendOptions): Promise<{0s}> =>
            \\            base.send<{0s}>("POST", `{1s}/collections/{2s}/auth/{3s}/complete`, {{ ...opts }}),
            \\
        , .{ comp_out, prefix, col_name, slug }));
    }
    try wf.appendSlice(a, "        },\n");
}

/// Mirror of emit.zig's hasSingleFileFields: the per-collection fileUrl graft is
/// only valid for single-value file fields (a multi-value file field is string[]
/// on the record and can't be passed as a single filename). Collections whose only
/// file fields are multi-value fall through to the plain makeRecordService path.
fn emit_hasSingleFileFields(c: schema.Collection) bool {
    const tt = @import("ts_type.zig");
    for (c.fields) |f| if (tt.kindOf(f) == .file_name and !f.isMultiValue()) return true;
    return false;
}

const Args = struct {
    out: ?[]const u8 = null,
    api_prefix: []const u8 = "/api",
    check: bool = false,
    /// Output language: "ts" (default) or "dart".
    lang: []const u8 = "ts",
    /// Kotlin-only: the `package` declaration emitted at the top of the generated
    /// file. Mirrors `typegen --package`. Defaults to the dating fixture's
    /// namespace so the committed golden and `zig build gen-dating-kotlin-client`
    /// stay byte-stable; a consumer's gen-client step passes `--package
    /// your.app` to target its own namespace instead of the unoverridable
    /// hardcode this used to bake in.
    kotlin_package: []const u8 = "io.github.valthon.zigbase.codegen.dating",
};

/// Parse CLI args from the Zig 0.16 argv slice ([]const [:0]const u8).
fn parseArgsSlice(alloc: std.mem.Allocator, argv: []const [:0]const u8) !Args {
    var args = Args{};
    var i: usize = 1; // skip exe name
    while (i < argv.len) : (i += 1) {
        const a = argv[i];
        if (std.mem.eql(u8, a, "--out")) {
            i += 1;
            if (i >= argv.len) return error.MissingOutValue;
            args.out = try alloc.dupe(u8, argv[i]);
        } else if (std.mem.eql(u8, a, "--api-prefix")) {
            i += 1;
            if (i >= argv.len) return error.MissingApiPrefixValue;
            args.api_prefix = try alloc.dupe(u8, argv[i]);
        } else if (std.mem.eql(u8, a, "--check")) {
            args.check = true;
        } else if (std.mem.eql(u8, a, "--lang")) {
            i += 1;
            if (i >= argv.len) return error.MissingLangValue;
            args.lang = try alloc.dupe(u8, argv[i]);
        } else if (std.mem.eql(u8, a, "--package")) {
            i += 1;
            if (i >= argv.len) return error.MissingPackageValue;
            args.kotlin_package = try alloc.dupe(u8, argv[i]);
        } else {
            std.log.warn("gen_client: ignoring unknown arg '{s}'", .{a});
        }
    }
    return args;
}

/// Pick the auth collection name (first auth collection).
fn authCollectionName(cols: []const schema.Collection) []const u8 {
    for (cols) |c| if (c.type == .auth) return c.name;
    return "";
}

/// Entry point: Zig 0.16 `pub fn main(init: std.process.Init) !void`.
/// Threads `init.io` (for file operations) and uses `init.gpa` for a local arena,
/// reads argv from `init.minimal.args.toSlice(arena)` (yields `[]const [:0]const u8`).
/// Reads the ZBASE_INREPO env flag via `init.environ_map` (Zig 0.16's pure-Zig env
/// access through `std.process.Environ.Map` — no `std.c.getenv`, so this code adds no
/// libc dependency of its own).
///
/// NOTE (Task 7): In Zig 0.16, a file can only belong to one module. gen_client.zig
/// uses relative imports (@import("../schema.zig") etc.) which claim those files for
/// THIS module. If gen_client.zig is used as the exe module root AND zigbase is in
/// the dependency graph (via the `app` module), those files would be double-claimed.
/// The solution: use gen_main.zig as the exe root (which imports "zigbase" and "app"
/// as named modules) and call mainWithCollections() here. This keeps gen_client.zig
/// as a self-contained library file usable by the zigbase test suite WITHOUT being
/// a module root.
pub fn mainWithCollections(init: std.process.Init, cols: []const schema.Collection, comptime routes: []const events.RouteMeta, comptime custom_auth: []const events.CustomAuthMeta, flags: []const features.FlagDef, experiments: []const features.ExperimentDef) !void {
    const io = init.io;
    // Use an arena for all temporary allocations during the generator run.
    var arena_state = std.heap.ArenaAllocator.init(init.gpa);
    defer arena_state.deinit();
    const a = arena_state.allocator();

    // argv: []const [:0]const u8 (Zig 0.16 — init.minimal.args.toSlice returns this).
    const argv = try init.minimal.args.toSlice(a);
    const args = try parseArgsSlice(a, argv);
    const out_path = args.out orelse {
        std.log.err("gen_client: --out <path> is required", .{});
        return error.MissingOut;
    };

    // ZBASE_INREPO: read via init.environ_map (Zig 0.16 pure-Zig env access; no libc).
    // contains() means the var is set (value may be empty string — that's fine).
    const in_repo = init.environ_map.contains("ZBASE_INREPO");
    const client_name = "ZbClient";
    const want_dart = std.mem.eql(u8, args.lang, "dart");
    const want_python = std.mem.eql(u8, args.lang, "python");
    const want_kotlin = std.mem.eql(u8, args.lang, "kotlin");
    if (!want_dart and !want_python and !want_kotlin and !std.mem.eql(u8, args.lang, "ts")) {
        std.log.err("gen_client: unknown --lang '{s}' (expected 'ts', 'dart', 'python', or 'kotlin')", .{args.lang});
        return error.BadLang;
    }

    const text = (if (want_dart)
        gen_dart.generate(a, cols, routes, custom_auth, flags, experiments, in_repo, authCollectionName(cols), client_name, args.api_prefix)
    else if (want_python)
        gen_python.generate(a, cols, routes, custom_auth, flags, experiments, in_repo, authCollectionName(cols), client_name, args.api_prefix)
    else if (want_kotlin)
        gen_kotlin.generate(a, cols, routes, custom_auth, flags, experiments, in_repo, authCollectionName(cols), client_name, args.api_prefix, args.kotlin_package)
    else
        generate(a, cols, routes, custom_auth, flags, experiments, in_repo, authCollectionName(cols), client_name, args.api_prefix)) catch |e| {
        // guard messages are printed via the report; re-run path for the message:
        var report = guards.GuardReport{ .message = "" };
        guards.checkOperatorNames(a, cols, &report) catch {};
        guards.checkIdentifiers(a, cols, &report) catch {};
        if (report.message.len > 0) std.log.err("{s}", .{report.message});
        return e;
    };

    if (args.check) {
        // Zig 0.16 file-read: std.Io.Dir.cwd().readFileAlloc(io, path, alloc, .limited(N))
        const existing = std.Io.Dir.cwd().readFileAlloc(io, out_path, a, .limited(64 * 1024 * 1024)) catch |e| {
            std.log.err("gen_client --check: cannot read '{s}': {s}", .{ out_path, @errorName(e) });
            return error.CheckReadFailed;
        };
        if (!std.mem.eql(u8, existing, text)) {
            std.log.err("gen_client --check: '{s}' is STALE — re-run gen-client to regenerate.", .{out_path});
            return error.Stale;
        }
        return;
    }

    // Ensure the output directory exists.
    // Zig 0.16: std.Io.Dir.cwd().createDirPath(io, dir) — NOT makePath.
    if (std.fs.path.dirname(out_path)) |dir| {
        std.Io.Dir.cwd().createDirPath(io, dir) catch {};
    }
    // Zig 0.16 file-write: std.Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = bytes })
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = text });
    std.log.info("gen_client: wrote {s} ({d} bytes)", .{ out_path, text.len });
}

/// Legacy entry point kept for back-compat; reads @import("app").App.collections.
/// Prefer mainWithCollections when building as a separate module to avoid
/// the Zig 0.16 "file exists in multiple modules" error (see note above).
pub fn main(init: std.process.Init) !void {
    const app = @import("app");
    return mainWithCollections(init, app.App.collections, app.App.routes, app.App.custom_auth, app.App.flags, app.App.experiments);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

fn miniBlog(alloc: std.mem.Allocator) ![]const schema.Collection {
    const tags_f = try alloc.dupe(schema.Field, &.{.{ .id = "a", .name = "label", .required = true, .options = .{ .text = .{} } }});
    const users_f = try alloc.dupe(schema.Field, &.{.{ .id = "b", .name = "name", .options = .{ .text = .{} } }});
    const posts_f = try alloc.dupe(schema.Field, &.{
        .{ .id = "c", .name = "title", .required = true, .options = .{ .text = .{} } },
        .{ .id = "d", .name = "status", .options = .{ .select = .{ .values = &.{ "draft", "published" }, .maxSelect = 1 } } },
        .{ .id = "e", .name = "author", .options = .{ .relation = .{ .targetCollectionId = "users", .maxSelect = 1 } } },
        .{ .id = "f", .name = "tags", .options = .{ .relation = .{ .targetCollectionId = "tags", .maxSelect = 99 } } },
        .{ .id = "g", .name = "cover", .options = .{ .file = .{ .maxSelect = 1 } } },
    });
    return try alloc.dupe(schema.Collection, &.{
        .{ .id = "", .name = "posts", .fields = posts_f },
        .{ .id = "", .name = "users", .type = .auth, .fields = users_f },
        .{ .id = "", .name = "tags", .fields = tags_f },
    });
}

test "generate emits a parseable file with the expected top-level constructs" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const out = try generate(a, cols, &.{}, &.{}, &.{}, &.{}, true, "users", "BlogClient", "/api");
    try std.testing.expect(std.mem.startsWith(u8, out, "// generated by zigbase — do not edit\n// schema-hash: "));
    inline for (.{
        "export interface Post {",                    "export type PostStatus =",
        "export interface PostCreate {",              "export type PostUpdate =",
        "export interface PostWhere {",               "export type PostRelations =",
        "export type PostExpand =",                   "export interface PostFields {",
        "export interface PostsService {",            "export const postsMeta: CollectionMeta = {",
        "const relationResolver: RelationResolver =", "export type PostsRealtime = RawTypedRealtime<Post, PostWhere>;",
        "export interface BlogClient {",              "export function createClient(",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, out, needle) != null);
}

test "schemaHash is deterministic + order-sensitive" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    try std.testing.expectEqual(schemaHash(cols), schemaHash(cols));
    // mutating a field name changes the hash
    var cols2 = try a.dupe(schema.Collection, cols);
    var f2 = try a.dupe(schema.Field, cols2[0].fields);
    f2[0].name = "headline";
    cols2[0].fields = f2;
    try std.testing.expect(schemaHash(cols) != schemaHash(cols2));
}

test "--check diff: stale buffer differs from fresh output" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const fresh = try generate(a, cols, &.{}, &.{}, &.{}, &.{}, true, "users", "BlogClient", "/api");
    const stale = try std.fmt.allocPrint(a, "{s}\n// drift\n", .{fresh});
    try std.testing.expect(!std.mem.eql(u8, fresh, stale)); // --check would exit non-zero
    try std.testing.expect(std.mem.eql(u8, fresh, fresh)); // --check would exit zero
}

test "guards run inside generate: operator-named relation target errors" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const tag_f = try a.dupe(schema.Field, &.{.{ .id = "x", .name = "in", .options = .{ .text = .{} } }});
    const post_f = try a.dupe(schema.Field, &.{.{ .id = "y", .name = "labels", .options = .{ .relation = .{ .targetCollectionId = "tags" } } }});
    const cols = try a.dupe(schema.Collection, &.{
        .{ .id = "", .name = "tags", .fields = tag_f },
        .{ .id = "", .name = "posts", .fields = post_f },
    });
    try std.testing.expectError(guards.GuardError.OperatorNameClash, generate(a, cols, &.{}, &.{}, &.{}, &.{}, true, "", "ZbClient", "/api"));
}

test "auth-method endpoints: magic_link emits TYPED initiate/complete; password emits nothing" {
    // Verifies that emitAuthMethodEndpoints generates TYPED initiate/complete for built-ins.
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    // An auth collection with magic_link enabled.
    const members_cols = try a.dupe(schema.Collection, &.{
        .{
            .id = "",
            .name = "members",
            .type = .auth,
            .fields = &.{},
            .options = .{ .auth = .{ .methods = .{ .magic_link = .{} } } },
        },
    });
    const out_ml = try generate(a, members_cols, &.{}, &.{}, &.{}, &.{}, true, "members", "MembersClient", "/api");
    // Should contain magic_link initiate + complete paths
    try std.testing.expect(std.mem.indexOf(u8, out_ml, "/auth/magic_link/initiate") != null);
    try std.testing.expect(std.mem.indexOf(u8, out_ml, "/auth/magic_link/complete") != null);
    // Should contain the camelCase method name
    try std.testing.expect(std.mem.indexOf(u8, out_ml, "magicLink") != null);
    // Typed I/O: shared interfaces emitted + referenced (no untyped Record stub).
    inline for (.{
        "export interface AuthMethodResult {",
        "export interface MagicLinkInitiateInput {",
        "export interface MagicLinkCompleteInput {",
        "initiate(input: MagicLinkInitiateInput, opts?: SendOptions): Promise<void>;",
        "complete(input: MagicLinkCompleteInput, opts?: SendOptions): Promise<AuthMethodResult>;",
        "base.send<AuthMethodResult>(\"POST\", `/api/collections/members/auth/magic_link/complete`",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, out_ml, needle) != null);
    // Built-ins must NOT carry the untyped stub.
    try std.testing.expect(std.mem.indexOf(u8, out_ml, "Record<string, unknown>") == null);

    // An auth collection with ONLY password — no non-password stubs.
    const pw_cols = try a.dupe(schema.Collection, &.{
        .{
            .id = "",
            .name = "users",
            .type = .auth,
            .fields = &.{},
            .options = .{ .auth = .{ .methods = .{ .password = .{} } } },
        },
    });
    const out_pw = try generate(a, pw_cols, &.{}, &.{}, &.{}, &.{}, true, "users", "UsersClient", "/api");
    // Should NOT contain any /auth/password/ URL stubs
    try std.testing.expect(std.mem.indexOf(u8, out_pw, "/auth/password/") == null);
    // Should NOT contain an auth namespace on the client interface
    try std.testing.expect(std.mem.indexOf(u8, out_pw, "auth: {") == null);
    // No auth methods ⇒ none of the shared built-in I/O interfaces are emitted.
    try std.testing.expect(std.mem.indexOf(u8, out_pw, "export interface AuthMethodResult") == null);
}

test "auth-method endpoints: otp + webauthn emit precise typed I/O" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const cols = try a.dupe(schema.Collection, &.{
        .{
            .id = "",
            .name = "users",
            .type = .auth,
            .fields = &.{},
            .options = .{ .auth = .{ .methods = .{
                .otp = .{},
                .webauthn = .{ .rp_id = "x.test", .origin = "https://x.test" },
            } } },
        },
    });
    const out = try generate(a, cols, &.{}, &.{}, &.{}, &.{}, true, "users", "UsersClient", "/api");
    inline for (.{
        // OTP typed I/O
        "export interface OtpInitiateInput {",
        "export interface OtpCompleteInput {",
        "initiate(input: OtpInitiateInput, opts?: SendOptions): Promise<void>;",
        "complete(input: OtpCompleteInput, opts?: SendOptions): Promise<AuthMethodResult>;",
        "  code: string;",
        // WebAuthn typed I/O — initiate returns a structured challenge, not void.
        "export interface WebAuthnInitiateInput {",
        "export interface WebAuthnInitiateResult {",
        "export interface WebAuthnCompleteInput {",
        "initiate(input: WebAuthnInitiateInput, opts?: SendOptions): Promise<WebAuthnInitiateResult>;",
        "complete(input: WebAuthnCompleteInput, opts?: SendOptions): Promise<AuthMethodResult>;",
        "  ceremonyId: string;",
        "  challenge: string;",
        "  rpId: string;",
        "  timeout: number;",
        "  credentialId: string;",
        "  signature: string;",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, out, needle) != null);
    // No built-in carries the untyped stub.
    try std.testing.expect(std.mem.indexOf(u8, out, "Record<string, unknown>") == null);
}

test "auth-method endpoints: custom slugs stay untyped with a follow-up TODO" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const cols = try a.dupe(schema.Collection, &.{
        .{
            .id = "",
            .name = "users",
            .type = .auth,
            .fields = &.{},
            .options = .{ .auth = .{ .methods = .{ .custom = &.{"my_method"} } } },
        },
    });
    // Back-compat: a bare-string slug stays UNTYPED even with the comptime custom-auth
    // channel present (here empty) — exactly the pre-#119 behavior.
    const out = try generate(a, cols, &.{}, &.{}, &.{}, &.{}, true, "users", "UsersClient", "/api");
    // Custom slug present + camelCased.
    try std.testing.expect(std.mem.indexOf(u8, out, "/auth/my_method/initiate") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "myMethod") != null);
    // Custom methods keep the untyped stub + the precise follow-up TODO.
    try std.testing.expect(std.mem.indexOf(u8, out, "initiate(input: Record<string, unknown>, opts?: SendOptions): Promise<unknown>;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "comptime typed-I/O declaration API") != null);
    // No built-in I/O interfaces are emitted when only custom methods exist.
    try std.testing.expect(std.mem.indexOf(u8, out, "export interface AuthMethodResult") == null);
}

test "auth-method endpoints: custom methods with declared I/O emit typed interfaces" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    // Two custom methods on `users`: one with full typed initiate+complete, and one
    // bare-string slug that must STILL be untyped even alongside the typed channel.
    const SsoInitiateReq = struct { redirect: []const u8 };
    const SsoInitiateResp = struct { authorizeUrl: []const u8 };
    const SsoCompleteReq = struct { code: []const u8, state: []const u8 };
    const SsoCompleteResp = struct { token: []const u8 };

    const cols = try a.dupe(schema.Collection, &.{
        .{
            .id = "",
            .name = "users",
            .type = .auth,
            .fields = &.{},
            // Runtime slug list carries BOTH slugs (lowering is slug-only).
            .options = .{ .auth = .{ .methods = .{ .custom = &.{ "corp_sso", "legacy" } } } },
        },
    });
    // Comptime channel: only `corp_sso` is typed; `legacy` is absent → stays untyped.
    const custom_auth = [_]events.CustomAuthMeta{.{
        .col_name = "users",
        .slug = "corp_sso",
        .InitiateInput = SsoInitiateReq,
        .InitiateOutput = SsoInitiateResp,
        .CompleteInput = SsoCompleteReq,
        .CompleteOutput = SsoCompleteResp,
    }};
    const out = try generate(a, cols, &.{}, &custom_auth, &.{}, &.{}, true, "users", "UsersClient", "/api");

    // Named interfaces emitted (by the Zig type's own short name).
    inline for (.{
        "export interface SsoInitiateReq {",
        "export interface SsoInitiateResp {",
        "export interface SsoCompleteReq {",
        "export interface SsoCompleteResp {",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, out, needle) != null);

    // Typed initiate/complete signatures + URLs for the typed method.
    try std.testing.expect(std.mem.indexOf(u8, out, "initiate(input: SsoInitiateReq, opts?: SendOptions): Promise<SsoInitiateResp>;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "complete(input: SsoCompleteReq, opts?: SendOptions): Promise<SsoCompleteResp>;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "base.send<SsoCompleteResp>(\"POST\", `/api/collections/users/auth/corp_sso/complete`") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "corpSso") != null);

    // The bare-string `legacy` slug remains untyped (the Record stub still appears).
    try std.testing.expect(std.mem.indexOf(u8, out, "/auth/legacy/initiate") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "Record<string, unknown>") != null);
}

test "auth-method endpoints: custom method void I/O omits input arg and returns Promise<void>" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const TokenResp = struct { token: []const u8 };
    const cols = try a.dupe(schema.Collection, &.{
        .{
            .id = "",
            .name = "users",
            .type = .auth,
            .fields = &.{},
            .options = .{ .auth = .{ .methods = .{ .custom = &.{"api_token"} } } },
        },
    });
    // void initiate input + void initiate output; void complete input, typed output.
    const custom_auth = [_]events.CustomAuthMeta{.{
        .col_name = "users",
        .slug = "api_token",
        .CompleteOutput = TokenResp,
    }};
    const out = try generate(a, cols, &.{}, &custom_auth, &.{}, &.{}, true, "users", "UsersClient", "/api");

    // void input → no `input` arg; void output → Promise<void>.
    try std.testing.expect(std.mem.indexOf(u8, out, "initiate(opts?: SendOptions): Promise<void>;") != null);
    // void complete input but typed output.
    try std.testing.expect(std.mem.indexOf(u8, out, "complete(opts?: SendOptions): Promise<TokenResp>;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "export interface TokenResp {") != null);
    // Typed method must NOT fall back to the untyped Record stub.
    try std.testing.expect(std.mem.indexOf(u8, out, "Record<string, unknown>") == null);
}

test "feature state: typed zb.flags.resolveAll emits named booleans + variant unions (#130)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);

    const flags = [_]features.FlagDef{
        .{ .name = "checkout_enabled", .default = true },
        .{ .name = "new_dashboard", .default = false },
    };
    const experiments = [_]features.ExperimentDef{
        .{ .name = "checkout_layout", .variants = &.{ "control", "compact" }, .weights = &.{ 50, 50 } },
    };
    const out = try generate(a, cols, &.{}, &.{}, &flags, &experiments, true, "users", "ZbClient", "/api");

    // Named FeatureState type: flags as booleans, experiment as a string-literal union.
    inline for (.{
        "export interface FeatureState {",
        "    checkout_enabled: boolean;",
        "    new_dashboard: boolean;",
        "    checkout_layout: \"control\" | \"compact\";",
        // Client interface member + factory member targeting GET <prefix>/state.
        "  flags: {",
        "    resolveAll(subject: string): Promise<FeatureState>;",
        "base.send<FeatureState>(\"GET\", `/api/state?subject=${encodeURIComponent(subject)}`)",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, out, needle) != null);
}

test "feature state: surface is omitted when no flags/experiments are declared" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const out = try generate(a, cols, &.{}, &.{}, &.{}, &.{}, true, "users", "ZbClient", "/api");
    try std.testing.expect(std.mem.indexOf(u8, out, "FeatureState") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "resolveAll(subject") == null);
}

test "feature state: flags-only app yields Record<string, never> experiments" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const flags = [_]features.FlagDef{.{ .name = "promo_banner", .default = false }};
    const out = try generate(a, cols, &.{}, &.{}, &flags, &.{}, true, "users", "ZbClient", "/api");
    try std.testing.expect(std.mem.indexOf(u8, out, "    promo_banner: boolean;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "  experiments: Record<string, never>;") != null);
}

test "schemaHash changes when searchable or tenant_field toggles" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const base = schemaHash(cols);
    // Toggle searchable on one field.
    var cols2 = try a.dupe(schema.Collection, cols);
    var f2 = try a.dupe(schema.Field, cols2[0].fields);
    f2[0].searchable = true;
    cols2[0].fields = f2;
    try std.testing.expect(base != schemaHash(cols2));
    // Set a tenant field.
    var cols3 = try a.dupe(schema.Collection, cols);
    cols3[0].options.tenant_field = "account";
    try std.testing.expect(base != schemaHash(cols3));
}

test "generate emits sort unions, the _RequiresCore guard, and SortExpr/RecordAbilities imports" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const out = try generate(a, cols, &.{}, &.{}, &.{}, &.{}, true, "users", "BlogClient", "/api");
    inline for (.{
        "export type PostSortField =",
        "export type PostSort = SortExpr<PostSortField>;",
        "export type _RequiresCore = import(\"../../../src/typed/index.js\").CoreSupports_0_3;",
        "type SortExpr,",
        "type RecordAbilities",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, out, needle) != null);
    // Non-in-repo emission uses the package path.
    const pkg = try generate(a, cols, &.{}, &.{}, &.{}, &.{}, false, "users", "BlogClient", "/api");
    try std.testing.expect(std.mem.indexOf(u8, pkg, "export type _RequiresCore = import(\"@zigbase/client/typed\").CoreSupports_0_3;") != null);
}

test "generated client wires accounts/analytics/senders/withAccount" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = try miniBlog(a);
    const out = try generate(a, cols, &.{}, &.{}, &.{}, &.{}, true, "users", "BlogClient", "/api");
    inline for (.{
        // interface members (indexed-access types keep the import surface small)
        "  accounts: Client[\"accounts\"];",
        "  analytics: Client[\"analytics\"];",
        "  senders: Client[\"senders\"];",
        "  withAccount(accountId: string): BlogClient;",
        // factory: createClient delegates to a rebuildable makeClient
        "return makeClient(base);",
        "function makeClient(base: RealtimeEnabledClient): BlogClient {",
        "    accounts: base.accounts,",
        "    analytics: base.analytics,",
        "    senders: base.senders,",
        "    withAccount: (accountId: string): BlogClient => makeClient(withRealtime(base.withAccount(accountId))),",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, out, needle) != null);
}

test "customAuthMeta reflects struct entries and skips bare strings" {
    const Req = struct { x: i32 };
    const meta = comptime events.customAuthMeta(.{
        .users = .{
            .type = .auth,
            .auth = .{ .methods = .{ .custom = .{
                "bare_slug",
                .{ .slug = "typed", .Complete = .{ .Input = Req } },
            } } },
        },
        .posts = .{ .fields = .{} }, // non-auth collection → ignored
    });
    try std.testing.expectEqual(@as(usize, 1), meta.len);
    try std.testing.expectEqualStrings("users", meta[0].col_name);
    try std.testing.expectEqualStrings("typed", meta[0].slug);
    try std.testing.expectEqual(void, meta[0].InitiateInput); // default
    try std.testing.expectEqual(Req, meta[0].CompleteInput);
    try std.testing.expectEqual(void, meta[0].CompleteOutput); // default
}
