//! Pure-Zig Python client generator: collections -> a zbase_gen.py that
//! instantiates the runtime in clients/python/src/zigbase/typed.py (imported
//! as `zbt`) into concrete pydantic BaseModel classes, fluent field builders,
//! per-collection metadata, sync/async typed services, realtime subclasses,
//! and the `ZbClient`/`AsyncZbClient` façades. The Python counterpart of
//! gen_dart.generate; shares the acquisition layer and the guard bar
//! (guards.checkIdentifiers), and branches only in emission. NB: that guard bar
//! is TS-derived (TS identifier validity + the TS typed-core reserved-name set),
//! applied to every language as a conservative lowest common denominator — NOT a
//! language-neutral check. The Python-specific keyword/member sanitizing that
//! keeps THIS output legal lives in emit_python.zig.
const std = @import("std");
const schema = @import("../schema.zig");
const events = @import("../events.zig");
const features = @import("../features.zig");
const emit = @import("emit_python.zig");
const guards = @import("guards.zig");
const ident = @import("identifiers.zig");
const gen_client = @import("gen_client.zig");

const W = std.ArrayList(u8);

/// The `zigbase.typed.TYPED_CORE_VERSION` value this emitter targets — a
/// human/tooling compatibility marker in the generated header, matching the
/// literal in clients/python/src/zigbase/typed.py. Not read across the
/// language boundary at build time; keep the two in sync by hand.
const TYPED_CORE_VERSION = "0.1.0";

fn section(alloc: std.mem.Allocator, w: *W, title: []const u8) !void {
    const line = try std.fmt.allocPrint(alloc, "\n# ---- {s} " ++ ("-" ** 4) ++ "\n\n", .{title});
    try w.appendSlice(alloc, line);
}

/// The pure Python generator core: collections -> full file text.
///
/// Signature mirrors gen_dart.generate/gen_client.generate so the CLI/build
/// threading is uniform. `routes`, `custom_auth`, `flags`, `experiments`
/// (the comptime-only surfaces) are accepted for parity but not yet emitted
/// in Python — a documented follow-up, same as Dart. `in_repo` is unused
/// (the snapshot lives inside the client package, so the package import works).
pub fn generate(
    alloc: std.mem.Allocator,
    cols: []const schema.Collection,
    comptime routes: []const events.RouteMeta,
    comptime custom_auth: []const events.CustomAuthMeta,
    flags: []const features.FlagDef,
    experiments: []const features.ExperimentDef,
    in_repo: bool,
    auth_collection: []const u8,
    client_name: []const u8,
    api_prefix: []const u8,
) ![]const u8 {
    _ = routes;
    _ = custom_auth;
    _ = flags;
    _ = experiments;
    _ = in_repo;
    _ = api_prefix;

    var report = guards.GuardReport{ .message = "" };
    try guards.checkOperatorNames(alloc, cols, &report);
    try guards.checkIdentifiers(alloc, cols, &report);

    const needs_enum = emit.anySelectFields(cols);
    const needs_file = emit.anyFileFields(cols);
    const needs_auth = emit.anyAuthCollections(cols);

    var w: W = .empty;
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        \\# GENERATED by zigbase — do not edit.
        \\# schema-hash: {x:0>16}
        \\# typed-core-version: {s}
        \\#
        \\# A thin, schema-aware wrapper over the base Python SDK's generic typed
        \\# runtime (zigbase.typed, imported below as `zbt`). Regenerate with your
        \\# server's `typegen --lang python` command (or the build-time comptime
        \\# gen-client build step), then `ruff format` it with your project's config.
        \\#
        \\# Identifier mapping: a schema name that is a Python keyword gets a
        \\# trailing `_` on the PYTHON side only (field `class` -> member
        \\# `class_`); wire keys are unchanged.
        \\# ruff: noqa
        \\from __future__ import annotations
        \\
        \\from collections.abc import AsyncIterator, Callable, Iterator, Mapping, Sequence
        \\
    , .{ gen_client.schemaHash(cols), TYPED_CORE_VERSION }));
    if (needs_enum) try w.appendSlice(alloc, "from enum import Enum\n");
    try w.appendSlice(alloc, "from typing import Any\n\nimport zigbase.typed as zbt\n");
    if (needs_auth) {
        try w.appendSlice(alloc, "from zigbase import AsyncZigBase, AuthResponse, AuthStore, ZigBase\n");
    } else {
        try w.appendSlice(alloc, "from zigbase import AsyncZigBase, AuthStore, ZigBase\n");
    }
    if (needs_file) {
        try w.appendSlice(alloc, "from pydantic import BaseModel, ConfigDict\n");
        try w.appendSlice(alloc, "\nfrom zigbase._multipart import FileArg\n");
    } else {
        try w.appendSlice(alloc, "from pydantic import BaseModel\n");
    }

    try section(alloc, &w, "Records");
    for (cols) |c| try emit.emitSelectEnums(alloc, &w, c);
    for (cols) |c| try emit.emitRecord(alloc, &w, cols, c);

    try section(alloc, &w, "Create / Update payloads");
    for (cols) |c| {
        try emit.emitCreate(alloc, &w, c);
        try emit.emitUpdate(alloc, &w, c);
    }

    try section(alloc, &w, "Fluent field builders");
    for (cols) |c| try emit.emitFields(alloc, &w, cols, c);

    try section(alloc, &w, "Per-collection metadata");
    for (cols) |c| try emit.emitMeta(alloc, &w, c);

    try section(alloc, &w, "Typed services");
    for (cols) |c| {
        try emit.emitService(alloc, &w, cols, c);
        try emit.emitAsyncService(alloc, &w, cols, c);
    }

    try section(alloc, &w, "Typed realtime");
    for (cols) |c| try emit.emitRealtime(alloc, &w, c);

    try section(alloc, &w, "Client");
    try emit.emitClient(alloc, &w, cols, client_name, auth_collection);
    try emit.emitAsyncClient(alloc, &w, cols, client_name, auth_collection);

    return w.toOwnedSlice(alloc);
}

test "generate emits a valid-looking Python client for a mini blog" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = [_]schema.Collection{
        .{ .id = "", .name = "users", .type = .auth, .fields = &.{
            .{ .id = "", .name = "displayName", .options = .{ .text = .{} } },
        } },
        .{ .id = "", .name = "posts", .fields = &.{
            .{ .id = "", .name = "title", .required = true, .options = .{ .text = .{} } },
            .{ .id = "", .name = "status", .options = .{ .select = .{ .values = &.{ "draft", "published" }, .maxSelect = 1 } } },
            .{ .id = "", .name = "views", .options = .{ .number = .{ .mode = .int } } },
            .{ .id = "", .name = "author", .options = .{ .relation = .{ .targetCollectionId = "users", .maxSelect = 1 } } },
            .{ .id = "", .name = "cover", .options = .{ .file = .{ .maxSelect = 1 } } },
        } },
    };
    const out = try generate(a, &cols, &.{}, &.{}, &.{}, &.{}, true, "users", "ZbClient", "/api");

    // Byte-exact fragment: the enum class in full (Step 1's "byte-exact
    // expected fragment for one small collection").
    const expected_enum =
        \\class PostStatus(str, Enum):
        \\    DRAFT = "draft"
        \\    PUBLISHED = "published"
        \\
        \\    @classmethod
        \\    def from_wire(cls, v: object) -> PostStatus | None:
        \\        for e in cls:
        \\            if e.value == v:
        \\                return e
        \\        return None
        \\
        \\
    ;
    try std.testing.expect(std.mem.indexOf(u8, out, expected_enum) != null);

    // Spot-check the remaining key generated shapes.
    try std.testing.expect(std.mem.indexOf(u8, out, "class Post(BaseModel):") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "views: int") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "views=zbt.coerce_int(r.get(\"views\")),") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class PostExpand(BaseModel):") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "author=zbt.expand_one(r, \"author\", User.from_record),") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class PostCreate(BaseModel):") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class PostUpdate(BaseModel):") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "cover: FileArg | None = None") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "model_config = ConfigDict(arbitrary_types_allowed=True)") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "from zigbase._multipart import FileArg") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "from enum import Enum") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "import zigbase.typed as zbt") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "# ruff: noqa") != null);
}

test "Python keywords are sanitized (wire keys unchanged)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = [_]schema.Collection{
        .{ .id = "", .name = "users", .type = .auth, .fields = &.{} },
        // `class`/`import` are Python keywords; `expand` collides with the
        // generated record member; select value `class` is a keyword-derived
        // enum member (sanitized only after the uppercase transform, which
        // never itself collides — this exercises the general path anyway).
        .{ .id = "", .name = "raw", .fields = &.{
            .{ .id = "", .name = "class", .required = true, .options = .{ .text = .{} } },
            .{ .id = "", .name = "import", .options = .{ .number = .{ .mode = .int } } },
            .{ .id = "", .name = "expand", .options = .{ .text = .{} } },
            .{ .id = "", .name = "author", .options = .{ .relation = .{ .targetCollectionId = "users", .maxSelect = 1 } } },
        } },
    };
    const out = try generate(a, &cols, &.{}, &.{}, &.{}, &.{}, true, "users", "ZbClient", "/api");
    // Record members: keyword-sanitized Python identifier, wire key untouched.
    try std.testing.expect(std.mem.indexOf(u8, out, "class_: str") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "import_: int") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "expand_: str") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class_=zbt.coerce_str(r.get(\"class\")),") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "import_=zbt.coerce_int(r.get(\"import\")),") != null);
    // No unsanitized keyword member leaked.
    try std.testing.expect(std.mem.indexOf(u8, out, "class: str") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "import: int") == null);
    // Payload: required field + to_map keeps the wire key.
    try std.testing.expect(std.mem.indexOf(u8, out, "class_: str\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "m[\"class\"] = self.class_") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "m[\"import\"] = zbt.encode_int(self.import_)") != null);
}

test "generate emits fields builder, meta, service, realtime and client fragments (byte-exact)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = [_]schema.Collection{
        .{ .id = "", .name = "users", .type = .auth, .fields = &.{
            .{ .id = "", .name = "displayName", .options = .{ .text = .{} } },
        } },
        .{ .id = "", .name = "posts", .fields = &.{
            .{ .id = "", .name = "title", .required = true, .options = .{ .text = .{} } },
            .{ .id = "", .name = "status", .options = .{ .select = .{ .values = &.{ "draft", "published" }, .maxSelect = 1 } } },
            .{ .id = "", .name = "views", .options = .{ .number = .{ .mode = .int } } },
            .{ .id = "", .name = "author", .options = .{ .relation = .{ .targetCollectionId = "users", .maxSelect = 1 } } },
            .{ .id = "", .name = "cover", .options = .{ .file = .{ .maxSelect = 1 } } },
        } },
    };
    const out = try generate(a, &cols, &.{}, &.{}, &.{}, &.{}, true, "users", "ZbClient", "/api");

    // Byte-exact fragment: the fluent fields builder for `posts` in full —
    // covers every FieldExpr subclass (string/enum/num/relation) plus the
    // fixed id/created/updated trailer. Carry-forward from the T2 review:
    // every property instantiates a `zbt.*FieldExpr` DIRECTLY (no generated
    // subclass), so there is nothing here to rebind `__eq__`/`__ne__` on.
    const expected_fields =
        \\class PostFields:
        \\    def __init__(self, prefix: str = "") -> None:
        \\        self._p = prefix
        \\
        \\    @property
        \\    def title(self) -> zbt.StringFieldExpr:
        \\        return zbt.StringFieldExpr(f"{self._p}title")
        \\
        \\    @property
        \\    def status(self) -> zbt.EnumFieldExpr[PostStatus]:
        \\        return zbt.EnumFieldExpr(f"{self._p}status", wire_of=lambda e: e.value)
        \\
        \\    @property
        \\    def views(self) -> zbt.NumFieldExpr:
        \\        return zbt.NumFieldExpr(f"{self._p}views")
        \\
        \\    @property
        \\    def author(self) -> zbt.RelFieldExpr[UserFields]:
        \\        return zbt.RelFieldExpr(f"{self._p}author", lambda p: UserFields(p))
        \\
        \\    @property
        \\    def id(self) -> zbt.StringFieldExpr:
        \\        return zbt.StringFieldExpr(f"{self._p}id")
        \\
        \\    @property
        \\    def created(self) -> zbt.StringFieldExpr:
        \\        return zbt.StringFieldExpr(f"{self._p}created")
        \\
        \\    @property
        \\    def updated(self) -> zbt.StringFieldExpr:
        \\        return zbt.StringFieldExpr(f"{self._p}updated")
        \\
        \\
    ;
    try std.testing.expect(std.mem.indexOf(u8, out, expected_fields) != null);

    // Byte-exact fragment: the sync service's constructor + getList entry
    // point — covers the `<col>_meta`/`TypedCollection` wiring and the
    // where-lambda-compiles-to-filter pattern every query method shares.
    const expected_service_head =
        \\class PostsService:
        \\    def __init__(self, client: ZigBase) -> None:
        \\        self._c: zbt.TypedCollection[Post] = zbt.TypedCollection(client, posts_meta, Post.from_record)
        \\
        \\    def get_list(
        \\        self,
        \\        page: int = 1,
        \\        per_page: int = 30,
        \\        *,
        \\        where: Callable[[PostFields], zbt.Expr] | None = None,
        \\        sort: str | Sequence[str] | None = None,
        \\        expand: Sequence[str] | None = None,
        \\        fields: str | None = None,
        \\        skip_total: bool = False,
        \\        search: str | None = None,
        \\    ) -> zbt.TypedList[Post]:
        \\        return self._c.get_list(
        \\            page,
        \\            per_page,
        \\            filter=where(PostFields()).compile() if where else None,
        \\            sort=sort,
        \\            expand=expand,
        \\            fields=fields,
        \\            skip_total=skip_total,
        \\            search=search,
        \\        )
        \\
    ;
    try std.testing.expect(std.mem.indexOf(u8, out, expected_service_head) != null);

    // Byte-exact fragment: the async-only realtime subclass.
    const expected_realtime =
        \\class PostsRealtime(zbt.TypedRealtime[Post]):
        \\    def __init__(self, client: AsyncZigBase) -> None:
        \\        super().__init__(client, posts_meta, Post.from_record)
        \\
        \\
    ;
    try std.testing.expect(std.mem.indexOf(u8, out, expected_realtime) != null);

    // Spot-check the remaining key generated shapes.
    try std.testing.expect(std.mem.indexOf(u8, out, "posts_meta = zbt.CollectionMeta(") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "\"views\": zbt.FieldMeta(type=zbt.FieldType.NUMBER, mode=zbt.NumberMode.INTEGER),") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class AsyncPostsService:") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "self._c: zbt.AsyncTypedCollection[Post] = zbt.AsyncTypedCollection(") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "async def get_list(") != null);
    // `iterate` stays a plain (non-async) method even on the async service —
    // it returns an async generator object without itself needing `await`.
    try std.testing.expect(std.mem.indexOf(u8, out, "    def iterate(\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "def auth_with_password(self, identity: str, password: str) -> AuthResponse:") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class UsersFileField") == null); // users has no file field
    try std.testing.expect(std.mem.indexOf(u8, out, "class PostFileField(Enum):") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    COVER = \"cover\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "def file_url(") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "        if filename is None:\n            raise ValueError(f\"record has no value for file field '{field.value}'\")\n") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class ZbClient:") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "self.posts = PostsService(raw)") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class AsyncZbClient:") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "self.postsRealtime = PostsRealtime(raw)") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "async def aclose(self) -> None:") != null);
    try std.testing.expect(std.mem.indexOf(u8, out,
        \\def create_client(url: str, **kwargs: Any) -> ZbClient:
        \\    kwargs.setdefault("auth_collection", "users")
        \\    return ZbClient(ZigBase(url, **kwargs), owned=True)
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "from zigbase import AsyncZigBase, AuthResponse, AuthStore, ZigBase") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "from collections.abc import AsyncIterator, Callable, Iterator, Mapping, Sequence") != null);
}

test "select values differing only in case collide into one Python enum member — a generation error" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    // "active" and "ACTIVE" both uppercase to the enum member ACTIVE — the
    // second would silently overwrite the first's `= "active"` line with
    // `= "ACTIVE"` if generation didn't dedup-check before emitting.
    const cols = [_]schema.Collection{
        .{ .id = "", .name = "posts", .fields = &.{
            .{ .id = "", .name = "status", .options = .{ .select = .{ .values = &.{ "active", "ACTIVE" }, .maxSelect = 1 } } },
        } },
    };
    try std.testing.expectError(
        error.PythonIdentCollision,
        generate(a, &cols, &.{}, &.{}, &.{}, &.{}, true, "", "ZbClient", "/api"),
    );
}

test "file_url's Mapping branch uses .get() so an unrequested file field's key may be absent" {
    // No fixture collection in the repo (dating, blog, golfsim) has two
    // single-value file fields, so the golden-based Python behavior tests
    // can't exercise a Mapping missing one file field's key while carrying
    // another's -- this synthetic two-file-field collection is the only
    // place that shape is covered. Regression guard for the KeyError bug: a
    // dict literal's entries are all evaluated eagerly, so bracket-indexing
    // (`record["thumbnail"]`) would raise KeyError building the `filename =
    // {...}` dict for a caller's Mapping that only carries `cover` (e.g. a
    // partial realtime payload), even though only `cover` is ever selected
    // via `[field]`.
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = [_]schema.Collection{
        .{ .id = "", .name = "posts", .fields = &.{
            .{ .id = "", .name = "cover", .options = .{ .file = .{ .maxSelect = 1 } } },
            .{ .id = "", .name = "thumbnail", .options = .{ .file = .{ .maxSelect = 1 } } },
        } },
    };
    const out = try generate(a, &cols, &.{}, &.{}, &.{}, &.{}, true, "", "ZbClient", "/api");

    try std.testing.expect(std.mem.indexOf(u8, out, "class PostFileField(Enum):") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    COVER = \"cover\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    THUMBNAIL = \"thumbnail\"") != null);
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "            PostFileField.COVER: record.get(\"cover\") if isinstance(record, Mapping) else record.cover,\n",
    ) != null);
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "            PostFileField.THUMBNAIL: record.get(\"thumbnail\") if isinstance(record, Mapping) else record.thumbnail,\n",
    ) != null);
    // No bracket-indexed lookup anywhere in the filename dict (that's the
    // KeyError-on-partial-Mapping bug this test guards against).
    try std.testing.expect(std.mem.indexOf(u8, out, "record[\"cover\"]") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "record[\"thumbnail\"]") == null);
}

test "two schema names mapping to one Python identifier is a generation error" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = [_]schema.Collection{
        .{ .id = "", .name = "posts", .fields = &.{
            .{ .id = "", .name = "class", .options = .{ .text = .{} } },
            .{ .id = "", .name = "class_", .options = .{ .text = .{} } },
        } },
    };
    try std.testing.expectError(
        error.PythonIdentCollision,
        generate(a, &cols, &.{}, &.{}, &.{}, &.{}, true, "", "ZbClient", "/api"),
    );
}
