//! Pure-Zig Dart client generator: collections -> a zbase.gen.dart that
//! instantiates the runtime in clients/dart/lib/typed.dart into concrete typed
//! classes. The Dart counterpart of gen_client.generate; shares the acquisition
//! layer and the guard bar (guards.checkIdentifiers), and branches only in
//! emission. NB: that guard bar is TS-derived (TS identifier validity + the TS
//! typed-core reserved-name set), applied to every language as a conservative
//! lowest common denominator — NOT a language-neutral check. The Dart-specific
//! keyword/member sanitizing that keeps THIS output legal lives in
//! emit_dart.zig's memberIdent/checkDuplicateIdents.
const std = @import("std");
const schema = @import("../schema.zig");
const events = @import("../events.zig");
const features = @import("../features.zig");
const emit = @import("emit_dart.zig");
const guards = @import("guards.zig");
const ident = @import("identifiers.zig");
const gen_client = @import("gen_client.zig");

const W = std.ArrayList(u8);

fn section(alloc: std.mem.Allocator, w: *W, title: []const u8) !void {
    const line = try std.fmt.allocPrint(alloc, "\n// ---- {s} " ++ ("-" ** 4) ++ "\n\n", .{title});
    try w.appendSlice(alloc, line);
}

/// The pure Dart generator core: collections -> full file text.
///
/// Signature mirrors gen_client.generate so the CLI/build threading is uniform.
/// `routes`, `custom_auth`, `flags`, `experiments` (the comptime-only surfaces:
/// typed RPC / auth methods / feature flags) are accepted for parity but are not
/// yet emitted in Dart — a documented follow-up. `in_repo` is unused for Dart
/// (the snapshot lives inside the client package, so the package import works).
pub fn generate(
    alloc: std.mem.Allocator,
    cols: []const schema.Collection,
    comptime routes: []const events.RouteMeta,
    comptime custom_auth: []const events.CustomAuthMeta,
    flags: []const features.FlagDef,
    experiments: []const features.ExperimentDef,
    in_repo: bool,
    auth_collection: []const u8,
    client_name: []const u8,
    api_prefix: []const u8,
) ![]const u8 {
    _ = routes;
    _ = custom_auth;
    _ = flags;
    _ = experiments;
    _ = in_repo;
    _ = api_prefix;

    var report = guards.GuardReport{ .message = "" };
    try guards.checkOperatorNames(alloc, cols, &report);
    try guards.checkIdentifiers(alloc, cols, &report);

    var w: W = .empty;
    try w.appendSlice(alloc, try std.fmt.allocPrint(alloc,
        \\// GENERATED by zigbase — do not edit.
        \\// schema-hash: {x:0>16}
        \\//
        \\// A thin, schema-aware wrapper over the base Dart SDK. Import both this
        \\// file and package:zigbase_client/typed.dart (the generic typed runtime).
        \\// Regenerate with your server's `typegen --lang dart` command (or the
        \\// build-time comptime gen-client build step), then `dart format` it with
        \\// the consuming package's language version (resolved from the package
        \\// config; without one, pass --language-version — style differs by version).
        \\//
        \\// Identifier mapping: a schema name that is a Dart reserved word or would
        \\// shadow a generated/Object member gets a trailing `_` on the DART side
        \\// only (field `default` -> member `default_`); wire keys are unchanged.
        \\// ignore_for_file: non_constant_identifier_names, constant_identifier_names, unused_element, unused_import, unnecessary_import, unused_field, prefer_const_constructors
        \\
        \\import 'package:zigbase_client/zigbase_client.dart';
        \\import 'package:zigbase_client/typed.dart';
        \\
    , .{gen_client.schemaHash(cols)}));
    if (emit.anyFileFields(cols)) {
        try w.appendSlice(alloc, "import 'package:http/http.dart' show MultipartFile;\n");
    }

    try section(alloc, &w, "Records");
    for (cols) |c| try emit.emitSelectEnums(alloc, &w, c);
    for (cols) |c| try emit.emitRecord(alloc, &w, cols, c);

    try section(alloc, &w, "Create / Update payloads");
    for (cols) |c| {
        try emit.emitCreate(alloc, &w, c);
        try emit.emitUpdate(alloc, &w, c);
    }

    try section(alloc, &w, "Fluent field builders");
    for (cols) |c| try emit.emitFields(alloc, &w, cols, c);

    try section(alloc, &w, "Per-collection metadata");
    for (cols) |c| try emit.emitMeta(alloc, &w, c);

    try section(alloc, &w, "Typed services");
    for (cols) |c| try emit.emitService(alloc, &w, cols, c);

    try section(alloc, &w, "Typed realtime");
    for (cols) |c| try emit.emitRealtime(alloc, &w, c);

    try section(alloc, &w, "Client");
    try emit.emitClient(alloc, &w, cols, client_name, auth_collection);

    return w.toOwnedSlice(alloc);
}

test "generate emits a valid-looking Dart client for a mini blog" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = [_]schema.Collection{
        .{ .id = "", .name = "users", .type = .auth, .fields = &.{
            .{ .id = "", .name = "displayName", .options = .{ .text = .{} } },
        } },
        .{ .id = "", .name = "posts", .fields = &.{
            .{ .id = "", .name = "title", .required = true, .options = .{ .text = .{} } },
            .{ .id = "", .name = "status", .options = .{ .select = .{ .values = &.{ "draft", "published" }, .maxSelect = 1 } } },
            .{ .id = "", .name = "views", .options = .{ .number = .{ .mode = .int } } },
            .{ .id = "", .name = "author", .options = .{ .relation = .{ .targetCollectionId = "users", .maxSelect = 1 } } },
            .{ .id = "", .name = "cover", .options = .{ .file = .{ .maxSelect = 1 } } },
        } },
    };
    const out = try generate(a, &cols, &.{}, &.{}, &.{}, &.{}, true, "users", "ZbClient", "/api");
    // Spot-check the key generated shapes.
    try std.testing.expect(std.mem.indexOf(u8, out, "class Post {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "enum PostStatus {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "views = coerceInt(r['views'])") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class PostExpand {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "author = expandOne<User>(r, 'author', User.fromRecord)") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "class PostsService {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "TypedCollection<Post>(client, postsMeta, Post.fromRecord)") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "authWithPassword(String identity, String password)") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "enum PostFileField {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "ZbClient createClient(") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "import 'package:http/http.dart'") != null);
}

test "Dart reserved words and member collisions are sanitized (wire keys unchanged)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = [_]schema.Collection{
        .{ .id = "", .name = "users", .type = .auth, .fields = &.{} },
        // `raw` collides with the ZbClient member; fields named `default`/`in`
        // are Dart keywords; `expand` collides with the generated record member;
        // select value `default` is a keyword enum member.
        .{ .id = "", .name = "raw", .fields = &.{
            .{ .id = "", .name = "default", .required = true, .options = .{ .text = .{} } },
            .{ .id = "", .name = "in", .options = .{ .number = .{ .mode = .int } } },
            .{ .id = "", .name = "expand", .options = .{ .text = .{} } },
            .{ .id = "", .name = "kind", .options = .{ .select = .{ .values = &.{ "default", "custom" }, .maxSelect = 1 } } },
            .{ .id = "", .name = "author", .options = .{ .relation = .{ .targetCollectionId = "users", .maxSelect = 1 } } },
        } },
    };
    const out = try generate(a, &cols, &.{}, &.{}, &.{}, &.{}, true, "users", "ZbClient", "/api");
    // Record members: keyword-sanitized Dart identifier, wire key untouched.
    try std.testing.expect(std.mem.indexOf(u8, out, "default_ = coerceString(r['default'])") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "in_ = coerceInt(r['in'])") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "expand_ = coerceString(r['expand'])") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "final String default_;") != null);
    // No unsanitized keyword member leaked.
    try std.testing.expect(std.mem.indexOf(u8, out, "final String default;") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "final int in;") == null);
    // Payload: required ctor param + toMap keeps the wire key.
    try std.testing.expect(std.mem.indexOf(u8, out, "required this.default_,") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "'default': default_,") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "'in': encodeInt(in_),") != null);
    // Fluent getter sanitized; filter path stays wire.
    try std.testing.expect(std.mem.indexOf(u8, out, "get default_ => StringFieldExpr('${_p}default')") != null);
    // Select enum member: keyword value sanitized, wire string unchanged.
    try std.testing.expect(std.mem.indexOf(u8, out, "default_('default')") != null);
    // Client accessor: collection `raw` -> accessor `raw_` (ZbClient.raw reserved).
    try std.testing.expect(std.mem.indexOf(u8, out, "late final RawService raw_ = RawService(raw);") != null);
}

test "two schema names mapping to one Dart identifier is a generation error" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cols = [_]schema.Collection{
        .{ .id = "", .name = "posts", .fields = &.{
            .{ .id = "", .name = "default", .options = .{ .text = .{} } },
            .{ .id = "", .name = "default_", .options = .{ .text = .{} } },
        } },
    };
    try std.testing.expectError(
        error.DartIdentCollision,
        generate(a, &cols, &.{}, &.{}, &.{}, &.{}, true, "", "ZbClient", "/api"),
    );
}
