// @zigbase/client/typed — the hand-written generic typed core that a generated
// zbase.gen.ts instantiates. All intricate type-level machinery lives here; the
// generator emits a thin declarative layer that instantiates it.
export const TYPED_CORE_VERSION = "0.2.0";

/** A sortable-field expression: the field name for ascending, `-field` for descending. */
export type SortExpr<F extends string> = F | `-${F}`;

/** Compatibility marker: present iff this typed core supports files generated by
 *  ZigBase >= 0.10.0 (requires `@zigbase/client` >= 0.3.0). Generated clients reference
 *  it so an old core fails typecheck with an error that names this type. */
export type CoreSupports_0_3 = true;

// The one expand-narrowing generic.
export type { WithExpand } from "./expand.js";

// Operator-object types referenced by generated `*Where` types.
export type {
  StringOps,
  NumberOps,
  BoolOps,
  DateOps,
  EnumOps,
  RelOps,
} from "./operators.js";

// Runtime field metadata.
export type { FieldType, FieldMeta, CollectionMeta } from "./meta.js";
export { fieldMeta } from "./meta.js";

// where-DSL compiler + fluent builder.
export { compileWhere, compileIn, OP_MAP } from "./where.js";
export type { RelationResolver, OpKey } from "./where.js";
export { makeFilterBuilder, Expr, FieldExpr } from "./fluent.js";
export type { FilterRoot, TypedFieldExpr } from "./fluent.js";

// Typed runtime factories (narrowed by the generated file).
export { makeRecordService } from "./service.js";
export type {
  RawTypedService,
  TypedListOptions,
  TypedReadOptions,
  TypedPageOptions,
} from "./service.js";
export { makeTypedRealtime } from "./realtime.js";
export type {
  RawTypedRealtime,
  TypedSubscribeOptions,
  TypedLiveListOptions,
} from "./realtime.js";
export { makeTypedFiles } from "./files.js";
export type { RawTypedFiles } from "./files.js";
