// GENERATED by zigbase — do not edit.
// schema-hash: 097ea715a9163fd9
// typed-core-version: 0.1.0
//
// A thin, schema-aware wrapper generating @Serializable data classes over
// the io.github.valthon.zigbase.typed runtime. Regenerate with
// `zig build gen-dating-kotlin-client`, then `spotlessApply` it from
// clients/kotlin (its ktlint config governs formatting).
//
// Identifier mapping: a schema name that is a Kotlin keyword gets a
// trailing `_` on the KOTLIN side only (field `class` -> member
// `class_`); wire keys are unchanged (a `@SerialName` carries the
// original wire key whenever it differs from the sanitized member).
package io.github.valthon.zigbase.codegen.dating

import io.github.valthon.zigbase.AuthResponse
import io.github.valthon.zigbase.FileArg
import io.github.valthon.zigbase.ZbRecord
import io.github.valthon.zigbase.ZigbaseClient
import io.github.valthon.zigbase.auth.AuthStore
import io.github.valthon.zigbase.auth.MemoryAuthStore
import io.github.valthon.zigbase.typed.BoolFieldExpr
import io.github.valthon.zigbase.typed.CollectionMeta
import io.github.valthon.zigbase.typed.EnumFieldExpr
import io.github.valthon.zigbase.typed.Expr
import io.github.valthon.zigbase.typed.FieldExpr
import io.github.valthon.zigbase.typed.FieldMeta
import io.github.valthon.zigbase.typed.FieldType
import io.github.valthon.zigbase.typed.NumberFieldExpr
import io.github.valthon.zigbase.typed.NumberMode
import io.github.valthon.zigbase.typed.RelFieldExpr
import io.github.valthon.zigbase.typed.StringFieldExpr
import io.github.valthon.zigbase.typed.TypedCollection
import io.github.valthon.zigbase.typed.TypedCursorPage
import io.github.valthon.zigbase.typed.TypedList
import io.github.valthon.zigbase.typed.TypedRealtime
import io.github.valthon.zigbase.typed.coerceBoolean
import io.github.valthon.zigbase.typed.coerceDouble
import io.github.valthon.zigbase.typed.coerceDoubleList
import io.github.valthon.zigbase.typed.coerceLong
import io.github.valthon.zigbase.typed.coerceLongList
import io.github.valthon.zigbase.typed.coerceString
import io.github.valthon.zigbase.typed.coerceStringList
import io.github.valthon.zigbase.typed.encodeFixed
import io.github.valthon.zigbase.typed.encodeInt
import io.github.valthon.zigbase.typed.expandMany
import io.github.valthon.zigbase.typed.expandOne
import io.ktor.client.HttpClient
import io.ktor.http.HttpMethod
import kotlinx.coroutines.flow.Flow
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

// Extracts a plain String from a raw wire value for `<Enum>.fromWire`,
// treating a missing key or an explicit JSON null as "no value" (unlike
// `coerceString`, whose non-null fallback would collide with a select
// value that happens to be the empty string).
private fun wireStringOrNull(v: JsonElement?): String? {
    val e = (if (v == null || v is JsonNull) null else v) as? JsonPrimitive ?: return null
    return if (e.isString) e.content else null
}

@Serializable
enum class ProfileGender(
    val wire: String,
) {
    @SerialName("female")
    FEMALE("female"),

    @SerialName("male")
    MALE("male"),

    @SerialName("nonbinary")
    NONBINARY("nonbinary"),

    @SerialName("other")
    OTHER("other"),
    ;

    companion object {
        fun fromWire(v: String?): ProfileGender? = entries.firstOrNull { it.wire == v }
    }
}

@Serializable
enum class SubscriptionPlan(
    val wire: String,
) {
    @SerialName("free")
    FREE("free"),

    @SerialName("plus")
    PLUS("plus"),

    @SerialName("premium")
    PREMIUM("premium"),
    ;

    companion object {
        fun fromWire(v: String?): SubscriptionPlan? = entries.firstOrNull { it.wire == v }
    }
}

@Serializable
data class Profile(
    val id: String,
    val email: String,
    val username: String,
    val verified: Boolean,
    val name: String,
    val bio: String,
    val website: String,
    val age: Long,
    val gender: ProfileGender?,
    val avatar: String,
    val created: String,
    val updated: String,
) {
    companion object {
        fun fromRecord(r: JsonObject): Profile =
            Profile(
                id = coerceString(r["id"]),
                email = coerceString(r["email"]),
                username = coerceString(r["username"]),
                verified = coerceBoolean(r["verified"]),
                name = coerceString(r["name"]),
                bio = coerceString(r["bio"]),
                website = coerceString(r["website"]),
                age = coerceLong(r["age"]),
                gender = ProfileGender.fromWire(wireStringOrNull(r["gender"])),
                avatar = coerceString(r["avatar"]),
                created = coerceString(r["created"]),
                updated = coerceString(r["updated"]),
            )
    }
}

@Serializable
data class Tag(
    val id: String,
    val label: String,
    val created: String,
    val updated: String,
) {
    companion object {
        fun fromRecord(r: JsonObject): Tag =
            Tag(
                id = coerceString(r["id"]),
                label = coerceString(r["label"]),
                created = coerceString(r["created"]),
                updated = coerceString(r["updated"]),
            )
    }
}

@Serializable
data class PhotoExpand(
    val owner: Profile? = null,
    val tags: List<Tag> = emptyList(),
) {
    companion object {
        fun fromRecord(r: JsonObject): PhotoExpand =
            PhotoExpand(
                owner = expandOne(r, "owner", Profile::fromRecord),
                tags = expandMany(r, "tags", Tag::fromRecord),
            )
    }
}

@Serializable
data class Photo(
    val id: String,
    val owner: String,
    val image: String,
    val caption: String,
    val tags: List<String>,
    val created: String,
    val updated: String,
    val expand: PhotoExpand = PhotoExpand(),
) {
    companion object {
        fun fromRecord(r: JsonObject): Photo =
            Photo(
                id = coerceString(r["id"]),
                owner = coerceString(r["owner"]),
                image = coerceString(r["image"]),
                caption = coerceString(r["caption"]),
                tags = coerceStringList(r["tags"]),
                created = coerceString(r["created"]),
                updated = coerceString(r["updated"]),
                expand = PhotoExpand.fromRecord(r),
            )
    }
}

@Serializable
data class PrivatePhotoExpand(
    val owner: Profile? = null,
) {
    companion object {
        fun fromRecord(r: JsonObject): PrivatePhotoExpand =
            PrivatePhotoExpand(
                owner = expandOne(r, "owner", Profile::fromRecord),
            )
    }
}

@Serializable
data class PrivatePhoto(
    val id: String,
    val owner: String,
    val image: String,
    val caption: String,
    val created: String,
    val updated: String,
    val expand: PrivatePhotoExpand = PrivatePhotoExpand(),
) {
    companion object {
        fun fromRecord(r: JsonObject): PrivatePhoto =
            PrivatePhoto(
                id = coerceString(r["id"]),
                owner = coerceString(r["owner"]),
                image = coerceString(r["image"]),
                caption = coerceString(r["caption"]),
                created = coerceString(r["created"]),
                updated = coerceString(r["updated"]),
                expand = PrivatePhotoExpand.fromRecord(r),
            )
    }
}

@Serializable
data class MessageExpand(
    val from: Profile? = null,
    val to: Profile? = null,
) {
    companion object {
        fun fromRecord(r: JsonObject): MessageExpand =
            MessageExpand(
                from = expandOne(r, "from", Profile::fromRecord),
                to = expandOne(r, "to", Profile::fromRecord),
            )
    }
}

@Serializable
data class Message(
    val id: String,
    val from: String,
    val to: String,
    val body: String,
    val sentAt: String,
    val read: Boolean,
    val created: String,
    val updated: String,
    val expand: MessageExpand = MessageExpand(),
) {
    companion object {
        fun fromRecord(r: JsonObject): Message =
            Message(
                id = coerceString(r["id"]),
                from = coerceString(r["from"]),
                to = coerceString(r["to"]),
                body = coerceString(r["body"]),
                sentAt = coerceString(r["sentAt"]),
                read = coerceBoolean(r["read"]),
                created = coerceString(r["created"]),
                updated = coerceString(r["updated"]),
                expand = MessageExpand.fromRecord(r),
            )
    }
}

@Serializable
data class WinkExpand(
    val from: Profile? = null,
    val to: Profile? = null,
) {
    companion object {
        fun fromRecord(r: JsonObject): WinkExpand =
            WinkExpand(
                from = expandOne(r, "from", Profile::fromRecord),
                to = expandOne(r, "to", Profile::fromRecord),
            )
    }
}

@Serializable
data class Wink(
    val id: String,
    val from: String,
    val to: String,
    val createdAt: String,
    val created: String,
    val updated: String,
    val expand: WinkExpand = WinkExpand(),
) {
    companion object {
        fun fromRecord(r: JsonObject): Wink =
            Wink(
                id = coerceString(r["id"]),
                from = coerceString(r["from"]),
                to = coerceString(r["to"]),
                createdAt = coerceString(r["createdAt"]),
                created = coerceString(r["created"]),
                updated = coerceString(r["updated"]),
                expand = WinkExpand.fromRecord(r),
            )
    }
}

@Serializable
data class SubscriptionExpand(
    val profile: Profile? = null,
) {
    companion object {
        fun fromRecord(r: JsonObject): SubscriptionExpand =
            SubscriptionExpand(
                profile = expandOne(r, "profile", Profile::fromRecord),
            )
    }
}

@Serializable
data class Subscription(
    val id: String,
    val profile: String,
    val plan: SubscriptionPlan?,
    val price: Double,
    val renewsAt: String,
    val active: Boolean,
    val metadata: JsonElement?,
    val created: String,
    val updated: String,
    val expand: SubscriptionExpand = SubscriptionExpand(),
) {
    companion object {
        fun fromRecord(r: JsonObject): Subscription =
            Subscription(
                id = coerceString(r["id"]),
                profile = coerceString(r["profile"]),
                plan = SubscriptionPlan.fromWire(wireStringOrNull(r["plan"])),
                price = coerceDouble(r["price"]),
                renewsAt = coerceString(r["renewsAt"]),
                active = coerceBoolean(r["active"]),
                metadata = r["metadata"],
                created = coerceString(r["created"]),
                updated = coerceString(r["updated"]),
                expand = SubscriptionExpand.fromRecord(r),
            )
    }
}

@Serializable
data class Note(
    val id: String,
    val account: String,
    val title: String,
    val body: String,
    val attachment: String,
    val created: String,
    val updated: String,
) {
    companion object {
        fun fromRecord(r: JsonObject): Note =
            Note(
                id = coerceString(r["id"]),
                account = coerceString(r["account"]),
                title = coerceString(r["title"]),
                body = coerceString(r["body"]),
                attachment = coerceString(r["attachment"]),
                created = coerceString(r["created"]),
                updated = coerceString(r["updated"]),
            )
    }
}

data class ProfileCreate(
    val email: String,
    val password: String,
    val passwordConfirm: String,
    val name: String? = null,
    val bio: String? = null,
    val website: String? = null,
    val age: Long? = null,
    val gender: ProfileGender? = null,
    val avatar: FileArg? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        m["email"] = email
        m["password"] = password
        m["passwordConfirm"] = passwordConfirm
        if (name != null) m["name"] = name
        if (bio != null) m["bio"] = bio
        if (website != null) m["website"] = website
        if (age != null) m["age"] = encodeInt(age)
        if (gender != null) m["gender"] = gender.wire
        if (avatar != null) m["avatar"] = avatar
        return m
    }
}

data class ProfileUpdate(
    val email: String? = null,
    val name: String? = null,
    val bio: String? = null,
    val website: String? = null,
    val age: Long? = null,
    val gender: ProfileGender? = null,
    val avatar: FileArg? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (email != null) m["email"] = email
        if (name != null) m["name"] = name
        if (bio != null) m["bio"] = bio
        if (website != null) m["website"] = website
        if (age != null) m["age"] = encodeInt(age)
        if (gender != null) m["gender"] = gender.wire
        if (avatar != null) m["avatar"] = avatar
        return m
    }
}

data class TagCreate(
    val label: String,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        m["label"] = label
        return m
    }
}

data class TagUpdate(
    val label: String? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (label != null) m["label"] = label
        return m
    }
}

data class PhotoCreate(
    val owner: String? = null,
    val image: FileArg? = null,
    val caption: String? = null,
    val tags: List<String>? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (owner != null) m["owner"] = owner
        if (image != null) m["image"] = image
        if (caption != null) m["caption"] = caption
        if (tags != null) m["tags"] = tags
        return m
    }
}

data class PhotoUpdate(
    val owner: String? = null,
    val image: FileArg? = null,
    val caption: String? = null,
    val tags: List<String>? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (owner != null) m["owner"] = owner
        if (image != null) m["image"] = image
        if (caption != null) m["caption"] = caption
        if (tags != null) m["tags"] = tags
        return m
    }
}

data class PrivatePhotoCreate(
    val owner: String? = null,
    val image: FileArg? = null,
    val caption: String? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (owner != null) m["owner"] = owner
        if (image != null) m["image"] = image
        if (caption != null) m["caption"] = caption
        return m
    }
}

data class PrivatePhotoUpdate(
    val owner: String? = null,
    val image: FileArg? = null,
    val caption: String? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (owner != null) m["owner"] = owner
        if (image != null) m["image"] = image
        if (caption != null) m["caption"] = caption
        return m
    }
}

data class MessageCreate(
    val body: String,
    val from: String? = null,
    val to: String? = null,
    val sentAt: String? = null,
    val read: Boolean? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (from != null) m["from"] = from
        if (to != null) m["to"] = to
        m["body"] = body
        if (sentAt != null) m["sentAt"] = sentAt
        if (read != null) m["read"] = read
        return m
    }
}

data class MessageUpdate(
    val from: String? = null,
    val to: String? = null,
    val body: String? = null,
    val sentAt: String? = null,
    val read: Boolean? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (from != null) m["from"] = from
        if (to != null) m["to"] = to
        if (body != null) m["body"] = body
        if (sentAt != null) m["sentAt"] = sentAt
        if (read != null) m["read"] = read
        return m
    }
}

data class WinkCreate(
    val from: String? = null,
    val to: String? = null,
    val createdAt: String? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (from != null) m["from"] = from
        if (to != null) m["to"] = to
        if (createdAt != null) m["createdAt"] = createdAt
        return m
    }
}

data class WinkUpdate(
    val from: String? = null,
    val to: String? = null,
    val createdAt: String? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (from != null) m["from"] = from
        if (to != null) m["to"] = to
        if (createdAt != null) m["createdAt"] = createdAt
        return m
    }
}

data class SubscriptionCreate(
    val profile: String? = null,
    val plan: SubscriptionPlan? = null,
    val price: Double? = null,
    val renewsAt: String? = null,
    val active: Boolean? = null,
    val metadata: JsonElement? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (profile != null) m["profile"] = profile
        if (plan != null) m["plan"] = plan.wire
        if (price != null) m["price"] = encodeFixed(price, 2)
        if (renewsAt != null) m["renewsAt"] = renewsAt
        if (active != null) m["active"] = active
        if (metadata != null) m["metadata"] = metadata
        return m
    }
}

data class SubscriptionUpdate(
    val profile: String? = null,
    val plan: SubscriptionPlan? = null,
    val price: Double? = null,
    val renewsAt: String? = null,
    val active: Boolean? = null,
    val metadata: JsonElement? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (profile != null) m["profile"] = profile
        if (plan != null) m["plan"] = plan.wire
        if (price != null) m["price"] = encodeFixed(price, 2)
        if (renewsAt != null) m["renewsAt"] = renewsAt
        if (active != null) m["active"] = active
        if (metadata != null) m["metadata"] = metadata
        return m
    }
}

data class NoteCreate(
    val title: String,
    val body: String? = null,
    val attachment: FileArg? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        m["title"] = title
        if (body != null) m["body"] = body
        if (attachment != null) m["attachment"] = attachment
        return m
    }
}

data class NoteUpdate(
    val title: String? = null,
    val body: String? = null,
    val attachment: FileArg? = null,
) {
    fun toMap(): Map<String, Any?> {
        val m = mutableMapOf<String, Any?>()
        if (title != null) m["title"] = title
        if (body != null) m["body"] = body
        if (attachment != null) m["attachment"] = attachment
        return m
    }
}

class ProfileFields(
    private val prefix: String = "",
) {
    val email: StringFieldExpr get() = StringFieldExpr("${prefix}email")

    val username: StringFieldExpr get() = StringFieldExpr("${prefix}username")

    val verified: BoolFieldExpr get() = BoolFieldExpr("${prefix}verified")

    val name: StringFieldExpr get() = StringFieldExpr("${prefix}name")

    val bio: StringFieldExpr get() = StringFieldExpr("${prefix}bio")

    val website: StringFieldExpr get() = StringFieldExpr("${prefix}website")

    val age: NumberFieldExpr get() = NumberFieldExpr("${prefix}age")

    val gender: EnumFieldExpr<ProfileGender> get() = EnumFieldExpr<ProfileGender>("${prefix}gender") { it.wire }

    val id: StringFieldExpr get() = StringFieldExpr("${prefix}id")

    val created: StringFieldExpr get() = StringFieldExpr("${prefix}created")

    val updated: StringFieldExpr get() = StringFieldExpr("${prefix}updated")
}

class TagFields(
    private val prefix: String = "",
) {
    val label: StringFieldExpr get() = StringFieldExpr("${prefix}label")

    val id: StringFieldExpr get() = StringFieldExpr("${prefix}id")

    val created: StringFieldExpr get() = StringFieldExpr("${prefix}created")

    val updated: StringFieldExpr get() = StringFieldExpr("${prefix}updated")
}

class PhotoFields(
    private val prefix: String = "",
) {
    val owner: RelFieldExpr<ProfileFields> get() = RelFieldExpr<ProfileFields>("${prefix}owner") { ProfileFields(it) }

    val caption: StringFieldExpr get() = StringFieldExpr("${prefix}caption")

    val tags: RelFieldExpr<TagFields> get() = RelFieldExpr<TagFields>("${prefix}tags") { TagFields(it) }

    val id: StringFieldExpr get() = StringFieldExpr("${prefix}id")

    val created: StringFieldExpr get() = StringFieldExpr("${prefix}created")

    val updated: StringFieldExpr get() = StringFieldExpr("${prefix}updated")
}

class PrivatePhotoFields(
    private val prefix: String = "",
) {
    val owner: RelFieldExpr<ProfileFields> get() = RelFieldExpr<ProfileFields>("${prefix}owner") { ProfileFields(it) }

    val caption: StringFieldExpr get() = StringFieldExpr("${prefix}caption")

    val id: StringFieldExpr get() = StringFieldExpr("${prefix}id")

    val created: StringFieldExpr get() = StringFieldExpr("${prefix}created")

    val updated: StringFieldExpr get() = StringFieldExpr("${prefix}updated")
}

class MessageFields(
    private val prefix: String = "",
) {
    val from: RelFieldExpr<ProfileFields> get() = RelFieldExpr<ProfileFields>("${prefix}from") { ProfileFields(it) }

    val to: RelFieldExpr<ProfileFields> get() = RelFieldExpr<ProfileFields>("${prefix}to") { ProfileFields(it) }

    val body: StringFieldExpr get() = StringFieldExpr("${prefix}body")

    val sentAt: StringFieldExpr get() = StringFieldExpr("${prefix}sentAt")

    val read: BoolFieldExpr get() = BoolFieldExpr("${prefix}read")

    val id: StringFieldExpr get() = StringFieldExpr("${prefix}id")

    val created: StringFieldExpr get() = StringFieldExpr("${prefix}created")

    val updated: StringFieldExpr get() = StringFieldExpr("${prefix}updated")
}

class WinkFields(
    private val prefix: String = "",
) {
    val from: RelFieldExpr<ProfileFields> get() = RelFieldExpr<ProfileFields>("${prefix}from") { ProfileFields(it) }

    val to: RelFieldExpr<ProfileFields> get() = RelFieldExpr<ProfileFields>("${prefix}to") { ProfileFields(it) }

    val createdAt: StringFieldExpr get() = StringFieldExpr("${prefix}createdAt")

    val id: StringFieldExpr get() = StringFieldExpr("${prefix}id")

    val created: StringFieldExpr get() = StringFieldExpr("${prefix}created")

    val updated: StringFieldExpr get() = StringFieldExpr("${prefix}updated")
}

class SubscriptionFields(
    private val prefix: String = "",
) {
    val profile: RelFieldExpr<ProfileFields> get() = RelFieldExpr<ProfileFields>("${prefix}profile") { ProfileFields(it) }

    val plan: EnumFieldExpr<SubscriptionPlan> get() = EnumFieldExpr<SubscriptionPlan>("${prefix}plan") { it.wire }

    val price: NumberFieldExpr get() = NumberFieldExpr("${prefix}price")

    val renewsAt: StringFieldExpr get() = StringFieldExpr("${prefix}renewsAt")

    val active: BoolFieldExpr get() = BoolFieldExpr("${prefix}active")

    val id: StringFieldExpr get() = StringFieldExpr("${prefix}id")

    val created: StringFieldExpr get() = StringFieldExpr("${prefix}created")

    val updated: StringFieldExpr get() = StringFieldExpr("${prefix}updated")
}

class NoteFields(
    private val prefix: String = "",
) {
    val account: FieldExpr get() = FieldExpr("${prefix}account")

    val title: StringFieldExpr get() = StringFieldExpr("${prefix}title")

    val body: StringFieldExpr get() = StringFieldExpr("${prefix}body")

    val id: StringFieldExpr get() = StringFieldExpr("${prefix}id")

    val created: StringFieldExpr get() = StringFieldExpr("${prefix}created")

    val updated: StringFieldExpr get() = StringFieldExpr("${prefix}updated")
}

val profilesMeta =
    CollectionMeta(
        name = "profiles",
        fields =
            mapOf(
                "id" to FieldMeta(type = FieldType.TEXT),
                "email" to FieldMeta(type = FieldType.EMAIL),
                "username" to FieldMeta(type = FieldType.TEXT),
                "verified" to FieldMeta(type = FieldType.BOOLEAN),
                "name" to FieldMeta(type = FieldType.TEXT),
                "bio" to FieldMeta(type = FieldType.EDITOR),
                "website" to FieldMeta(type = FieldType.URL),
                "age" to FieldMeta(type = FieldType.NUMBER, mode = NumberMode.INTEGER),
                "gender" to FieldMeta(type = FieldType.SELECT),
                "avatar" to FieldMeta(type = FieldType.FILE),
                "created" to FieldMeta(type = FieldType.AUTODATE),
                "updated" to FieldMeta(type = FieldType.AUTODATE),
            ),
        fileFields = listOf("avatar"),
        expandable = listOf(),
        isAuth = true,
        searchable = listOf("bio"),
    )

val tagsMeta =
    CollectionMeta(
        name = "tags",
        fields =
            mapOf(
                "id" to FieldMeta(type = FieldType.TEXT),
                "label" to FieldMeta(type = FieldType.TEXT),
                "created" to FieldMeta(type = FieldType.AUTODATE),
                "updated" to FieldMeta(type = FieldType.AUTODATE),
            ),
        fileFields = listOf(),
        expandable = listOf(),
        isAuth = false,
    )

val photosMeta =
    CollectionMeta(
        name = "photos",
        fields =
            mapOf(
                "id" to FieldMeta(type = FieldType.TEXT),
                "owner" to FieldMeta(type = FieldType.RELATION),
                "image" to FieldMeta(type = FieldType.FILE),
                "caption" to FieldMeta(type = FieldType.TEXT),
                "tags" to FieldMeta(type = FieldType.RELATION, multi = true),
                "created" to FieldMeta(type = FieldType.AUTODATE),
                "updated" to FieldMeta(type = FieldType.AUTODATE),
            ),
        fileFields = listOf("image"),
        expandable = listOf("owner", "tags"),
        isAuth = false,
    )

val privatePhotosMeta =
    CollectionMeta(
        name = "privatePhotos",
        fields =
            mapOf(
                "id" to FieldMeta(type = FieldType.TEXT),
                "owner" to FieldMeta(type = FieldType.RELATION),
                "image" to FieldMeta(type = FieldType.FILE),
                "caption" to FieldMeta(type = FieldType.TEXT),
                "created" to FieldMeta(type = FieldType.AUTODATE),
                "updated" to FieldMeta(type = FieldType.AUTODATE),
            ),
        fileFields = listOf("image"),
        expandable = listOf("owner"),
        isAuth = false,
    )

val messagesMeta =
    CollectionMeta(
        name = "messages",
        fields =
            mapOf(
                "id" to FieldMeta(type = FieldType.TEXT),
                "from" to FieldMeta(type = FieldType.RELATION),
                "to" to FieldMeta(type = FieldType.RELATION),
                "body" to FieldMeta(type = FieldType.TEXT),
                "sentAt" to FieldMeta(type = FieldType.AUTODATE),
                "read" to FieldMeta(type = FieldType.BOOLEAN),
                "created" to FieldMeta(type = FieldType.AUTODATE),
                "updated" to FieldMeta(type = FieldType.AUTODATE),
            ),
        fileFields = listOf(),
        expandable = listOf("from", "to"),
        isAuth = false,
        searchable = listOf("body"),
    )

val winksMeta =
    CollectionMeta(
        name = "winks",
        fields =
            mapOf(
                "id" to FieldMeta(type = FieldType.TEXT),
                "from" to FieldMeta(type = FieldType.RELATION),
                "to" to FieldMeta(type = FieldType.RELATION),
                "createdAt" to FieldMeta(type = FieldType.AUTODATE),
                "created" to FieldMeta(type = FieldType.AUTODATE),
                "updated" to FieldMeta(type = FieldType.AUTODATE),
            ),
        fileFields = listOf(),
        expandable = listOf("from", "to"),
        isAuth = false,
    )

val subscriptionsMeta =
    CollectionMeta(
        name = "subscriptions",
        fields =
            mapOf(
                "id" to FieldMeta(type = FieldType.TEXT),
                "profile" to FieldMeta(type = FieldType.RELATION),
                "plan" to FieldMeta(type = FieldType.SELECT),
                "price" to FieldMeta(type = FieldType.NUMBER, mode = NumberMode.FIXED, scale = 2),
                "renewsAt" to FieldMeta(type = FieldType.DATE),
                "active" to FieldMeta(type = FieldType.BOOLEAN),
                "metadata" to FieldMeta(type = FieldType.JSON),
                "created" to FieldMeta(type = FieldType.AUTODATE),
                "updated" to FieldMeta(type = FieldType.AUTODATE),
            ),
        fileFields = listOf(),
        expandable = listOf("profile"),
        isAuth = false,
    )

val notesMeta =
    CollectionMeta(
        name = "notes",
        fields =
            mapOf(
                "id" to FieldMeta(type = FieldType.TEXT),
                "account" to FieldMeta(type = FieldType.RELATION),
                "title" to FieldMeta(type = FieldType.TEXT),
                "body" to FieldMeta(type = FieldType.TEXT),
                "attachment" to FieldMeta(type = FieldType.FILE),
                "created" to FieldMeta(type = FieldType.AUTODATE),
                "updated" to FieldMeta(type = FieldType.AUTODATE),
            ),
        fileFields = listOf("attachment"),
        expandable = listOf("account"),
        isAuth = false,
        tenant = "account",
    )

class ProfilesService(
    client: ZigbaseClient,
) {
    private val c: TypedCollection<Profile> = TypedCollection(client, profilesMeta, Profile::fromRecord)

    suspend fun getList(
        page: Int = 1,
        perPage: Int = 30,
        where: ((ProfileFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        skipTotal: Boolean = false,
        search: String? = null,
    ): TypedList<Profile> =
        c.getList(
            page = page,
            perPage = perPage,
            filter = where?.let { it(ProfileFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            skipTotal = skipTotal,
            search = search,
        )

    suspend fun getOne(
        id: String,
        expand: List<String>? = null,
        fields: String? = null,
    ): Profile = c.getOne(id, expand = expand, fields = fields)

    suspend fun getFirstListItem(
        where: (ProfileFields) -> Expr,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        search: String? = null,
    ): Profile =
        c.getFirstListItem(
            where(ProfileFields()).compile(),
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getPage(
        where: ((ProfileFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        cursor: String? = null,
        limit: Int = 30,
        withTotal: Boolean = false,
        fields: String? = null,
        search: String? = null,
    ): TypedCursorPage<Profile> =
        c.getPage(
            cursor = cursor,
            limit = limit,
            filter = where?.let { it(ProfileFields()).compile() },
            sort = sort,
            expand = expand,
            withTotal = withTotal,
            fields = fields,
            search = search,
        )

    fun iterate(
        where: ((ProfileFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): Flow<Profile> =
        c.iterate(
            batch = batch,
            filter = where?.let { it(ProfileFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getFullList(
        where: ((ProfileFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): List<Profile> =
        c.getFullList(
            batch = batch,
            filter = where?.let { it(ProfileFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun create(
        data: ProfileCreate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Profile = c.create(data.toMap(), expand = expand, fields = fields)

    suspend fun update(
        id: String,
        data: ProfileUpdate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Profile = c.update(id, data.toMap(), expand = expand, fields = fields)

    suspend fun delete(id: String) = c.delete(id)

    /** Compiles a typed filter expression to a server filter string. */
    fun filter(fn: (ProfileFields) -> Expr): String = fn(ProfileFields()).compile()

    suspend fun authWithPassword(
        identity: String,
        password: String,
    ): AuthResponse = c.collection.authWithPassword(identity, password)

    fun fileUrl(
        record: Profile,
        field: ProfileFileField,
        download: Boolean = false,
        thumb: String? = null,
        token: String? = null,
    ): String {
        val filename =
            when (field) {
                ProfileFileField.AVATAR -> record.avatar
            }
        return c.fileUrl(
            ZbRecord(
                buildJsonObject {
                    put("id", record.id)
                    put("collectionName", "profiles")
                },
            ),
            filename,
            download = download,
            thumb = thumb,
            token = token,
        )
    }
}

enum class ProfileFileField(
    val wire: String,
) {
    AVATAR("avatar"),
}

class TagsService(
    client: ZigbaseClient,
) {
    private val c: TypedCollection<Tag> = TypedCollection(client, tagsMeta, Tag::fromRecord)

    suspend fun getList(
        page: Int = 1,
        perPage: Int = 30,
        where: ((TagFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        skipTotal: Boolean = false,
        search: String? = null,
    ): TypedList<Tag> =
        c.getList(
            page = page,
            perPage = perPage,
            filter = where?.let { it(TagFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            skipTotal = skipTotal,
            search = search,
        )

    suspend fun getOne(
        id: String,
        expand: List<String>? = null,
        fields: String? = null,
    ): Tag = c.getOne(id, expand = expand, fields = fields)

    suspend fun getFirstListItem(
        where: (TagFields) -> Expr,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        search: String? = null,
    ): Tag =
        c.getFirstListItem(
            where(TagFields()).compile(),
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getPage(
        where: ((TagFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        cursor: String? = null,
        limit: Int = 30,
        withTotal: Boolean = false,
        fields: String? = null,
        search: String? = null,
    ): TypedCursorPage<Tag> =
        c.getPage(
            cursor = cursor,
            limit = limit,
            filter = where?.let { it(TagFields()).compile() },
            sort = sort,
            expand = expand,
            withTotal = withTotal,
            fields = fields,
            search = search,
        )

    fun iterate(
        where: ((TagFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): Flow<Tag> =
        c.iterate(
            batch = batch,
            filter = where?.let { it(TagFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getFullList(
        where: ((TagFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): List<Tag> =
        c.getFullList(
            batch = batch,
            filter = where?.let { it(TagFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun create(
        data: TagCreate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Tag = c.create(data.toMap(), expand = expand, fields = fields)

    suspend fun update(
        id: String,
        data: TagUpdate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Tag = c.update(id, data.toMap(), expand = expand, fields = fields)

    suspend fun delete(id: String) = c.delete(id)

    /** Compiles a typed filter expression to a server filter string. */
    fun filter(fn: (TagFields) -> Expr): String = fn(TagFields()).compile()
}

class PhotosService(
    client: ZigbaseClient,
) {
    private val c: TypedCollection<Photo> = TypedCollection(client, photosMeta, Photo::fromRecord)

    suspend fun getList(
        page: Int = 1,
        perPage: Int = 30,
        where: ((PhotoFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        skipTotal: Boolean = false,
        search: String? = null,
    ): TypedList<Photo> =
        c.getList(
            page = page,
            perPage = perPage,
            filter = where?.let { it(PhotoFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            skipTotal = skipTotal,
            search = search,
        )

    suspend fun getOne(
        id: String,
        expand: List<String>? = null,
        fields: String? = null,
    ): Photo = c.getOne(id, expand = expand, fields = fields)

    suspend fun getFirstListItem(
        where: (PhotoFields) -> Expr,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        search: String? = null,
    ): Photo =
        c.getFirstListItem(
            where(PhotoFields()).compile(),
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getPage(
        where: ((PhotoFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        cursor: String? = null,
        limit: Int = 30,
        withTotal: Boolean = false,
        fields: String? = null,
        search: String? = null,
    ): TypedCursorPage<Photo> =
        c.getPage(
            cursor = cursor,
            limit = limit,
            filter = where?.let { it(PhotoFields()).compile() },
            sort = sort,
            expand = expand,
            withTotal = withTotal,
            fields = fields,
            search = search,
        )

    fun iterate(
        where: ((PhotoFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): Flow<Photo> =
        c.iterate(
            batch = batch,
            filter = where?.let { it(PhotoFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getFullList(
        where: ((PhotoFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): List<Photo> =
        c.getFullList(
            batch = batch,
            filter = where?.let { it(PhotoFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun create(
        data: PhotoCreate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Photo = c.create(data.toMap(), expand = expand, fields = fields)

    suspend fun update(
        id: String,
        data: PhotoUpdate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Photo = c.update(id, data.toMap(), expand = expand, fields = fields)

    suspend fun delete(id: String) = c.delete(id)

    /** Compiles a typed filter expression to a server filter string. */
    fun filter(fn: (PhotoFields) -> Expr): String = fn(PhotoFields()).compile()

    fun fileUrl(
        record: Photo,
        field: PhotoFileField,
        download: Boolean = false,
        thumb: String? = null,
        token: String? = null,
    ): String {
        val filename =
            when (field) {
                PhotoFileField.IMAGE -> record.image
            }
        return c.fileUrl(
            ZbRecord(
                buildJsonObject {
                    put("id", record.id)
                    put("collectionName", "photos")
                },
            ),
            filename,
            download = download,
            thumb = thumb,
            token = token,
        )
    }
}

enum class PhotoFileField(
    val wire: String,
) {
    IMAGE("image"),
}

class PrivatePhotosService(
    client: ZigbaseClient,
) {
    private val c: TypedCollection<PrivatePhoto> = TypedCollection(client, privatePhotosMeta, PrivatePhoto::fromRecord)

    suspend fun getList(
        page: Int = 1,
        perPage: Int = 30,
        where: ((PrivatePhotoFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        skipTotal: Boolean = false,
        search: String? = null,
    ): TypedList<PrivatePhoto> =
        c.getList(
            page = page,
            perPage = perPage,
            filter = where?.let { it(PrivatePhotoFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            skipTotal = skipTotal,
            search = search,
        )

    suspend fun getOne(
        id: String,
        expand: List<String>? = null,
        fields: String? = null,
    ): PrivatePhoto = c.getOne(id, expand = expand, fields = fields)

    suspend fun getFirstListItem(
        where: (PrivatePhotoFields) -> Expr,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        search: String? = null,
    ): PrivatePhoto =
        c.getFirstListItem(
            where(PrivatePhotoFields()).compile(),
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getPage(
        where: ((PrivatePhotoFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        cursor: String? = null,
        limit: Int = 30,
        withTotal: Boolean = false,
        fields: String? = null,
        search: String? = null,
    ): TypedCursorPage<PrivatePhoto> =
        c.getPage(
            cursor = cursor,
            limit = limit,
            filter = where?.let { it(PrivatePhotoFields()).compile() },
            sort = sort,
            expand = expand,
            withTotal = withTotal,
            fields = fields,
            search = search,
        )

    fun iterate(
        where: ((PrivatePhotoFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): Flow<PrivatePhoto> =
        c.iterate(
            batch = batch,
            filter = where?.let { it(PrivatePhotoFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getFullList(
        where: ((PrivatePhotoFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): List<PrivatePhoto> =
        c.getFullList(
            batch = batch,
            filter = where?.let { it(PrivatePhotoFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun create(
        data: PrivatePhotoCreate,
        expand: List<String>? = null,
        fields: String? = null,
    ): PrivatePhoto = c.create(data.toMap(), expand = expand, fields = fields)

    suspend fun update(
        id: String,
        data: PrivatePhotoUpdate,
        expand: List<String>? = null,
        fields: String? = null,
    ): PrivatePhoto = c.update(id, data.toMap(), expand = expand, fields = fields)

    suspend fun delete(id: String) = c.delete(id)

    /** Compiles a typed filter expression to a server filter string. */
    fun filter(fn: (PrivatePhotoFields) -> Expr): String = fn(PrivatePhotoFields()).compile()

    fun fileUrl(
        record: PrivatePhoto,
        field: PrivatePhotoFileField,
        download: Boolean = false,
        thumb: String? = null,
        token: String? = null,
    ): String {
        val filename =
            when (field) {
                PrivatePhotoFileField.IMAGE -> record.image
            }
        return c.fileUrl(
            ZbRecord(
                buildJsonObject {
                    put("id", record.id)
                    put("collectionName", "privatePhotos")
                },
            ),
            filename,
            download = download,
            thumb = thumb,
            token = token,
        )
    }
}

enum class PrivatePhotoFileField(
    val wire: String,
) {
    IMAGE("image"),
}

class MessagesService(
    client: ZigbaseClient,
) {
    private val c: TypedCollection<Message> = TypedCollection(client, messagesMeta, Message::fromRecord)

    suspend fun getList(
        page: Int = 1,
        perPage: Int = 30,
        where: ((MessageFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        skipTotal: Boolean = false,
        search: String? = null,
    ): TypedList<Message> =
        c.getList(
            page = page,
            perPage = perPage,
            filter = where?.let { it(MessageFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            skipTotal = skipTotal,
            search = search,
        )

    suspend fun getOne(
        id: String,
        expand: List<String>? = null,
        fields: String? = null,
    ): Message = c.getOne(id, expand = expand, fields = fields)

    suspend fun getFirstListItem(
        where: (MessageFields) -> Expr,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        search: String? = null,
    ): Message =
        c.getFirstListItem(
            where(MessageFields()).compile(),
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getPage(
        where: ((MessageFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        cursor: String? = null,
        limit: Int = 30,
        withTotal: Boolean = false,
        fields: String? = null,
        search: String? = null,
    ): TypedCursorPage<Message> =
        c.getPage(
            cursor = cursor,
            limit = limit,
            filter = where?.let { it(MessageFields()).compile() },
            sort = sort,
            expand = expand,
            withTotal = withTotal,
            fields = fields,
            search = search,
        )

    fun iterate(
        where: ((MessageFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): Flow<Message> =
        c.iterate(
            batch = batch,
            filter = where?.let { it(MessageFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getFullList(
        where: ((MessageFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): List<Message> =
        c.getFullList(
            batch = batch,
            filter = where?.let { it(MessageFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun create(
        data: MessageCreate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Message = c.create(data.toMap(), expand = expand, fields = fields)

    suspend fun update(
        id: String,
        data: MessageUpdate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Message = c.update(id, data.toMap(), expand = expand, fields = fields)

    suspend fun delete(id: String) = c.delete(id)

    /** Compiles a typed filter expression to a server filter string. */
    fun filter(fn: (MessageFields) -> Expr): String = fn(MessageFields()).compile()
}

class WinksService(
    client: ZigbaseClient,
) {
    private val c: TypedCollection<Wink> = TypedCollection(client, winksMeta, Wink::fromRecord)

    suspend fun getList(
        page: Int = 1,
        perPage: Int = 30,
        where: ((WinkFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        skipTotal: Boolean = false,
        search: String? = null,
    ): TypedList<Wink> =
        c.getList(
            page = page,
            perPage = perPage,
            filter = where?.let { it(WinkFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            skipTotal = skipTotal,
            search = search,
        )

    suspend fun getOne(
        id: String,
        expand: List<String>? = null,
        fields: String? = null,
    ): Wink = c.getOne(id, expand = expand, fields = fields)

    suspend fun getFirstListItem(
        where: (WinkFields) -> Expr,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        search: String? = null,
    ): Wink =
        c.getFirstListItem(
            where(WinkFields()).compile(),
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getPage(
        where: ((WinkFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        cursor: String? = null,
        limit: Int = 30,
        withTotal: Boolean = false,
        fields: String? = null,
        search: String? = null,
    ): TypedCursorPage<Wink> =
        c.getPage(
            cursor = cursor,
            limit = limit,
            filter = where?.let { it(WinkFields()).compile() },
            sort = sort,
            expand = expand,
            withTotal = withTotal,
            fields = fields,
            search = search,
        )

    fun iterate(
        where: ((WinkFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): Flow<Wink> =
        c.iterate(
            batch = batch,
            filter = where?.let { it(WinkFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getFullList(
        where: ((WinkFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): List<Wink> =
        c.getFullList(
            batch = batch,
            filter = where?.let { it(WinkFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun create(
        data: WinkCreate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Wink = c.create(data.toMap(), expand = expand, fields = fields)

    suspend fun update(
        id: String,
        data: WinkUpdate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Wink = c.update(id, data.toMap(), expand = expand, fields = fields)

    suspend fun delete(id: String) = c.delete(id)

    /** Compiles a typed filter expression to a server filter string. */
    fun filter(fn: (WinkFields) -> Expr): String = fn(WinkFields()).compile()
}

class SubscriptionsService(
    client: ZigbaseClient,
) {
    private val c: TypedCollection<Subscription> = TypedCollection(client, subscriptionsMeta, Subscription::fromRecord)

    suspend fun getList(
        page: Int = 1,
        perPage: Int = 30,
        where: ((SubscriptionFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        skipTotal: Boolean = false,
        search: String? = null,
    ): TypedList<Subscription> =
        c.getList(
            page = page,
            perPage = perPage,
            filter = where?.let { it(SubscriptionFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            skipTotal = skipTotal,
            search = search,
        )

    suspend fun getOne(
        id: String,
        expand: List<String>? = null,
        fields: String? = null,
    ): Subscription = c.getOne(id, expand = expand, fields = fields)

    suspend fun getFirstListItem(
        where: (SubscriptionFields) -> Expr,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        search: String? = null,
    ): Subscription =
        c.getFirstListItem(
            where(SubscriptionFields()).compile(),
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getPage(
        where: ((SubscriptionFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        cursor: String? = null,
        limit: Int = 30,
        withTotal: Boolean = false,
        fields: String? = null,
        search: String? = null,
    ): TypedCursorPage<Subscription> =
        c.getPage(
            cursor = cursor,
            limit = limit,
            filter = where?.let { it(SubscriptionFields()).compile() },
            sort = sort,
            expand = expand,
            withTotal = withTotal,
            fields = fields,
            search = search,
        )

    fun iterate(
        where: ((SubscriptionFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): Flow<Subscription> =
        c.iterate(
            batch = batch,
            filter = where?.let { it(SubscriptionFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getFullList(
        where: ((SubscriptionFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): List<Subscription> =
        c.getFullList(
            batch = batch,
            filter = where?.let { it(SubscriptionFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun create(
        data: SubscriptionCreate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Subscription = c.create(data.toMap(), expand = expand, fields = fields)

    suspend fun update(
        id: String,
        data: SubscriptionUpdate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Subscription = c.update(id, data.toMap(), expand = expand, fields = fields)

    suspend fun delete(id: String) = c.delete(id)

    /** Compiles a typed filter expression to a server filter string. */
    fun filter(fn: (SubscriptionFields) -> Expr): String = fn(SubscriptionFields()).compile()
}

class NotesService(
    client: ZigbaseClient,
) {
    private val c: TypedCollection<Note> = TypedCollection(client, notesMeta, Note::fromRecord)

    suspend fun getList(
        page: Int = 1,
        perPage: Int = 30,
        where: ((NoteFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        skipTotal: Boolean = false,
        search: String? = null,
    ): TypedList<Note> =
        c.getList(
            page = page,
            perPage = perPage,
            filter = where?.let { it(NoteFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            skipTotal = skipTotal,
            search = search,
        )

    suspend fun getOne(
        id: String,
        expand: List<String>? = null,
        fields: String? = null,
    ): Note = c.getOne(id, expand = expand, fields = fields)

    suspend fun getFirstListItem(
        where: (NoteFields) -> Expr,
        sort: List<String>? = null,
        expand: List<String>? = null,
        fields: String? = null,
        search: String? = null,
    ): Note =
        c.getFirstListItem(
            where(NoteFields()).compile(),
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getPage(
        where: ((NoteFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        cursor: String? = null,
        limit: Int = 30,
        withTotal: Boolean = false,
        fields: String? = null,
        search: String? = null,
    ): TypedCursorPage<Note> =
        c.getPage(
            cursor = cursor,
            limit = limit,
            filter = where?.let { it(NoteFields()).compile() },
            sort = sort,
            expand = expand,
            withTotal = withTotal,
            fields = fields,
            search = search,
        )

    fun iterate(
        where: ((NoteFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): Flow<Note> =
        c.iterate(
            batch = batch,
            filter = where?.let { it(NoteFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun getFullList(
        where: ((NoteFields) -> Expr)? = null,
        sort: List<String>? = null,
        expand: List<String>? = null,
        batch: Int = 100,
        fields: String? = null,
        search: String? = null,
    ): List<Note> =
        c.getFullList(
            batch = batch,
            filter = where?.let { it(NoteFields()).compile() },
            sort = sort,
            expand = expand,
            fields = fields,
            search = search,
        )

    suspend fun create(
        data: NoteCreate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Note = c.create(data.toMap(), expand = expand, fields = fields)

    suspend fun update(
        id: String,
        data: NoteUpdate,
        expand: List<String>? = null,
        fields: String? = null,
    ): Note = c.update(id, data.toMap(), expand = expand, fields = fields)

    suspend fun delete(id: String) = c.delete(id)

    /** Compiles a typed filter expression to a server filter string. */
    fun filter(fn: (NoteFields) -> Expr): String = fn(NoteFields()).compile()

    fun fileUrl(
        record: Note,
        field: NoteFileField,
        download: Boolean = false,
        thumb: String? = null,
        token: String? = null,
    ): String {
        val filename =
            when (field) {
                NoteFileField.ATTACHMENT -> record.attachment
            }
        return c.fileUrl(
            ZbRecord(
                buildJsonObject {
                    put("id", record.id)
                    put("collectionName", "notes")
                },
            ),
            filename,
            download = download,
            thumb = thumb,
            token = token,
        )
    }
}

enum class NoteFileField(
    val wire: String,
) {
    ATTACHMENT("attachment"),
}

class ProfilesRealtime(
    client: ZigbaseClient,
) : TypedRealtime<Profile>(client, profilesMeta, Profile::fromRecord)

class TagsRealtime(
    client: ZigbaseClient,
) : TypedRealtime<Tag>(client, tagsMeta, Tag::fromRecord)

class PhotosRealtime(
    client: ZigbaseClient,
) : TypedRealtime<Photo>(client, photosMeta, Photo::fromRecord)

class PrivatePhotosRealtime(
    client: ZigbaseClient,
) : TypedRealtime<PrivatePhoto>(client, privatePhotosMeta, PrivatePhoto::fromRecord)

class MessagesRealtime(
    client: ZigbaseClient,
) : TypedRealtime<Message>(client, messagesMeta, Message::fromRecord)

class WinksRealtime(
    client: ZigbaseClient,
) : TypedRealtime<Wink>(client, winksMeta, Wink::fromRecord)

class SubscriptionsRealtime(
    client: ZigbaseClient,
) : TypedRealtime<Subscription>(client, subscriptionsMeta, Subscription::fromRecord)

class NotesRealtime(
    client: ZigbaseClient,
) : TypedRealtime<Note>(client, notesMeta, Note::fromRecord)

class ZbClient(
    val raw: ZigbaseClient,
    val owned: Boolean = false,
) : AutoCloseable {
    val profiles: ProfilesService by lazy { ProfilesService(raw) }
    val tags: TagsService by lazy { TagsService(raw) }
    val photos: PhotosService by lazy { PhotosService(raw) }
    val privatePhotos: PrivatePhotosService by lazy { PrivatePhotosService(raw) }
    val messages: MessagesService by lazy { MessagesService(raw) }
    val winks: WinksService by lazy { WinksService(raw) }
    val subscriptions: SubscriptionsService by lazy { SubscriptionsService(raw) }
    val notes: NotesService by lazy { NotesService(raw) }

    val profilesRealtime: ProfilesRealtime by lazy { ProfilesRealtime(raw) }
    val tagsRealtime: TagsRealtime by lazy { TagsRealtime(raw) }
    val photosRealtime: PhotosRealtime by lazy { PhotosRealtime(raw) }
    val privatePhotosRealtime: PrivatePhotosRealtime by lazy { PrivatePhotosRealtime(raw) }
    val messagesRealtime: MessagesRealtime by lazy { MessagesRealtime(raw) }
    val winksRealtime: WinksRealtime by lazy { WinksRealtime(raw) }
    val subscriptionsRealtime: SubscriptionsRealtime by lazy { SubscriptionsRealtime(raw) }
    val notesRealtime: NotesRealtime by lazy { NotesRealtime(raw) }

    val authStore: AuthStore get() = raw.authStore

    suspend fun send(
        method: HttpMethod,
        path: String,
        query: Map<String, String>? = null,
        body: Map<String, Any?>? = null,
        headers: Map<String, String>? = null,
    ): JsonElement? = raw.send(method, path, query = query, body = body, headers = headers)

    override fun close() {
        if (owned) raw.close()
    }
}

fun createClient(
    url: String,
    authStore: AuthStore = MemoryAuthStore(),
    autoRefresh: Boolean = false,
    authCollection: String? = "profiles",
    accountId: String? = null,
    lang: String? = null,
    maxRetries: Int = 3,
    httpClient: HttpClient? = null,
    onRealtimeError: ((String) -> Unit)? = null,
): ZbClient =
    ZbClient(
        ZigbaseClient(
            url,
            authStore = authStore,
            autoRefresh = autoRefresh,
            authCollection = authCollection,
            accountId = accountId,
            lang = lang,
            maxRetries = maxRetries,
            httpClient = httpClient,
            onRealtimeError = onRealtimeError,
        ),
        owned = true,
    )
