// GENERATED by zigbase — do not edit.
// schema-hash: 097ea715a9163fd9
//
// A thin, schema-aware wrapper over the base Dart SDK. Import both this
// file and package:zigbase_client/typed.dart (the generic typed runtime).
// Regenerate with `zig build gen-dating-dart-client`, then `dart format` it
// with the consuming package's language version (resolved from the package
// config; without one, pass --language-version — style differs by version).
//
// Identifier mapping: a schema name that is a Dart reserved word or would
// shadow a generated/Object member gets a trailing `_` on the DART side
// only (field `default` -> member `default_`); wire keys are unchanged.
// ignore_for_file: non_constant_identifier_names, constant_identifier_names, unused_element, unused_import, unnecessary_import, unused_field, prefer_const_constructors

import 'package:zigbase_client/zigbase_client.dart';
import 'package:zigbase_client/typed.dart';
import 'package:http/http.dart' show MultipartFile;

// ---- Records ----

enum ProfileGender {
  female('female'),
  male('male'),
  nonbinary('nonbinary'),
  other('other');

  const ProfileGender(this.wire);
  final String wire;
  static ProfileGender? fromWire(Object? v) {
    for (final e in ProfileGender.values) {
      if (e.wire == v) return e;
    }
    return null;
  }
}

enum SubscriptionPlan {
  free('free'),
  plus('plus'),
  premium('premium');

  const SubscriptionPlan(this.wire);
  final String wire;
  static SubscriptionPlan? fromWire(Object? v) {
    for (final e in SubscriptionPlan.values) {
      if (e.wire == v) return e;
    }
    return null;
  }
}

class Profile {
  Profile.fromRecord(ZbRecord r)
      : id = coerceString(r['id']),
        email = coerceString(r['email']),
        username = coerceString(r['username']),
        verified = coerceBool(r['verified']),
        name = coerceString(r['name']),
        bio = coerceString(r['bio']),
        website = coerceString(r['website']),
        age = coerceInt(r['age']),
        gender = ProfileGender.fromWire(r['gender']),
        avatar = coerceString(r['avatar']),
        created = coerceString(r['created']),
        updated = coerceString(r['updated']);

  factory Profile.fromJson(Map<String, dynamic> json) =>
      Profile.fromRecord(ZbRecord(json));

  final String id;
  final String email;
  final String username;
  final bool verified;
  final String name;
  final String bio;
  final String website;
  final int age;
  final ProfileGender? gender;
  final String avatar;
  final String created;
  final String updated;
}

class Tag {
  Tag.fromRecord(ZbRecord r)
      : id = coerceString(r['id']),
        label = coerceString(r['label']),
        created = coerceString(r['created']),
        updated = coerceString(r['updated']);

  factory Tag.fromJson(Map<String, dynamic> json) =>
      Tag.fromRecord(ZbRecord(json));

  final String id;
  final String label;
  final String created;
  final String updated;
}

class Photo {
  Photo.fromRecord(ZbRecord r)
      : id = coerceString(r['id']),
        owner = coerceString(r['owner']),
        image = coerceString(r['image']),
        caption = coerceString(r['caption']),
        tags = coerceStringList(r['tags']),
        created = coerceString(r['created']),
        updated = coerceString(r['updated']),
        expand = PhotoExpand.fromRecord(r);

  factory Photo.fromJson(Map<String, dynamic> json) =>
      Photo.fromRecord(ZbRecord(json));

  final String id;
  final String owner;
  final String image;
  final String caption;
  final List<String> tags;
  final String created;
  final String updated;
  final PhotoExpand expand;
}

class PhotoExpand {
  PhotoExpand.fromRecord(ZbRecord r)
      : owner = expandOne<Profile>(r, 'owner', Profile.fromRecord),
        tags = expandMany<Tag>(r, 'tags', Tag.fromRecord);

  final Profile? owner;
  final List<Tag> tags;
}

class PrivatePhoto {
  PrivatePhoto.fromRecord(ZbRecord r)
      : id = coerceString(r['id']),
        owner = coerceString(r['owner']),
        image = coerceString(r['image']),
        caption = coerceString(r['caption']),
        created = coerceString(r['created']),
        updated = coerceString(r['updated']),
        expand = PrivatePhotoExpand.fromRecord(r);

  factory PrivatePhoto.fromJson(Map<String, dynamic> json) =>
      PrivatePhoto.fromRecord(ZbRecord(json));

  final String id;
  final String owner;
  final String image;
  final String caption;
  final String created;
  final String updated;
  final PrivatePhotoExpand expand;
}

class PrivatePhotoExpand {
  PrivatePhotoExpand.fromRecord(ZbRecord r)
      : owner = expandOne<Profile>(r, 'owner', Profile.fromRecord);

  final Profile? owner;
}

class Message {
  Message.fromRecord(ZbRecord r)
      : id = coerceString(r['id']),
        from = coerceString(r['from']),
        to = coerceString(r['to']),
        body = coerceString(r['body']),
        sentAt = coerceString(r['sentAt']),
        read = coerceBool(r['read']),
        created = coerceString(r['created']),
        updated = coerceString(r['updated']),
        expand = MessageExpand.fromRecord(r);

  factory Message.fromJson(Map<String, dynamic> json) =>
      Message.fromRecord(ZbRecord(json));

  final String id;
  final String from;
  final String to;
  final String body;
  final String sentAt;
  final bool read;
  final String created;
  final String updated;
  final MessageExpand expand;
}

class MessageExpand {
  MessageExpand.fromRecord(ZbRecord r)
      : from = expandOne<Profile>(r, 'from', Profile.fromRecord),
        to = expandOne<Profile>(r, 'to', Profile.fromRecord);

  final Profile? from;
  final Profile? to;
}

class Wink {
  Wink.fromRecord(ZbRecord r)
      : id = coerceString(r['id']),
        from = coerceString(r['from']),
        to = coerceString(r['to']),
        createdAt = coerceString(r['createdAt']),
        created = coerceString(r['created']),
        updated = coerceString(r['updated']),
        expand = WinkExpand.fromRecord(r);

  factory Wink.fromJson(Map<String, dynamic> json) =>
      Wink.fromRecord(ZbRecord(json));

  final String id;
  final String from;
  final String to;
  final String createdAt;
  final String created;
  final String updated;
  final WinkExpand expand;
}

class WinkExpand {
  WinkExpand.fromRecord(ZbRecord r)
      : from = expandOne<Profile>(r, 'from', Profile.fromRecord),
        to = expandOne<Profile>(r, 'to', Profile.fromRecord);

  final Profile? from;
  final Profile? to;
}

class Subscription {
  Subscription.fromRecord(ZbRecord r)
      : id = coerceString(r['id']),
        profile = coerceString(r['profile']),
        plan = SubscriptionPlan.fromWire(r['plan']),
        price = coerceDouble(r['price']),
        renewsAt = coerceString(r['renewsAt']),
        active = coerceBool(r['active']),
        metadata = r['metadata'],
        created = coerceString(r['created']),
        updated = coerceString(r['updated']),
        expand = SubscriptionExpand.fromRecord(r);

  factory Subscription.fromJson(Map<String, dynamic> json) =>
      Subscription.fromRecord(ZbRecord(json));

  final String id;
  final String profile;
  final SubscriptionPlan? plan;
  final double price;
  final String renewsAt;
  final bool active;
  final Object? metadata;
  final String created;
  final String updated;
  final SubscriptionExpand expand;
}

class SubscriptionExpand {
  SubscriptionExpand.fromRecord(ZbRecord r)
      : profile = expandOne<Profile>(r, 'profile', Profile.fromRecord);

  final Profile? profile;
}

class Note {
  Note.fromRecord(ZbRecord r)
      : id = coerceString(r['id']),
        account = coerceString(r['account']),
        title = coerceString(r['title']),
        body = coerceString(r['body']),
        attachment = coerceString(r['attachment']),
        created = coerceString(r['created']),
        updated = coerceString(r['updated']);

  factory Note.fromJson(Map<String, dynamic> json) =>
      Note.fromRecord(ZbRecord(json));

  final String id;
  final String account;
  final String title;
  final String body;
  final String attachment;
  final String created;
  final String updated;
}

// ---- Create / Update payloads ----

class ProfileCreate {
  const ProfileCreate({
    required this.email,
    required this.password,
    required this.passwordConfirm,
    this.name,
    this.bio,
    this.website,
    this.age,
    this.gender,
    this.avatar,
  });

  final String email;
  final String password;
  final String passwordConfirm;
  final String? name;
  final String? bio;
  final String? website;
  final int? age;
  final ProfileGender? gender;
  final MultipartFile? avatar;

  Map<String, dynamic> toMap() => {
        'email': email,
        'password': password,
        'passwordConfirm': passwordConfirm,
        if (name != null) 'name': name,
        if (bio != null) 'bio': bio,
        if (website != null) 'website': website,
        if (age != null) 'age': encodeInt(age),
        if (gender != null) 'gender': gender!.wire,
        if (avatar != null) 'avatar': avatar,
      };
}

class ProfileUpdate {
  const ProfileUpdate({
    this.email,
    this.name,
    this.bio,
    this.website,
    this.age,
    this.gender,
    this.avatar,
  });

  final String? email;
  final String? name;
  final String? bio;
  final String? website;
  final int? age;
  final ProfileGender? gender;
  final MultipartFile? avatar;

  Map<String, dynamic> toMap() => {
        if (email != null) 'email': email,
        if (name != null) 'name': name,
        if (bio != null) 'bio': bio,
        if (website != null) 'website': website,
        if (age != null) 'age': encodeInt(age),
        if (gender != null) 'gender': gender!.wire,
        if (avatar != null) 'avatar': avatar,
      };
}

class TagCreate {
  const TagCreate({
    required this.label,
  });

  final String label;

  Map<String, dynamic> toMap() => {
        'label': label,
      };
}

class TagUpdate {
  const TagUpdate({
    this.label,
  });

  final String? label;

  Map<String, dynamic> toMap() => {
        if (label != null) 'label': label,
      };
}

class PhotoCreate {
  const PhotoCreate({
    this.owner,
    this.image,
    this.caption,
    this.tags,
  });

  final String? owner;
  final MultipartFile? image;
  final String? caption;
  final List<String>? tags;

  Map<String, dynamic> toMap() => {
        if (owner != null) 'owner': owner,
        if (image != null) 'image': image,
        if (caption != null) 'caption': caption,
        if (tags != null) 'tags': tags,
      };
}

class PhotoUpdate {
  const PhotoUpdate({
    this.owner,
    this.image,
    this.caption,
    this.tags,
  });

  final String? owner;
  final MultipartFile? image;
  final String? caption;
  final List<String>? tags;

  Map<String, dynamic> toMap() => {
        if (owner != null) 'owner': owner,
        if (image != null) 'image': image,
        if (caption != null) 'caption': caption,
        if (tags != null) 'tags': tags,
      };
}

class PrivatePhotoCreate {
  const PrivatePhotoCreate({
    this.owner,
    this.image,
    this.caption,
  });

  final String? owner;
  final MultipartFile? image;
  final String? caption;

  Map<String, dynamic> toMap() => {
        if (owner != null) 'owner': owner,
        if (image != null) 'image': image,
        if (caption != null) 'caption': caption,
      };
}

class PrivatePhotoUpdate {
  const PrivatePhotoUpdate({
    this.owner,
    this.image,
    this.caption,
  });

  final String? owner;
  final MultipartFile? image;
  final String? caption;

  Map<String, dynamic> toMap() => {
        if (owner != null) 'owner': owner,
        if (image != null) 'image': image,
        if (caption != null) 'caption': caption,
      };
}

class MessageCreate {
  const MessageCreate({
    required this.body,
    this.from,
    this.to,
    this.sentAt,
    this.read,
  });

  final String? from;
  final String? to;
  final String body;
  final String? sentAt;
  final bool? read;

  Map<String, dynamic> toMap() => {
        if (from != null) 'from': from,
        if (to != null) 'to': to,
        'body': body,
        if (sentAt != null) 'sentAt': sentAt,
        if (read != null) 'read': read,
      };
}

class MessageUpdate {
  const MessageUpdate({
    this.from,
    this.to,
    this.body,
    this.sentAt,
    this.read,
  });

  final String? from;
  final String? to;
  final String? body;
  final String? sentAt;
  final bool? read;

  Map<String, dynamic> toMap() => {
        if (from != null) 'from': from,
        if (to != null) 'to': to,
        if (body != null) 'body': body,
        if (sentAt != null) 'sentAt': sentAt,
        if (read != null) 'read': read,
      };
}

class WinkCreate {
  const WinkCreate({
    this.from,
    this.to,
    this.createdAt,
  });

  final String? from;
  final String? to;
  final String? createdAt;

  Map<String, dynamic> toMap() => {
        if (from != null) 'from': from,
        if (to != null) 'to': to,
        if (createdAt != null) 'createdAt': createdAt,
      };
}

class WinkUpdate {
  const WinkUpdate({
    this.from,
    this.to,
    this.createdAt,
  });

  final String? from;
  final String? to;
  final String? createdAt;

  Map<String, dynamic> toMap() => {
        if (from != null) 'from': from,
        if (to != null) 'to': to,
        if (createdAt != null) 'createdAt': createdAt,
      };
}

class SubscriptionCreate {
  const SubscriptionCreate({
    this.profile,
    this.plan,
    this.price,
    this.renewsAt,
    this.active,
    this.metadata,
  });

  final String? profile;
  final SubscriptionPlan? plan;
  final double? price;
  final String? renewsAt;
  final bool? active;
  final Object? metadata;

  Map<String, dynamic> toMap() => {
        if (profile != null) 'profile': profile,
        if (plan != null) 'plan': plan!.wire,
        if (price != null) 'price': encodeFixed(price, 2),
        if (renewsAt != null) 'renewsAt': renewsAt,
        if (active != null) 'active': active,
        if (metadata != null) 'metadata': metadata,
      };
}

class SubscriptionUpdate {
  const SubscriptionUpdate({
    this.profile,
    this.plan,
    this.price,
    this.renewsAt,
    this.active,
    this.metadata,
  });

  final String? profile;
  final SubscriptionPlan? plan;
  final double? price;
  final String? renewsAt;
  final bool? active;
  final Object? metadata;

  Map<String, dynamic> toMap() => {
        if (profile != null) 'profile': profile,
        if (plan != null) 'plan': plan!.wire,
        if (price != null) 'price': encodeFixed(price, 2),
        if (renewsAt != null) 'renewsAt': renewsAt,
        if (active != null) 'active': active,
        if (metadata != null) 'metadata': metadata,
      };
}

class NoteCreate {
  const NoteCreate({
    required this.title,
    this.body,
    this.attachment,
  });

  final String title;
  final String? body;
  final MultipartFile? attachment;

  Map<String, dynamic> toMap() => {
        'title': title,
        if (body != null) 'body': body,
        if (attachment != null) 'attachment': attachment,
      };
}

class NoteUpdate {
  const NoteUpdate({
    this.title,
    this.body,
    this.attachment,
  });

  final String? title;
  final String? body;
  final MultipartFile? attachment;

  Map<String, dynamic> toMap() => {
        if (title != null) 'title': title,
        if (body != null) 'body': body,
        if (attachment != null) 'attachment': attachment,
      };
}

// ---- Fluent field builders ----

class ProfileFields {
  ProfileFields([this._p = '']);
  final String _p;
  StringFieldExpr get email => StringFieldExpr('${_p}email');
  StringFieldExpr get username => StringFieldExpr('${_p}username');
  BoolFieldExpr get verified => BoolFieldExpr('${_p}verified');
  StringFieldExpr get name => StringFieldExpr('${_p}name');
  StringFieldExpr get bio => StringFieldExpr('${_p}bio');
  StringFieldExpr get website => StringFieldExpr('${_p}website');
  NumFieldExpr get age => NumFieldExpr('${_p}age');
  EnumFieldExpr<ProfileGender> get gender =>
      EnumFieldExpr<ProfileGender>('${_p}gender', (e) => e.wire);
  StringFieldExpr get id => StringFieldExpr('${_p}id');
  StringFieldExpr get created => StringFieldExpr('${_p}created');
  StringFieldExpr get updated => StringFieldExpr('${_p}updated');
}

class TagFields {
  TagFields([this._p = '']);
  final String _p;
  StringFieldExpr get label => StringFieldExpr('${_p}label');
  StringFieldExpr get id => StringFieldExpr('${_p}id');
  StringFieldExpr get created => StringFieldExpr('${_p}created');
  StringFieldExpr get updated => StringFieldExpr('${_p}updated');
}

class PhotoFields {
  PhotoFields([this._p = '']);
  final String _p;
  RelFieldExpr<ProfileFields> get owner =>
      RelFieldExpr<ProfileFields>('${_p}owner', (p) => ProfileFields(p));
  StringFieldExpr get caption => StringFieldExpr('${_p}caption');
  RelFieldExpr<TagFields> get tags =>
      RelFieldExpr<TagFields>('${_p}tags', (p) => TagFields(p));
  StringFieldExpr get id => StringFieldExpr('${_p}id');
  StringFieldExpr get created => StringFieldExpr('${_p}created');
  StringFieldExpr get updated => StringFieldExpr('${_p}updated');
}

class PrivatePhotoFields {
  PrivatePhotoFields([this._p = '']);
  final String _p;
  RelFieldExpr<ProfileFields> get owner =>
      RelFieldExpr<ProfileFields>('${_p}owner', (p) => ProfileFields(p));
  StringFieldExpr get caption => StringFieldExpr('${_p}caption');
  StringFieldExpr get id => StringFieldExpr('${_p}id');
  StringFieldExpr get created => StringFieldExpr('${_p}created');
  StringFieldExpr get updated => StringFieldExpr('${_p}updated');
}

class MessageFields {
  MessageFields([this._p = '']);
  final String _p;
  RelFieldExpr<ProfileFields> get from =>
      RelFieldExpr<ProfileFields>('${_p}from', (p) => ProfileFields(p));
  RelFieldExpr<ProfileFields> get to =>
      RelFieldExpr<ProfileFields>('${_p}to', (p) => ProfileFields(p));
  StringFieldExpr get body => StringFieldExpr('${_p}body');
  StringFieldExpr get sentAt => StringFieldExpr('${_p}sentAt');
  BoolFieldExpr get read => BoolFieldExpr('${_p}read');
  StringFieldExpr get id => StringFieldExpr('${_p}id');
  StringFieldExpr get created => StringFieldExpr('${_p}created');
  StringFieldExpr get updated => StringFieldExpr('${_p}updated');
}

class WinkFields {
  WinkFields([this._p = '']);
  final String _p;
  RelFieldExpr<ProfileFields> get from =>
      RelFieldExpr<ProfileFields>('${_p}from', (p) => ProfileFields(p));
  RelFieldExpr<ProfileFields> get to =>
      RelFieldExpr<ProfileFields>('${_p}to', (p) => ProfileFields(p));
  StringFieldExpr get createdAt => StringFieldExpr('${_p}createdAt');
  StringFieldExpr get id => StringFieldExpr('${_p}id');
  StringFieldExpr get created => StringFieldExpr('${_p}created');
  StringFieldExpr get updated => StringFieldExpr('${_p}updated');
}

class SubscriptionFields {
  SubscriptionFields([this._p = '']);
  final String _p;
  RelFieldExpr<ProfileFields> get profile =>
      RelFieldExpr<ProfileFields>('${_p}profile', (p) => ProfileFields(p));
  EnumFieldExpr<SubscriptionPlan> get plan =>
      EnumFieldExpr<SubscriptionPlan>('${_p}plan', (e) => e.wire);
  NumFieldExpr get price => NumFieldExpr('${_p}price');
  StringFieldExpr get renewsAt => StringFieldExpr('${_p}renewsAt');
  BoolFieldExpr get active => BoolFieldExpr('${_p}active');
  StringFieldExpr get id => StringFieldExpr('${_p}id');
  StringFieldExpr get created => StringFieldExpr('${_p}created');
  StringFieldExpr get updated => StringFieldExpr('${_p}updated');
}

class NoteFields {
  NoteFields([this._p = '']);
  final String _p;
  FieldExpr<String> get account => FieldExpr<String>('${_p}account');
  StringFieldExpr get title => StringFieldExpr('${_p}title');
  StringFieldExpr get body => StringFieldExpr('${_p}body');
  StringFieldExpr get id => StringFieldExpr('${_p}id');
  StringFieldExpr get created => StringFieldExpr('${_p}created');
  StringFieldExpr get updated => StringFieldExpr('${_p}updated');
}

// ---- Per-collection metadata ----

const CollectionMeta profilesMeta = CollectionMeta(
  name: 'profiles',
  fields: {
    'id': FieldMeta(type: FieldType.text),
    'email': FieldMeta(type: FieldType.email),
    'username': FieldMeta(type: FieldType.text),
    'verified': FieldMeta(type: FieldType.boolean),
    'name': FieldMeta(type: FieldType.text),
    'bio': FieldMeta(type: FieldType.editor),
    'website': FieldMeta(type: FieldType.url),
    'age': FieldMeta(type: FieldType.number, mode: NumberMode.integer),
    'gender': FieldMeta(type: FieldType.select),
    'avatar': FieldMeta(type: FieldType.file),
    'created': FieldMeta(type: FieldType.autodate),
    'updated': FieldMeta(type: FieldType.autodate),
  },
  fileFields: ['avatar'],
  expandable: [],
  isAuth: true,
  searchable: ['bio'],
);

const CollectionMeta tagsMeta = CollectionMeta(
  name: 'tags',
  fields: {
    'id': FieldMeta(type: FieldType.text),
    'label': FieldMeta(type: FieldType.text),
    'created': FieldMeta(type: FieldType.autodate),
    'updated': FieldMeta(type: FieldType.autodate),
  },
  fileFields: [],
  expandable: [],
  isAuth: false,
);

const CollectionMeta photosMeta = CollectionMeta(
  name: 'photos',
  fields: {
    'id': FieldMeta(type: FieldType.text),
    'owner': FieldMeta(type: FieldType.relation),
    'image': FieldMeta(type: FieldType.file),
    'caption': FieldMeta(type: FieldType.text),
    'tags': FieldMeta(type: FieldType.relation, multi: true),
    'created': FieldMeta(type: FieldType.autodate),
    'updated': FieldMeta(type: FieldType.autodate),
  },
  fileFields: ['image'],
  expandable: ['owner', 'tags'],
  isAuth: false,
);

const CollectionMeta privatePhotosMeta = CollectionMeta(
  name: 'privatePhotos',
  fields: {
    'id': FieldMeta(type: FieldType.text),
    'owner': FieldMeta(type: FieldType.relation),
    'image': FieldMeta(type: FieldType.file),
    'caption': FieldMeta(type: FieldType.text),
    'created': FieldMeta(type: FieldType.autodate),
    'updated': FieldMeta(type: FieldType.autodate),
  },
  fileFields: ['image'],
  expandable: ['owner'],
  isAuth: false,
);

const CollectionMeta messagesMeta = CollectionMeta(
  name: 'messages',
  fields: {
    'id': FieldMeta(type: FieldType.text),
    'from': FieldMeta(type: FieldType.relation),
    'to': FieldMeta(type: FieldType.relation),
    'body': FieldMeta(type: FieldType.text),
    'sentAt': FieldMeta(type: FieldType.autodate),
    'read': FieldMeta(type: FieldType.boolean),
    'created': FieldMeta(type: FieldType.autodate),
    'updated': FieldMeta(type: FieldType.autodate),
  },
  fileFields: [],
  expandable: ['from', 'to'],
  isAuth: false,
  searchable: ['body'],
);

const CollectionMeta winksMeta = CollectionMeta(
  name: 'winks',
  fields: {
    'id': FieldMeta(type: FieldType.text),
    'from': FieldMeta(type: FieldType.relation),
    'to': FieldMeta(type: FieldType.relation),
    'createdAt': FieldMeta(type: FieldType.autodate),
    'created': FieldMeta(type: FieldType.autodate),
    'updated': FieldMeta(type: FieldType.autodate),
  },
  fileFields: [],
  expandable: ['from', 'to'],
  isAuth: false,
);

const CollectionMeta subscriptionsMeta = CollectionMeta(
  name: 'subscriptions',
  fields: {
    'id': FieldMeta(type: FieldType.text),
    'profile': FieldMeta(type: FieldType.relation),
    'plan': FieldMeta(type: FieldType.select),
    'price':
        FieldMeta(type: FieldType.number, mode: NumberMode.fixed, scale: 2),
    'renewsAt': FieldMeta(type: FieldType.date),
    'active': FieldMeta(type: FieldType.boolean),
    'metadata': FieldMeta(type: FieldType.json),
    'created': FieldMeta(type: FieldType.autodate),
    'updated': FieldMeta(type: FieldType.autodate),
  },
  fileFields: [],
  expandable: ['profile'],
  isAuth: false,
);

const CollectionMeta notesMeta = CollectionMeta(
  name: 'notes',
  fields: {
    'id': FieldMeta(type: FieldType.text),
    'account': FieldMeta(type: FieldType.relation),
    'title': FieldMeta(type: FieldType.text),
    'body': FieldMeta(type: FieldType.text),
    'attachment': FieldMeta(type: FieldType.file),
    'created': FieldMeta(type: FieldType.autodate),
    'updated': FieldMeta(type: FieldType.autodate),
  },
  fileFields: ['attachment'],
  expandable: ['account'],
  isAuth: false,
  tenant: 'account',
);

// ---- Typed services ----

class ProfilesService {
  ProfilesService(ZigbaseClient client)
      : _c = TypedCollection<Profile>(client, profilesMeta, Profile.fromRecord);
  final TypedCollection<Profile> _c;

  Future<TypedList<Profile>> getList({
    Expr Function(ProfileFields)? where,
    Object? sort,
    List<String>? expand,
    int page = 1,
    int perPage = 30,
    String? fields,
    bool skipTotal = false,
    String? search,
    String? requestKey,
  }) =>
      _c.getList(
        filter: where == null ? null : where(ProfileFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        page: page,
        perPage: perPage,
        fields: fields,
        skipTotal: skipTotal,
        search: search,
        requestKey: requestKey,
      );

  Future<Profile> getOne(String id,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getOne(id, expand: expand, fields: fields, requestKey: requestKey);

  Future<Profile> getFirstListItem(Expr Function(ProfileFields) where,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getFirstListItem(where(ProfileFields()).compile(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<TypedCursorPage<Profile>> getPage({
    Expr Function(ProfileFields)? where,
    Object? sort,
    List<String>? expand,
    String? cursor,
    int limit = 30,
    bool withTotal = false,
    String? fields,
    String? search,
    String? requestKey,
  }) =>
      _c.getPage(
        filter: where == null ? null : where(ProfileFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        cursor: cursor,
        limit: limit,
        withTotal: withTotal,
        fields: fields,
        search: search,
        requestKey: requestKey,
      );

  Stream<Profile> iterate({
    Expr Function(ProfileFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.iterate(
        filter: where == null ? null : where(ProfileFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<List<Profile>> getFullList({
    Expr Function(ProfileFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.getFullList(
        filter: where == null ? null : where(ProfileFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<Profile> create(ProfileCreate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.create(data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<Profile> update(String id, ProfileUpdate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.update(id, data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<void> delete(String id) => _c.delete(id);

  /// Compile a typed filter expression to a server filter string.
  String filter(Expr Function(ProfileFields) fn) =>
      fn(ProfileFields()).compile();

  Future<AuthResponse> authWithPassword(String identity, String password) =>
      _c.collection.authWithPassword(identity, password);

  String fileUrl(Profile record,
      {required ProfileFileField field,
      bool download = false,
      String? thumb,
      String? token}) {
    final filename = switch (field) {
      ProfileFileField.avatar => record.avatar,
    };
    return _c.fileUrl(
      ZbRecord({'id': record.id, 'collectionName': 'profiles'}),
      filename,
      download: download,
      thumb: thumb,
      token: token,
    );
  }
}

enum ProfileFileField { avatar }

class TagsService {
  TagsService(ZigbaseClient client)
      : _c = TypedCollection<Tag>(client, tagsMeta, Tag.fromRecord);
  final TypedCollection<Tag> _c;

  Future<TypedList<Tag>> getList({
    Expr Function(TagFields)? where,
    Object? sort,
    List<String>? expand,
    int page = 1,
    int perPage = 30,
    String? fields,
    bool skipTotal = false,
    String? search,
    String? requestKey,
  }) =>
      _c.getList(
        filter: where == null ? null : where(TagFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        page: page,
        perPage: perPage,
        fields: fields,
        skipTotal: skipTotal,
        search: search,
        requestKey: requestKey,
      );

  Future<Tag> getOne(String id,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getOne(id, expand: expand, fields: fields, requestKey: requestKey);

  Future<Tag> getFirstListItem(Expr Function(TagFields) where,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getFirstListItem(where(TagFields()).compile(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<TypedCursorPage<Tag>> getPage({
    Expr Function(TagFields)? where,
    Object? sort,
    List<String>? expand,
    String? cursor,
    int limit = 30,
    bool withTotal = false,
    String? fields,
    String? search,
    String? requestKey,
  }) =>
      _c.getPage(
        filter: where == null ? null : where(TagFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        cursor: cursor,
        limit: limit,
        withTotal: withTotal,
        fields: fields,
        search: search,
        requestKey: requestKey,
      );

  Stream<Tag> iterate({
    Expr Function(TagFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.iterate(
        filter: where == null ? null : where(TagFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<List<Tag>> getFullList({
    Expr Function(TagFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.getFullList(
        filter: where == null ? null : where(TagFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<Tag> create(TagCreate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.create(data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<Tag> update(String id, TagUpdate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.update(id, data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<void> delete(String id) => _c.delete(id);

  /// Compile a typed filter expression to a server filter string.
  String filter(Expr Function(TagFields) fn) => fn(TagFields()).compile();
}

class PhotosService {
  PhotosService(ZigbaseClient client)
      : _c = TypedCollection<Photo>(client, photosMeta, Photo.fromRecord);
  final TypedCollection<Photo> _c;

  Future<TypedList<Photo>> getList({
    Expr Function(PhotoFields)? where,
    Object? sort,
    List<String>? expand,
    int page = 1,
    int perPage = 30,
    String? fields,
    bool skipTotal = false,
    String? search,
    String? requestKey,
  }) =>
      _c.getList(
        filter: where == null ? null : where(PhotoFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        page: page,
        perPage: perPage,
        fields: fields,
        skipTotal: skipTotal,
        search: search,
        requestKey: requestKey,
      );

  Future<Photo> getOne(String id,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getOne(id, expand: expand, fields: fields, requestKey: requestKey);

  Future<Photo> getFirstListItem(Expr Function(PhotoFields) where,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getFirstListItem(where(PhotoFields()).compile(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<TypedCursorPage<Photo>> getPage({
    Expr Function(PhotoFields)? where,
    Object? sort,
    List<String>? expand,
    String? cursor,
    int limit = 30,
    bool withTotal = false,
    String? fields,
    String? search,
    String? requestKey,
  }) =>
      _c.getPage(
        filter: where == null ? null : where(PhotoFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        cursor: cursor,
        limit: limit,
        withTotal: withTotal,
        fields: fields,
        search: search,
        requestKey: requestKey,
      );

  Stream<Photo> iterate({
    Expr Function(PhotoFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.iterate(
        filter: where == null ? null : where(PhotoFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<List<Photo>> getFullList({
    Expr Function(PhotoFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.getFullList(
        filter: where == null ? null : where(PhotoFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<Photo> create(PhotoCreate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.create(data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<Photo> update(String id, PhotoUpdate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.update(id, data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<void> delete(String id) => _c.delete(id);

  /// Compile a typed filter expression to a server filter string.
  String filter(Expr Function(PhotoFields) fn) => fn(PhotoFields()).compile();

  String fileUrl(Photo record,
      {required PhotoFileField field,
      bool download = false,
      String? thumb,
      String? token}) {
    final filename = switch (field) {
      PhotoFileField.image => record.image,
    };
    return _c.fileUrl(
      ZbRecord({'id': record.id, 'collectionName': 'photos'}),
      filename,
      download: download,
      thumb: thumb,
      token: token,
    );
  }
}

enum PhotoFileField { image }

class PrivatePhotosService {
  PrivatePhotosService(ZigbaseClient client)
      : _c = TypedCollection<PrivatePhoto>(
            client, privatePhotosMeta, PrivatePhoto.fromRecord);
  final TypedCollection<PrivatePhoto> _c;

  Future<TypedList<PrivatePhoto>> getList({
    Expr Function(PrivatePhotoFields)? where,
    Object? sort,
    List<String>? expand,
    int page = 1,
    int perPage = 30,
    String? fields,
    bool skipTotal = false,
    String? search,
    String? requestKey,
  }) =>
      _c.getList(
        filter: where == null ? null : where(PrivatePhotoFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        page: page,
        perPage: perPage,
        fields: fields,
        skipTotal: skipTotal,
        search: search,
        requestKey: requestKey,
      );

  Future<PrivatePhoto> getOne(String id,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getOne(id, expand: expand, fields: fields, requestKey: requestKey);

  Future<PrivatePhoto> getFirstListItem(Expr Function(PrivatePhotoFields) where,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getFirstListItem(where(PrivatePhotoFields()).compile(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<TypedCursorPage<PrivatePhoto>> getPage({
    Expr Function(PrivatePhotoFields)? where,
    Object? sort,
    List<String>? expand,
    String? cursor,
    int limit = 30,
    bool withTotal = false,
    String? fields,
    String? search,
    String? requestKey,
  }) =>
      _c.getPage(
        filter: where == null ? null : where(PrivatePhotoFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        cursor: cursor,
        limit: limit,
        withTotal: withTotal,
        fields: fields,
        search: search,
        requestKey: requestKey,
      );

  Stream<PrivatePhoto> iterate({
    Expr Function(PrivatePhotoFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.iterate(
        filter: where == null ? null : where(PrivatePhotoFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<List<PrivatePhoto>> getFullList({
    Expr Function(PrivatePhotoFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.getFullList(
        filter: where == null ? null : where(PrivatePhotoFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<PrivatePhoto> create(PrivatePhotoCreate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.create(data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<PrivatePhoto> update(String id, PrivatePhotoUpdate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.update(id, data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<void> delete(String id) => _c.delete(id);

  /// Compile a typed filter expression to a server filter string.
  String filter(Expr Function(PrivatePhotoFields) fn) =>
      fn(PrivatePhotoFields()).compile();

  String fileUrl(PrivatePhoto record,
      {required PrivatePhotoFileField field,
      bool download = false,
      String? thumb,
      String? token}) {
    final filename = switch (field) {
      PrivatePhotoFileField.image => record.image,
    };
    return _c.fileUrl(
      ZbRecord({'id': record.id, 'collectionName': 'privatePhotos'}),
      filename,
      download: download,
      thumb: thumb,
      token: token,
    );
  }
}

enum PrivatePhotoFileField { image }

class MessagesService {
  MessagesService(ZigbaseClient client)
      : _c = TypedCollection<Message>(client, messagesMeta, Message.fromRecord);
  final TypedCollection<Message> _c;

  Future<TypedList<Message>> getList({
    Expr Function(MessageFields)? where,
    Object? sort,
    List<String>? expand,
    int page = 1,
    int perPage = 30,
    String? fields,
    bool skipTotal = false,
    String? search,
    String? requestKey,
  }) =>
      _c.getList(
        filter: where == null ? null : where(MessageFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        page: page,
        perPage: perPage,
        fields: fields,
        skipTotal: skipTotal,
        search: search,
        requestKey: requestKey,
      );

  Future<Message> getOne(String id,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getOne(id, expand: expand, fields: fields, requestKey: requestKey);

  Future<Message> getFirstListItem(Expr Function(MessageFields) where,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getFirstListItem(where(MessageFields()).compile(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<TypedCursorPage<Message>> getPage({
    Expr Function(MessageFields)? where,
    Object? sort,
    List<String>? expand,
    String? cursor,
    int limit = 30,
    bool withTotal = false,
    String? fields,
    String? search,
    String? requestKey,
  }) =>
      _c.getPage(
        filter: where == null ? null : where(MessageFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        cursor: cursor,
        limit: limit,
        withTotal: withTotal,
        fields: fields,
        search: search,
        requestKey: requestKey,
      );

  Stream<Message> iterate({
    Expr Function(MessageFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.iterate(
        filter: where == null ? null : where(MessageFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<List<Message>> getFullList({
    Expr Function(MessageFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.getFullList(
        filter: where == null ? null : where(MessageFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<Message> create(MessageCreate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.create(data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<Message> update(String id, MessageUpdate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.update(id, data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<void> delete(String id) => _c.delete(id);

  /// Compile a typed filter expression to a server filter string.
  String filter(Expr Function(MessageFields) fn) =>
      fn(MessageFields()).compile();
}

class WinksService {
  WinksService(ZigbaseClient client)
      : _c = TypedCollection<Wink>(client, winksMeta, Wink.fromRecord);
  final TypedCollection<Wink> _c;

  Future<TypedList<Wink>> getList({
    Expr Function(WinkFields)? where,
    Object? sort,
    List<String>? expand,
    int page = 1,
    int perPage = 30,
    String? fields,
    bool skipTotal = false,
    String? search,
    String? requestKey,
  }) =>
      _c.getList(
        filter: where == null ? null : where(WinkFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        page: page,
        perPage: perPage,
        fields: fields,
        skipTotal: skipTotal,
        search: search,
        requestKey: requestKey,
      );

  Future<Wink> getOne(String id,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getOne(id, expand: expand, fields: fields, requestKey: requestKey);

  Future<Wink> getFirstListItem(Expr Function(WinkFields) where,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getFirstListItem(where(WinkFields()).compile(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<TypedCursorPage<Wink>> getPage({
    Expr Function(WinkFields)? where,
    Object? sort,
    List<String>? expand,
    String? cursor,
    int limit = 30,
    bool withTotal = false,
    String? fields,
    String? search,
    String? requestKey,
  }) =>
      _c.getPage(
        filter: where == null ? null : where(WinkFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        cursor: cursor,
        limit: limit,
        withTotal: withTotal,
        fields: fields,
        search: search,
        requestKey: requestKey,
      );

  Stream<Wink> iterate({
    Expr Function(WinkFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.iterate(
        filter: where == null ? null : where(WinkFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<List<Wink>> getFullList({
    Expr Function(WinkFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.getFullList(
        filter: where == null ? null : where(WinkFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<Wink> create(WinkCreate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.create(data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<Wink> update(String id, WinkUpdate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.update(id, data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<void> delete(String id) => _c.delete(id);

  /// Compile a typed filter expression to a server filter string.
  String filter(Expr Function(WinkFields) fn) => fn(WinkFields()).compile();
}

class SubscriptionsService {
  SubscriptionsService(ZigbaseClient client)
      : _c = TypedCollection<Subscription>(
            client, subscriptionsMeta, Subscription.fromRecord);
  final TypedCollection<Subscription> _c;

  Future<TypedList<Subscription>> getList({
    Expr Function(SubscriptionFields)? where,
    Object? sort,
    List<String>? expand,
    int page = 1,
    int perPage = 30,
    String? fields,
    bool skipTotal = false,
    String? search,
    String? requestKey,
  }) =>
      _c.getList(
        filter: where == null ? null : where(SubscriptionFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        page: page,
        perPage: perPage,
        fields: fields,
        skipTotal: skipTotal,
        search: search,
        requestKey: requestKey,
      );

  Future<Subscription> getOne(String id,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getOne(id, expand: expand, fields: fields, requestKey: requestKey);

  Future<Subscription> getFirstListItem(Expr Function(SubscriptionFields) where,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getFirstListItem(where(SubscriptionFields()).compile(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<TypedCursorPage<Subscription>> getPage({
    Expr Function(SubscriptionFields)? where,
    Object? sort,
    List<String>? expand,
    String? cursor,
    int limit = 30,
    bool withTotal = false,
    String? fields,
    String? search,
    String? requestKey,
  }) =>
      _c.getPage(
        filter: where == null ? null : where(SubscriptionFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        cursor: cursor,
        limit: limit,
        withTotal: withTotal,
        fields: fields,
        search: search,
        requestKey: requestKey,
      );

  Stream<Subscription> iterate({
    Expr Function(SubscriptionFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.iterate(
        filter: where == null ? null : where(SubscriptionFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<List<Subscription>> getFullList({
    Expr Function(SubscriptionFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.getFullList(
        filter: where == null ? null : where(SubscriptionFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<Subscription> create(SubscriptionCreate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.create(data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<Subscription> update(String id, SubscriptionUpdate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.update(id, data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<void> delete(String id) => _c.delete(id);

  /// Compile a typed filter expression to a server filter string.
  String filter(Expr Function(SubscriptionFields) fn) =>
      fn(SubscriptionFields()).compile();
}

class NotesService {
  NotesService(ZigbaseClient client)
      : _c = TypedCollection<Note>(client, notesMeta, Note.fromRecord);
  final TypedCollection<Note> _c;

  Future<TypedList<Note>> getList({
    Expr Function(NoteFields)? where,
    Object? sort,
    List<String>? expand,
    int page = 1,
    int perPage = 30,
    String? fields,
    bool skipTotal = false,
    String? search,
    String? requestKey,
  }) =>
      _c.getList(
        filter: where == null ? null : where(NoteFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        page: page,
        perPage: perPage,
        fields: fields,
        skipTotal: skipTotal,
        search: search,
        requestKey: requestKey,
      );

  Future<Note> getOne(String id,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getOne(id, expand: expand, fields: fields, requestKey: requestKey);

  Future<Note> getFirstListItem(Expr Function(NoteFields) where,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.getFirstListItem(where(NoteFields()).compile(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<TypedCursorPage<Note>> getPage({
    Expr Function(NoteFields)? where,
    Object? sort,
    List<String>? expand,
    String? cursor,
    int limit = 30,
    bool withTotal = false,
    String? fields,
    String? search,
    String? requestKey,
  }) =>
      _c.getPage(
        filter: where == null ? null : where(NoteFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        cursor: cursor,
        limit: limit,
        withTotal: withTotal,
        fields: fields,
        search: search,
        requestKey: requestKey,
      );

  Stream<Note> iterate({
    Expr Function(NoteFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.iterate(
        filter: where == null ? null : where(NoteFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<List<Note>> getFullList({
    Expr Function(NoteFields)? where,
    Object? sort,
    List<String>? expand,
    int batch = 100,
    String? fields,
    String? search,
  }) =>
      _c.getFullList(
        filter: where == null ? null : where(NoteFields()).compile(),
        sort: normalizeSort(sort),
        expand: expand,
        batch: batch,
        fields: fields,
        search: search,
      );

  Future<Note> create(NoteCreate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.create(data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<Note> update(String id, NoteUpdate data,
          {List<String>? expand, String? fields, String? requestKey}) =>
      _c.update(id, data.toMap(),
          expand: expand, fields: fields, requestKey: requestKey);

  Future<void> delete(String id) => _c.delete(id);

  /// Compile a typed filter expression to a server filter string.
  String filter(Expr Function(NoteFields) fn) => fn(NoteFields()).compile();

  String fileUrl(Note record,
      {required NoteFileField field,
      bool download = false,
      String? thumb,
      String? token}) {
    final filename = switch (field) {
      NoteFileField.attachment => record.attachment,
    };
    return _c.fileUrl(
      ZbRecord({'id': record.id, 'collectionName': 'notes'}),
      filename,
      download: download,
      thumb: thumb,
      token: token,
    );
  }
}

enum NoteFileField { attachment }

// ---- Typed realtime ----

class ProfilesRealtime extends TypedRealtime<Profile> {
  ProfilesRealtime(ZigbaseClient client)
      : super(client, profilesMeta, Profile.fromRecord);
}

class TagsRealtime extends TypedRealtime<Tag> {
  TagsRealtime(ZigbaseClient client) : super(client, tagsMeta, Tag.fromRecord);
}

class PhotosRealtime extends TypedRealtime<Photo> {
  PhotosRealtime(ZigbaseClient client)
      : super(client, photosMeta, Photo.fromRecord);
}

class PrivatePhotosRealtime extends TypedRealtime<PrivatePhoto> {
  PrivatePhotosRealtime(ZigbaseClient client)
      : super(client, privatePhotosMeta, PrivatePhoto.fromRecord);
}

class MessagesRealtime extends TypedRealtime<Message> {
  MessagesRealtime(ZigbaseClient client)
      : super(client, messagesMeta, Message.fromRecord);
}

class WinksRealtime extends TypedRealtime<Wink> {
  WinksRealtime(ZigbaseClient client)
      : super(client, winksMeta, Wink.fromRecord);
}

class SubscriptionsRealtime extends TypedRealtime<Subscription> {
  SubscriptionsRealtime(ZigbaseClient client)
      : super(client, subscriptionsMeta, Subscription.fromRecord);
}

class NotesRealtime extends TypedRealtime<Note> {
  NotesRealtime(ZigbaseClient client)
      : super(client, notesMeta, Note.fromRecord);
}

// ---- Client ----

class ZbClient {
  ZbClient(this.raw, {this.owned = false});

  final ZigbaseClient raw;
  final bool owned;

  late final ProfilesService profiles = ProfilesService(raw);
  late final TagsService tags = TagsService(raw);
  late final PhotosService photos = PhotosService(raw);
  late final PrivatePhotosService privatePhotos = PrivatePhotosService(raw);
  late final MessagesService messages = MessagesService(raw);
  late final WinksService winks = WinksService(raw);
  late final SubscriptionsService subscriptions = SubscriptionsService(raw);
  late final NotesService notes = NotesService(raw);

  late final ProfilesRealtime profilesRealtime = ProfilesRealtime(raw);
  late final TagsRealtime tagsRealtime = TagsRealtime(raw);
  late final PhotosRealtime photosRealtime = PhotosRealtime(raw);
  late final PrivatePhotosRealtime privatePhotosRealtime =
      PrivatePhotosRealtime(raw);
  late final MessagesRealtime messagesRealtime = MessagesRealtime(raw);
  late final WinksRealtime winksRealtime = WinksRealtime(raw);
  late final SubscriptionsRealtime subscriptionsRealtime =
      SubscriptionsRealtime(raw);
  late final NotesRealtime notesRealtime = NotesRealtime(raw);

  AuthStore get authStore => raw.authStore;

  Future<dynamic> send(String method, String path,
          {Map<String, dynamic>? query,
          Object? body,
          Map<String, String>? headers}) =>
      raw.send(method, path, query: query, body: body, headers: headers);

  Future<void> close() => owned ? raw.close() : Future.value();
}

ZbClient createClient(
  String url, {
  AuthStore? authStore,
  bool autoRefresh = false,
  String authCollection = 'profiles',
  String? accountId,
  String? lang,
  WebSocketConnector? webSocketConnector,
}) =>
    ZbClient(
      ZigbaseClient(
        url,
        authStore: authStore,
        autoRefresh: autoRefresh,
        authCollection: authCollection,
        accountId: accountId,
        lang: lang,
        webSocketConnector: webSocketConnector,
      ),
      owned: true,
    );
