// generated by zigbase — do not edit
// schema-hash: 5c43d0adc32c87a6
//
// In a consumer repo this file imports from "@zigbase/client" and
// "@zigbase/client/typed". In this in-repo snapshot we import from the
// package source so it typechecks against the working tree without a built dist.
import { createClient as baseCreateClient, type Client, type SendOptions } from "../../../src/index.js";
import { withRealtime, type RealtimeEnabledClient } from "../../../src/realtime-entry.js";
import type { ListResult } from "../../../src/records.js";
import type { CursorPage } from "../../../src/cursor.js";
import type { FilesService, FileUrlOptions } from "../../../src/files.js";
import {
  makeRecordService,
  makeTypedRealtime,
  type CollectionMeta,
  type WithExpand,
  type StringOps,
  type NumberOps,
  type EnumOps,
  type RelOps,
  type Expr,
  type FieldExpr,
  type TypedFieldExpr,
  type RelationResolver,
  type RawTypedRealtime,
} from "../../../src/typed/index.js";

// ---- Records ----

export type ProfileGender = "female" | "male" | "nonbinary" | "other";
export type SubscriptionPlan = "free" | "plus" | "premium";
export interface Profile {
  id: string;
  email: string;
  username: string;
  verified: boolean;
  name: string;
  bio: string;
  website: string;
  age: number;
  gender: ProfileGender;
  avatar: string;
  created: string;
  updated: string;
}

export interface Tag {
  id: string;
  label: string;
  created: string;
  updated: string;
}

export interface Photo {
  id: string;
  owner: string;
  image: string;
  caption: string;
  tags: string[];
  created: string;
  updated: string;
}

export interface PrivatePhoto {
  id: string;
  owner: string;
  image: string;
  caption: string;
  created: string;
  updated: string;
}

export interface Message {
  id: string;
  from: string;
  to: string;
  body: string;
  sentAt: string;
  read: boolean;
  created: string;
  updated: string;
}

export interface Wink {
  id: string;
  from: string;
  to: string;
  createdAt: string;
  created: string;
  updated: string;
}

export interface Subscription {
  id: string;
  profile: string;
  plan: SubscriptionPlan;
  price: number;
  renewsAt: string;
  active: boolean;
  metadata: unknown;
  created: string;
  updated: string;
}


// ---- Create / Update payloads ----

export interface ProfileCreate {
  email: string;
  password: string;
  passwordConfirm: string;
  name?: string;
  bio?: string;
  website?: string;
  age?: number;
  gender?: ProfileGender;
  avatar?: File | Blob;
}
export type ProfileUpdate = Partial<Omit<ProfileCreate, "password" | "passwordConfirm">>;
export interface TagCreate {
  label: string;
}
export type TagUpdate = Partial<TagCreate>;
export interface PhotoCreate {
  owner?: string;
  image?: File | Blob;
  caption?: string;
  tags?: string[];
}
export type PhotoUpdate = Partial<PhotoCreate>;
export interface PrivatePhotoCreate {
  owner?: string;
  image?: File | Blob;
  caption?: string;
}
export type PrivatePhotoUpdate = Partial<PrivatePhotoCreate>;
export interface MessageCreate {
  body: string;
  from?: string;
  to?: string;
  sentAt?: string;
  read?: boolean;
}
export type MessageUpdate = Partial<MessageCreate>;
export interface WinkCreate {
  from?: string;
  to?: string;
  createdAt?: string;
}
export type WinkUpdate = Partial<WinkCreate>;
export interface SubscriptionCreate {
  profile?: string;
  plan?: SubscriptionPlan;
  price?: number;
  renewsAt?: string;
  active?: boolean;
  metadata?: unknown;
}
export type SubscriptionUpdate = Partial<SubscriptionCreate>;

// ---- Where types ----

export interface ProfileWhere {
  email?: StringOps | string;
  username?: StringOps | string;
  verified?: boolean;
  name?: StringOps | string;
  bio?: StringOps | string;
  website?: StringOps | string;
  age?: NumberOps | number;
  gender?: EnumOps<ProfileGender> | ProfileGender;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: ProfileWhere[];
  OR?: ProfileWhere[];
}
export interface TagWhere {
  label?: StringOps | string;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: TagWhere[];
  OR?: TagWhere[];
}
export interface PhotoWhere {
  owner?: string | RelOps | ProfileWhere;
  caption?: StringOps | string;
  tags?: string | RelOps;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: PhotoWhere[];
  OR?: PhotoWhere[];
}
export interface PrivatePhotoWhere {
  owner?: string | RelOps | ProfileWhere;
  caption?: StringOps | string;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: PrivatePhotoWhere[];
  OR?: PrivatePhotoWhere[];
}
export interface MessageWhere {
  from?: string | RelOps | ProfileWhere;
  to?: string | RelOps | ProfileWhere;
  body?: StringOps | string;
  sentAt?: StringOps | string;
  read?: boolean;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: MessageWhere[];
  OR?: MessageWhere[];
}
export interface WinkWhere {
  from?: string | RelOps | ProfileWhere;
  to?: string | RelOps | ProfileWhere;
  createdAt?: StringOps | string;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: WinkWhere[];
  OR?: WinkWhere[];
}
export interface SubscriptionWhere {
  profile?: string | RelOps | ProfileWhere;
  plan?: EnumOps<SubscriptionPlan> | SubscriptionPlan;
  price?: NumberOps | number;
  renewsAt?: StringOps | string;
  active?: boolean;
  metadata?: unknown;
  id?: StringOps | string;
  created?: StringOps | string;
  updated?: StringOps | string;
  AND?: SubscriptionWhere[];
  OR?: SubscriptionWhere[];
}

// ---- Relations + expand keys ----

export type PhotoRelations = { owner: Profile; tags: Tag[] };
export type PhotoExpand = "owner" | "tags";
export type PrivatePhotoRelations = { owner: Profile };
export type PrivatePhotoExpand = "owner";
export type MessageRelations = { from: Profile; to: Profile };
export type MessageExpand = "from" | "to";
export type WinkRelations = { from: Profile; to: Profile };
export type WinkExpand = "from" | "to";
export type SubscriptionRelations = { profile: Profile };
export type SubscriptionExpand = "profile";

// ---- Fluent accessor types ----

export interface ProfileFields {
  email: TypedFieldExpr<string>;
  username: TypedFieldExpr<string>;
  verified: TypedFieldExpr<boolean>;
  name: TypedFieldExpr<string>;
  bio: TypedFieldExpr<string>;
  website: TypedFieldExpr<string>;
  age: TypedFieldExpr<number>;
  gender: TypedFieldExpr<ProfileGender>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface TagFields {
  label: TypedFieldExpr<string>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface PhotoFields {
  owner: TypedFieldExpr<string>;
  caption: TypedFieldExpr<string>;
  tags: TypedFieldExpr<string>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface PrivatePhotoFields {
  owner: TypedFieldExpr<string>;
  caption: TypedFieldExpr<string>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface MessageFields {
  from: TypedFieldExpr<string>;
  to: TypedFieldExpr<string>;
  body: TypedFieldExpr<string>;
  sentAt: TypedFieldExpr<string>;
  read: TypedFieldExpr<boolean>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface WinkFields {
  from: TypedFieldExpr<string>;
  to: TypedFieldExpr<string>;
  createdAt: TypedFieldExpr<string>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}
export interface SubscriptionFields {
  profile: TypedFieldExpr<string>;
  plan: TypedFieldExpr<SubscriptionPlan>;
  price: TypedFieldExpr<number>;
  renewsAt: TypedFieldExpr<string>;
  active: TypedFieldExpr<boolean>;
  metadata: TypedFieldExpr<unknown>;
  id: TypedFieldExpr<string>;
  created: TypedFieldExpr<string>;
  updated: TypedFieldExpr<string>;
}

// ---- Concrete service interfaces ----

export interface ProfilesService {
  getOne(id: string, opts?: { fields?: string; signal?: AbortSignal; requestKey?: string }): Promise<Profile>;
  getList(opts?: {
    where?: ProfileWhere;
    sort?: string;
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<ListResult<Profile>>;
  getFirstListItem(opts?: {
    where?: ProfileWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<Profile>;
  getPage(opts?: {
    where?: ProfileWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<CursorPage<Profile>>;
  iterate(opts?: {
    where?: ProfileWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): AsyncIterableIterator<Profile>;
  getFullList(opts?: {
    where?: ProfileWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<Profile[]>;
  create(
    data: ProfileCreate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<Profile>;
  update(
    id: string,
    data: ProfileUpdate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<Profile>;
  delete(id: string): Promise<void>;
  filter(fn: (f: ProfileFields) => Expr): string;
  authWithPassword(
    identity: string,
    password: string,
  ): Promise<{ token: string; record: Profile }>;
  fileUrl(record: Profile, field: ProfileFileField, opts?: FileUrlOptions): string;
}
export interface TagsService {
  getOne(id: string, opts?: { fields?: string; signal?: AbortSignal; requestKey?: string }): Promise<Tag>;
  getList(opts?: {
    where?: TagWhere;
    sort?: string;
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<ListResult<Tag>>;
  getFirstListItem(opts?: {
    where?: TagWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<Tag>;
  getPage(opts?: {
    where?: TagWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<CursorPage<Tag>>;
  iterate(opts?: {
    where?: TagWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): AsyncIterableIterator<Tag>;
  getFullList(opts?: {
    where?: TagWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<Tag[]>;
  create(
    data: TagCreate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<Tag>;
  update(
    id: string,
    data: TagUpdate,
    opts?: { fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<Tag>;
  delete(id: string): Promise<void>;
  filter(fn: (f: TagFields) => Expr): string;
}
export interface PhotosService {
  getOne<K extends PhotoExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Photo, PhotoRelations, K>>;
  getList<K extends PhotoExpand = never>(opts?: {
    where?: PhotoWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<ListResult<WithExpand<Photo, PhotoRelations, K>>>;
  getFirstListItem<K extends PhotoExpand = never>(opts?: {
    where?: PhotoWhere;
    sort?: string;
    expand?: K[];
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<WithExpand<Photo, PhotoRelations, K>>;
  getPage(opts?: {
    where?: PhotoWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<CursorPage<Photo>>;
  iterate(opts?: {
    where?: PhotoWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): AsyncIterableIterator<Photo>;
  getFullList(opts?: {
    where?: PhotoWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<Photo[]>;
  create<K extends PhotoExpand = never>(
    data: PhotoCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Photo, PhotoRelations, K>>;
  update<K extends PhotoExpand = never>(
    id: string,
    data: PhotoUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Photo, PhotoRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: PhotoFields) => Expr): string;
  fileUrl(record: Photo, field: PhotoFileField, opts?: FileUrlOptions): string;
}
export interface PrivatePhotosService {
  getOne<K extends PrivatePhotoExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<PrivatePhoto, PrivatePhotoRelations, K>>;
  getList<K extends PrivatePhotoExpand = never>(opts?: {
    where?: PrivatePhotoWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<ListResult<WithExpand<PrivatePhoto, PrivatePhotoRelations, K>>>;
  getFirstListItem<K extends PrivatePhotoExpand = never>(opts?: {
    where?: PrivatePhotoWhere;
    sort?: string;
    expand?: K[];
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<WithExpand<PrivatePhoto, PrivatePhotoRelations, K>>;
  getPage(opts?: {
    where?: PrivatePhotoWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<CursorPage<PrivatePhoto>>;
  iterate(opts?: {
    where?: PrivatePhotoWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): AsyncIterableIterator<PrivatePhoto>;
  getFullList(opts?: {
    where?: PrivatePhotoWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<PrivatePhoto[]>;
  create<K extends PrivatePhotoExpand = never>(
    data: PrivatePhotoCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<PrivatePhoto, PrivatePhotoRelations, K>>;
  update<K extends PrivatePhotoExpand = never>(
    id: string,
    data: PrivatePhotoUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<PrivatePhoto, PrivatePhotoRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: PrivatePhotoFields) => Expr): string;
  fileUrl(record: PrivatePhoto, field: PrivatePhotoFileField, opts?: FileUrlOptions): string;
}
export interface MessagesService {
  getOne<K extends MessageExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Message, MessageRelations, K>>;
  getList<K extends MessageExpand = never>(opts?: {
    where?: MessageWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<ListResult<WithExpand<Message, MessageRelations, K>>>;
  getFirstListItem<K extends MessageExpand = never>(opts?: {
    where?: MessageWhere;
    sort?: string;
    expand?: K[];
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<WithExpand<Message, MessageRelations, K>>;
  getPage(opts?: {
    where?: MessageWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<CursorPage<Message>>;
  iterate(opts?: {
    where?: MessageWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): AsyncIterableIterator<Message>;
  getFullList(opts?: {
    where?: MessageWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<Message[]>;
  create<K extends MessageExpand = never>(
    data: MessageCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Message, MessageRelations, K>>;
  update<K extends MessageExpand = never>(
    id: string,
    data: MessageUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Message, MessageRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: MessageFields) => Expr): string;
}
export interface WinksService {
  getOne<K extends WinkExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Wink, WinkRelations, K>>;
  getList<K extends WinkExpand = never>(opts?: {
    where?: WinkWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<ListResult<WithExpand<Wink, WinkRelations, K>>>;
  getFirstListItem<K extends WinkExpand = never>(opts?: {
    where?: WinkWhere;
    sort?: string;
    expand?: K[];
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<WithExpand<Wink, WinkRelations, K>>;
  getPage(opts?: {
    where?: WinkWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<CursorPage<Wink>>;
  iterate(opts?: {
    where?: WinkWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): AsyncIterableIterator<Wink>;
  getFullList(opts?: {
    where?: WinkWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<Wink[]>;
  create<K extends WinkExpand = never>(
    data: WinkCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Wink, WinkRelations, K>>;
  update<K extends WinkExpand = never>(
    id: string,
    data: WinkUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Wink, WinkRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: WinkFields) => Expr): string;
}
export interface SubscriptionsService {
  getOne<K extends SubscriptionExpand = never>(
    id: string,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Subscription, SubscriptionRelations, K>>;
  getList<K extends SubscriptionExpand = never>(opts?: {
    where?: SubscriptionWhere;
    sort?: string;
    expand?: K[];
    page?: number;
    limit?: number;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<ListResult<WithExpand<Subscription, SubscriptionRelations, K>>>;
  getFirstListItem<K extends SubscriptionExpand = never>(opts?: {
    where?: SubscriptionWhere;
    sort?: string;
    expand?: K[];
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<WithExpand<Subscription, SubscriptionRelations, K>>;
  getPage(opts?: {
    where?: SubscriptionWhere;
    sort?: string;
    limit?: number;
    cursor?: string;
    withTotal?: boolean;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<CursorPage<Subscription>>;
  iterate(opts?: {
    where?: SubscriptionWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): AsyncIterableIterator<Subscription>;
  getFullList(opts?: {
    where?: SubscriptionWhere;
    sort?: string;
    fields?: string;
    signal?: AbortSignal;
    requestKey?: string;
  }): Promise<Subscription[]>;
  create<K extends SubscriptionExpand = never>(
    data: SubscriptionCreate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Subscription, SubscriptionRelations, K>>;
  update<K extends SubscriptionExpand = never>(
    id: string,
    data: SubscriptionUpdate,
    opts?: { expand?: K[]; fields?: string; signal?: AbortSignal; requestKey?: string },
  ): Promise<WithExpand<Subscription, SubscriptionRelations, K>>;
  delete(id: string): Promise<void>;
  filter(fn: (f: SubscriptionFields) => Expr): string;
}

// ---- Per-collection metadata ----

export const profilesMeta: CollectionMeta = {
  name: "profiles",
  fields: {
    id: { type: "text" },
    email: { type: "email" },
    username: { type: "text" },
    verified: { type: "bool" },
    name: { type: "text" },
    bio: { type: "editor" },
    website: { type: "url" },
    age: { type: "number", mode: "int" },
    gender: { type: "select" },
    avatar: { type: "file" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: ["avatar"],
  expandable: [],
  isAuth: true,
};
export const tagsMeta: CollectionMeta = {
  name: "tags",
  fields: {
    id: { type: "text" },
    label: { type: "text" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: [],
  expandable: [],
  isAuth: false,
};
export const photosMeta: CollectionMeta = {
  name: "photos",
  fields: {
    id: { type: "text" },
    owner: { type: "relation" },
    image: { type: "file" },
    caption: { type: "text" },
    tags: { type: "relation", multi: true },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: ["image"],
  expandable: ["owner", "tags"],
  isAuth: false,
};
export const privatePhotosMeta: CollectionMeta = {
  name: "privatePhotos",
  fields: {
    id: { type: "text" },
    owner: { type: "relation" },
    image: { type: "file" },
    caption: { type: "text" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: ["image"],
  expandable: ["owner"],
  isAuth: false,
};
export const messagesMeta: CollectionMeta = {
  name: "messages",
  fields: {
    id: { type: "text" },
    from: { type: "relation" },
    to: { type: "relation" },
    body: { type: "text" },
    sentAt: { type: "autodate" },
    read: { type: "bool" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: [],
  expandable: ["from", "to"],
  isAuth: false,
};
export const winksMeta: CollectionMeta = {
  name: "winks",
  fields: {
    id: { type: "text" },
    from: { type: "relation" },
    to: { type: "relation" },
    createdAt: { type: "autodate" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: [],
  expandable: ["from", "to"],
  isAuth: false,
};
export const subscriptionsMeta: CollectionMeta = {
  name: "subscriptions",
  fields: {
    id: { type: "text" },
    profile: { type: "relation" },
    plan: { type: "select" },
    price: { type: "number", mode: "fixed", scale: 2 },
    renewsAt: { type: "date" },
    active: { type: "bool" },
    metadata: { type: "json" },
    created: { type: "autodate" },
    updated: { type: "autodate" },
  },
  fileFields: [],
  expandable: ["profile"],
  isAuth: false,
};
const relationResolver: RelationResolver = (collection, field) => {
  if (collection === "photos" && field === "owner") return profilesMeta;
  if (collection === "photos" && field === "tags") return tagsMeta;
  if (collection === "privatePhotos" && field === "owner") return profilesMeta;
  if (collection === "messages" && field === "from") return profilesMeta;
  if (collection === "messages" && field === "to") return profilesMeta;
  if (collection === "winks" && field === "from") return profilesMeta;
  if (collection === "winks" && field === "to") return profilesMeta;
  if (collection === "subscriptions" && field === "profile") return profilesMeta;
  return undefined;
};

// ---- Typed files surface ----

export type ProfileFileField = "avatar";
export type PhotoFileField = "image";
export type PrivatePhotoFileField = "image";

// ---- Typed realtime surface ----

export type ProfilesRealtime = RawTypedRealtime<Profile, ProfileWhere>;
export type TagsRealtime = RawTypedRealtime<Tag, TagWhere>;
export type PhotosRealtime = RawTypedRealtime<Photo, PhotoWhere>;
export type PrivatePhotosRealtime = RawTypedRealtime<PrivatePhoto, PrivatePhotoWhere>;
export type MessagesRealtime = RawTypedRealtime<Message, MessageWhere>;
export type WinksRealtime = RawTypedRealtime<Wink, WinkWhere>;
export type SubscriptionsRealtime = RawTypedRealtime<Subscription, SubscriptionWhere>;

// ---- createClient ----

export interface SendWinkOut {
  ok: boolean;
  note: string;
}
export type Color = "red" | "green" | "blue";
export interface SendWinkIn {
  note: string;
  color: Color;
  sticker: string | null;
  tags: string[];
}
export type SearchSort = "newest" | "oldest";
export interface SearchIn {
  q: string;
  limit: number;
  sort: SearchSort;
}
export interface SearchOut {
  count: number;
}
export interface ZbClient {
  db: {
    profiles: ProfilesService;
    tags: TagsService;
    photos: PhotosService;
    privatePhotos: PrivatePhotosService;
    messages: MessagesService;
    winks: WinksService;
    subscriptions: SubscriptionsService;
  };
  realtime: {
    profiles: ProfilesRealtime;
    tags: TagsRealtime;
    photos: PhotosRealtime;
    privatePhotos: PrivatePhotosRealtime;
    messages: MessagesRealtime;
    winks: WinksRealtime;
    subscriptions: SubscriptionsRealtime;
  };
  files: FilesService;
  rpc: {
    echoPing(params: { id: string }, opts?: SendOptions): Promise<SendWinkOut>;
    winksSend(input: SendWinkIn, opts?: SendOptions): Promise<SendWinkOut>;
    messagesSearch(input: SearchIn, opts?: SendOptions): Promise<SearchOut>;
    winksStatus(opts?: SendOptions): Promise<void>;
    winksRaw(opts?: SendOptions): Promise<unknown>;
  };
  authStore: Client["authStore"];
  send: Client["send"];
  fetch: Client["fetch"];
}
export interface ZbClientOptions {
  fetch?: typeof fetch;
  WebSocket?: typeof WebSocket;
  authCollection?: string;
}
export function createClient(url: string, opts: ZbClientOptions = {}): ZbClient {
  const base: RealtimeEnabledClient = withRealtime(
    baseCreateClient(url, {
      fetch: opts.fetch,
      WebSocket: opts.WebSocket,
      authCollection: opts.authCollection ?? "profiles",
    }),
  );

  return {
    db: {
      profiles: Object.assign(
        makeRecordService(base, profilesMeta) as unknown as ProfilesService,
        {
          authWithPassword: (identity: string, password: string) =>
            base.collection("profiles").authWithPassword(identity, password),
          fileUrl: (record: any, field: any, opts: any) =>
            base.files.getUrl({ id: record.id, collectionName: "profiles" }, (record as Record<string, string>)[field] ?? "", opts),
        },
      ) as unknown as ProfilesService,
      tags: makeRecordService(base, tagsMeta) as unknown as TagsService,
      photos: Object.assign(
        makeRecordService(base, photosMeta, relationResolver) as unknown as PhotosService,
        {
          fileUrl: (record: any, field: any, opts: any) =>
            base.files.getUrl({ id: record.id, collectionName: "photos" }, (record as Record<string, string>)[field] ?? "", opts),
        },
      ) as unknown as PhotosService,
      privatePhotos: Object.assign(
        makeRecordService(base, privatePhotosMeta, relationResolver) as unknown as PrivatePhotosService,
        {
          fileUrl: (record: any, field: any, opts: any) =>
            base.files.getUrl({ id: record.id, collectionName: "privatePhotos" }, (record as Record<string, string>)[field] ?? "", opts),
        },
      ) as unknown as PrivatePhotosService,
      messages: makeRecordService(base, messagesMeta, relationResolver) as unknown as MessagesService,
      winks: makeRecordService(base, winksMeta, relationResolver) as unknown as WinksService,
      subscriptions: makeRecordService(base, subscriptionsMeta, relationResolver) as unknown as SubscriptionsService,
    },
    realtime: {
      profiles: makeTypedRealtime<Profile, ProfileWhere>(base.realtime, profilesMeta),
      tags: makeTypedRealtime<Tag, TagWhere>(base.realtime, tagsMeta),
      photos: makeTypedRealtime<Photo, PhotoWhere>(base.realtime, photosMeta, relationResolver),
      privatePhotos: makeTypedRealtime<PrivatePhoto, PrivatePhotoWhere>(base.realtime, privatePhotosMeta, relationResolver),
      messages: makeTypedRealtime<Message, MessageWhere>(base.realtime, messagesMeta, relationResolver),
      winks: makeTypedRealtime<Wink, WinkWhere>(base.realtime, winksMeta, relationResolver),
      subscriptions: makeTypedRealtime<Subscription, SubscriptionWhere>(base.realtime, subscriptionsMeta, relationResolver),
    },
    files: base.files,
    rpc: {
      echoPing(params, opts) {
        return base.send("POST", `/api/echo/${encodeURIComponent(String(params.id))}/ping`, opts);
      },
      winksSend(input, opts) {
        return base.send("POST", `/api/winks/send`, { body: input, ...opts });
      },
      messagesSearch(input, opts) {
        return base.send("GET", `/api/messages/search`, { query: input as unknown as Record<string, string | number | boolean | undefined>, ...opts });
      },
      winksStatus(opts) {
        return base.send("GET", `/api/winks/status`, opts);
      },
      winksRaw(opts) {
        return base.send("GET", `/api/winks/raw`, opts);
      },
    },
    authStore: base.authStore,
    send: base.send.bind(base),
    fetch: base.fetch.bind(base),
  };
}
